"""Generated by packages/contracts/corpus/generate.mjs; do not edit by hand."""

# ruff: noqa: E501 - embedded governed JSON Schema retains exact source text

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from datetime import datetime
from typing import Any

CORPUS_MEMBERSHIP_SCHEMA_SHA256 = "921db7c4511dd5a1f9c361acb89e2841b6eb7e3fc9558e69ab0e1a2f5840ec45"
CORPUS_MEMBERSHIP_SCHEMA: dict[str, Any] = json.loads(r"""{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://research-observatory.local/contracts/corpus/corpus-membership.schema.json",
  "title": "Research Observatory corpus membership documents",
  "description": "Portable T01 projection, immutable discovery path, and consequential decision; Core resolves authority and commits them atomically.",
  "x-research-observatory-semanticRules": [
    "identity-and-revision-distinct",
    "initial-candidate-pending-with-unknown-availability-no-duplicate-or-decision",
    "later-revision-requires-decision",
    "discovery-path-ids-sorted-unique",
    "discovery-kind-has-exact-typed-source",
    "discovery-edge-direction-time-and-predecessor",
    "decision-identities-and-values-distinct",
    "decision-evidence-sorted-unique",
    "work-target-only-for-work-reference",
    "decision-time-is-real-canonical-utc-milliseconds"
  ],
  "x-research-observatory-membershipLifecycle": {
    "sourcePath": "packages/contracts/domain/domain-lifecycle.v1.json",
    "sourceSha256": "99386404ed393d385f223680a2dbafba10c995eadfc1e0c4d912e180322c5125",
    "profileVersion": "1.0.0",
    "subjectKind": "corpus-item",
    "initialState": "candidate",
    "terminalStates": [
      "withdrawn"
    ],
    "transitions": [
      {
        "command": "include",
        "from": "candidate",
        "to": "included"
      },
      {
        "command": "exclude",
        "from": "candidate",
        "to": "excluded"
      },
      {
        "command": "reconsider",
        "from": "included",
        "to": "candidate"
      },
      {
        "command": "reconsider",
        "from": "excluded",
        "to": "candidate"
      },
      {
        "command": "withdraw",
        "from": "candidate",
        "to": "withdrawn"
      },
      {
        "command": "withdraw",
        "from": "included",
        "to": "withdrawn"
      },
      {
        "command": "withdraw",
        "from": "excluded",
        "to": "withdrawn"
      }
    ]
  },
  "oneOf": [
    {
      "$ref": "#/$defs/CorpusItemRevision"
    },
    {
      "$ref": "#/$defs/DiscoveryPath"
    },
    {
      "$ref": "#/$defs/CorpusDecision"
    }
  ],
  "$defs": {
    "UuidV7": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?![\\s\\S])"
    },
    "ProjectId": {
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[47][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?![\\s\\S])"
    },
    "Digest": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}(?![\\s\\S])"
    },
    "NullableUuidV7": {
      "anyOf": [
        {
          "$ref": "#/$defs/UuidV7"
        },
        {
          "type": "null"
        }
      ]
    },
    "NullableDigest": {
      "anyOf": [
        {
          "$ref": "#/$defs/Digest"
        },
        {
          "type": "null"
        }
      ]
    },
    "NullableOrdinal": {
      "anyOf": [
        {
          "type": "integer",
          "minimum": 0,
          "maximum": 200000
        },
        {
          "type": "null"
        }
      ]
    },
    "Membership": {
      "enum": [
        "candidate",
        "included",
        "excluded",
        "withdrawn"
      ]
    },
    "Review": {
      "enum": [
        "none",
        "pending"
      ]
    },
    "Availability": {
      "enum": [
        "unknown",
        "not-applicable",
        "available",
        "unavailable"
      ]
    },
    "Dimension": {
      "enum": [
        "membership",
        "review",
        "duplicate",
        "availability",
        "discovery",
        "work-reference"
      ]
    },
    "DiscoveryKind": {
      "enum": [
        "import-member",
        "connector-record",
        "citation",
        "recommendation",
        "manual"
      ]
    },
    "CommandCode": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9-]{0,63}(?![\\s\\S])"
    },
    "DecisionValue": {
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "UtcMillis": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z(?![\\s\\S])"
    },
    "CorpusItemRevision": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "projectId",
        "itemId",
        "revisionId",
        "previousRevisionId",
        "workId",
        "workRevisionId",
        "membership",
        "review",
        "duplicateOfItemId",
        "availability",
        "discoveryPathIds",
        "decisionRevisionId"
      ],
      "properties": {
        "schemaVersion": {
          "const": "1.0"
        },
        "contractVersion": {
          "const": "1.0.0"
        },
        "documentType": {
          "const": "research-observatory-corpus-item-revision"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectId"
        },
        "itemId": {
          "$ref": "#/$defs/UuidV7"
        },
        "revisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "previousRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "workId": {
          "$ref": "#/$defs/UuidV7"
        },
        "workRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "membership": {
          "$ref": "#/$defs/Membership"
        },
        "review": {
          "$ref": "#/$defs/Review"
        },
        "duplicateOfItemId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "availability": {
          "$ref": "#/$defs/Availability"
        },
        "discoveryPathIds": {
          "type": "array",
          "minItems": 1,
          "maxItems": 1000,
          "items": {
            "$ref": "#/$defs/UuidV7"
          }
        },
        "decisionRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        }
      }
    },
    "DiscoveryPath": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "pathId",
        "projectId",
        "itemId",
        "kind",
        "sourceRevisionId",
        "direction",
        "occurredAt",
        "predecessorItemRevisionId",
        "contextId",
        "contextRevisionId",
        "ordinal",
        "recordKeySha256",
        "queryRevisionId",
        "citingWorkRevisionId",
        "recommendationRevisionId",
        "manualDecisionRevisionId"
      ],
      "properties": {
        "schemaVersion": {
          "const": "1.0"
        },
        "contractVersion": {
          "const": "1.0.0"
        },
        "documentType": {
          "const": "research-observatory-discovery-path"
        },
        "pathId": {
          "$ref": "#/$defs/UuidV7"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectId"
        },
        "itemId": {
          "$ref": "#/$defs/UuidV7"
        },
        "kind": {
          "$ref": "#/$defs/DiscoveryKind"
        },
        "sourceRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "direction": {
          "const": "source-to-corpus-item"
        },
        "occurredAt": {
          "$ref": "#/$defs/UtcMillis"
        },
        "predecessorItemRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "contextId": {
          "$ref": "#/$defs/UuidV7"
        },
        "contextRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "ordinal": {
          "$ref": "#/$defs/NullableOrdinal"
        },
        "recordKeySha256": {
          "$ref": "#/$defs/NullableDigest"
        },
        "queryRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "citingWorkRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "recommendationRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "manualDecisionRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        }
      }
    },
    "CorpusDecision": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "decisionId",
        "projectId",
        "itemId",
        "previousRevisionId",
        "nextRevisionId",
        "dimension",
        "command",
        "previousValue",
        "nextValue",
        "previousDecisionRevisionId",
        "supersedesDecisionRevisionId",
        "nextWorkId",
        "actorId",
        "reasonCode",
        "protocolRevisionId",
        "evidenceRevisionIds",
        "occurredAt"
      ],
      "properties": {
        "schemaVersion": {
          "const": "1.0"
        },
        "contractVersion": {
          "const": "1.0.0"
        },
        "documentType": {
          "const": "research-observatory-corpus-decision"
        },
        "decisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectId"
        },
        "itemId": {
          "$ref": "#/$defs/UuidV7"
        },
        "previousRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "nextRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "dimension": {
          "$ref": "#/$defs/Dimension"
        },
        "command": {
          "$ref": "#/$defs/CommandCode"
        },
        "previousValue": {
          "$ref": "#/$defs/DecisionValue"
        },
        "nextValue": {
          "$ref": "#/$defs/DecisionValue"
        },
        "previousDecisionRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "supersedesDecisionRevisionId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "nextWorkId": {
          "$ref": "#/$defs/NullableUuidV7"
        },
        "actorId": {
          "$ref": "#/$defs/UuidV7"
        },
        "reasonCode": {
          "$ref": "#/$defs/CommandCode"
        },
        "protocolRevisionId": {
          "$ref": "#/$defs/UuidV7"
        },
        "evidenceRevisionIds": {
          "type": "array",
          "minItems": 1,
          "maxItems": 64,
          "items": {
            "$ref": "#/$defs/UuidV7"
          }
        },
        "occurredAt": {
          "$ref": "#/$defs/UtcMillis"
        }
      }
    }
  }
}""")
_KINDS = {
    "CorpusItemRevision": "research-observatory-corpus-item-revision",
    "DiscoveryPath": "research-observatory-discovery-path",
    "CorpusDecision": "research-observatory-corpus-decision",
}


def _matches(value: object, node: dict[str, Any], depth: int = 0) -> bool:
    """Validate the bounded JSON Schema subset used by this generated contract."""

    if depth > 12:
        return False
    if "$ref" in node:
        reference = node["$ref"]
        return (
            isinstance(reference, str)
            and reference.startswith("#/$defs/")
            and _matches(value, CORPUS_MEMBERSHIP_SCHEMA["$defs"][reference[8:]], depth + 1)
        )
    if "const" in node and value != node["const"]:
        return False
    if "enum" in node and value not in node["enum"]:
        return False
    if "anyOf" in node and not any(_matches(value, option, depth + 1) for option in node["anyOf"]):
        return False
    if "oneOf" in node and sum(_matches(value, option, depth + 1) for option in node["oneOf"]) != 1:
        return False
    kind = node.get("type")
    if kind == "null":
        return value is None
    if kind == "string":
        if type(value) is not str or len(value) > 256:
            return False
        if "minLength" in node and len(value) < node["minLength"]:
            return False
        if "maxLength" in node and len(value) > node["maxLength"]:
            return False
        if "pattern" in node and re.search(node["pattern"], value) is None:
            return False
    if kind == "integer":
        if type(value) is not int or abs(value) > 9007199254740991:
            return False
        if "minimum" in node and value < node["minimum"]:
            return False
        if "maximum" in node and value > node["maximum"]:
            return False
    if kind == "array":
        if type(value) is not list or len(value) > 1000:
            return False
        if "minItems" in node and len(value) < node["minItems"]:
            return False
        if "maxItems" in node and len(value) > node["maxItems"]:
            return False
        if not all(_matches(child, node["items"], depth + 1) for child in value):
            return False
    if kind == "object":
        if type(value) is not dict or len(value) > 32 or any(type(key) is not str for key in value):
            return False
        properties = node["properties"]
        if node.get("additionalProperties") is False and any(key not in properties for key in value):
            return False
        if not all(key in value for key in node["required"]):
            return False
        if not all(_matches(child, properties[key], depth + 1) for key, child in value.items()):
            return False
    return True


def _sorted_unique(values: object) -> bool:
    return isinstance(values, list) and all(
        isinstance(value, str) and (index == 0 or values[index - 1] < value) for index, value in enumerate(values)
    )


def _canonical_utc_millis(value: str) -> bool:
    try:
        instant = datetime.fromisoformat(value[:-1] + "+00:00")
    except ValueError:
        return False
    return instant.isoformat(timespec="milliseconds").replace("+00:00", "Z") == value


def _semantic_error(item: dict[str, Any]) -> str | None:
    kind = item["documentType"]
    if kind == _KINDS["CorpusItemRevision"]:
        if item["itemId"] in {item["revisionId"], item["workId"]} or item["previousRevisionId"] == item["revisionId"]:
            return "corpus-item-identity-invalid"
        if item["duplicateOfItemId"] == item["itemId"]:
            return "corpus-duplicate-self-invalid"
        if not _sorted_unique(item["discoveryPathIds"]):
            return "corpus-discovery-paths-invalid"
        if item["previousRevisionId"] is None and (
            item["membership"] != "candidate"
            or item["review"] != "pending"
            or item["duplicateOfItemId"] is not None
            or item["availability"] != "unknown"
            or item["decisionRevisionId"] is not None
        ):
            return "corpus-initial-state-invalid"
        if item["previousRevisionId"] is not None and item["decisionRevisionId"] is None:
            return "corpus-decision-required"
        return None
    if kind == _KINDS["DiscoveryPath"]:
        if (
            item["pathId"] == item["itemId"]
            or item["sourceRevisionId"] == item["pathId"]
            or item["predecessorItemRevisionId"] in {item["itemId"], item["pathId"]}
        ):
            return "corpus-discovery-identity-invalid"
        if not _canonical_utc_millis(item["occurredAt"]):
            return "corpus-discovery-time-invalid"
        typed = (
            item["queryRevisionId"],
            item["citingWorkRevisionId"],
            item["recommendationRevisionId"],
            item["manualDecisionRevisionId"],
        )
        if item["kind"] == "import-member":
            if item["ordinal"] is None or item["ordinal"] < 1 or item["recordKeySha256"] is None or any(typed):
                return "corpus-import-path-invalid"
        elif item["kind"] == "connector-record":
            if (
                item["ordinal"] is None
                or item["ordinal"] > 999
                or item["recordKeySha256"] is not None
                or item["queryRevisionId"] is None
                or any(typed[1:])
            ):
                return "corpus-connector-path-invalid"
        else:
            expected = {
                "citation": item["citingWorkRevisionId"],
                "recommendation": item["recommendationRevisionId"],
                "manual": item["manualDecisionRevisionId"],
            }[item["kind"]]
            if (
                item["ordinal"] is not None
                or item["recordKeySha256"] is not None
                or expected is None
                or sum(value is not None for value in typed) != 1
            ):
                return "corpus-discovery-path-invalid"
        return None
    if kind == _KINDS["CorpusDecision"]:
        if item["previousRevisionId"] == item["nextRevisionId"] or item["decisionId"] in {
            item["itemId"],
            item["previousRevisionId"],
            item["nextRevisionId"],
        }:
            return "corpus-decision-identity-invalid"
        if not _sorted_unique(item["evidenceRevisionIds"]):
            return "corpus-decision-evidence-invalid"
        if item["previousValue"] == item["nextValue"]:
            return "corpus-decision-no-change"
        if (
            item["previousDecisionRevisionId"] == item["decisionId"]
            or item["supersedesDecisionRevisionId"] == item["decisionId"]
        ):
            return "corpus-decision-self-supersession"
        if (item["nextWorkId"] is not None) != (item["dimension"] == "work-reference"):
            return "corpus-decision-work-target-invalid"
        if not _canonical_utc_millis(item["occurredAt"]):
            return "corpus-decision-time-invalid"
        return None
    return "corpus-document-type-invalid"


def corpus_contract_errors(value: object) -> tuple[str, ...]:
    """Content-free validation errors; the caller retains all authority checks."""

    try:
        if type(value) is not dict or not _matches(value, CORPUS_MEMBERSHIP_SCHEMA):
            return ("corpus-contract-schema-invalid",)
        error = _semantic_error(value)
        return () if error is None else (error,)
    except TypeError, ValueError, KeyError, RecursionError:
        return ("corpus-contract-schema-invalid",)


def decode_corpus_document(value: object) -> dict[str, Any] | None:
    if corpus_contract_errors(value):
        return None
    try:
        owned = json.loads(json.dumps(value, allow_nan=False))
        return owned if not corpus_contract_errors(owned) else None
    except TypeError, ValueError, RecursionError:
        return None


def _encode(fields: Mapping[str, object], name: str) -> dict[str, Any] | None:
    """Envelope an exact Pydantic model_dump(mode='json', by_alias=True) without model imports."""

    if not isinstance(fields, Mapping) or any(not isinstance(key, str) for key in fields):
        return None
    node = CORPUS_MEMBERSHIP_SCHEMA["$defs"][name]
    expected = {field for field in node["required"] if field not in {"contractVersion", "documentType"}}
    if set(fields) != expected:
        return None
    document = {
        field: ("1.0.0" if field == "contractVersion" else _KINDS[name] if field == "documentType" else fields[field])
        for field in node["required"]
    }
    return decode_corpus_document(document)


def encode_corpus_item_revision(fields: Mapping[str, object]) -> dict[str, Any] | None:
    return _encode(fields, "CorpusItemRevision")


def encode_discovery_path(fields: Mapping[str, object]) -> dict[str, Any] | None:
    return _encode(fields, "DiscoveryPath")


def encode_corpus_decision(fields: Mapping[str, object]) -> dict[str, Any] | None:
    return _encode(fields, "CorpusDecision")
