# Generated by packages/contracts/domain/generate-compatibility.mjs. Do not edit by hand.
# Sources: compatibility schema/policy, authority and event catalogs, and release fixtures.
from __future__ import annotations

import json
import re
from collections.abc import Callable, Mapping, Sequence
from types import MappingProxyType
from typing import Any, cast

DOMAIN_COMPATIBILITY_SCHEMA_SHA256 = "296fa313639a1e39512624755894936f46516a1fa6f662bce41794ec748bea89"
DOMAIN_COMPATIBILITY_POLICY_SHA256 = "371a01c41b4869420ce51377f298895bcd04a86b1fb5f9f00a7f7c6d36b2a92c"
PRIOR_DOMAIN_RELEASE_SHA256 = "ae4e052b69143eef0615ffd138e013063631dc8ca3869847d229b560d8e1110f"
CURRENT_DOMAIN_RELEASE_SHA256 = "bc299d6f2890717f16be9bb1f81e10470a606fd58e0dbf8584628a2a075f8418"
DOMAIN_COMPATIBILITY_AUTHORITY_SHA256 = "2ab2400e6563261980c1e48d5fe6fc0b9ffb2154c65dbda19312c2dd70b4bd3d"
DOMAIN_EVENT_CATALOG_SHA256 = "909191221f3ff762b1129b3777d8347371c011a62c0bef13a89d1a249fa2a697"

_POLICY: dict[str, Any] = json.loads(
    r"""{"schemaVersion":"1.0","documentType":"research-observatory-domain-compatibility-policy","policyVersion":"1.0.0","contractFamily":"research-observatory-domain","priorContractVersion":"0.1.0","currentContractVersion":"1.0.0","changeRules":[{"changeKind":"add-optional-field","classification":"additive","requirements":[]},{"changeKind":"widen-reader-type","classification":"additive","requirements":[]},{"changeKind":"deprecate-field","classification":"deprecation","requirements":["deprecation-window"]},{"changeKind":"add-required-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"remove-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"rename-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"narrow-reader-type","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"add-closed-enum-member","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"add-event-type","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"change-event-payload","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"change-identity-format","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"repurpose-meaning","classification":"breaking","requirements":["adr","migration"]}],"eventPolicy":{"envelopeVersioned":true,"unknownEvent":"deny-and-audit","payloadUnknownFields":"reject","supportedVersions":["0.1.0","1.0.0"]},"negotiation":{"roles":["desktop","sidecar","server"],"selection":"highest-exact-common","schemaSet":"exact-match","noOverlap":"deny"},"bridges":[{"id":"legacy-project-uuidv4-to-canonical-uuidv7","fromVersion":"0.1.0","toVersion":"1.0.0","adrId":"ADR-0013","strategy":"reader-bridge","sourceRetention":"preserved","testFixture":"packages/contracts/project/fixtures/valid-project-manifest.v1.json"}]}""",
)
_PRIOR_RELEASE: dict[str, Any] = json.loads(
    r"""{"schemaVersion":"1.0","documentType":"research-observatory-domain-contract-release","contractFamily":"research-observatory-domain","contractVersion":"0.1.0","identityFormat":"legacy-project-uuidv4-bridge","readerMode":"bridge-required","writerMode":"denied","schemaSetId":"sha256:1f9604bf780bc9182ad09b38119929c3af17276ed35599b79706e331c37ba8a9"}""",
)
_CURRENT_RELEASE: dict[str, Any] = json.loads(
    r"""{"schemaVersion":"1.0","documentType":"research-observatory-domain-contract-release","contractFamily":"research-observatory-domain","contractVersion":"1.0.0","identityFormat":"canonical-uuidv7","readerMode":"native","writerMode":"native","schemaSetId":"sha256:60cd81eb55668ffc279d7e904d7163a5b87110f81b120e9ff1a6b23e4f13b59e"}""",
)
_AUTHORITY_CATALOG: dict[str, Any] = json.loads(
    r"""{"schemaVersion":"1.0","documentType":"research-observatory-domain-compatibility-authority-catalog","catalogVersion":"1.0.0","authorities":[{"id":"authority.uuidv4-project-to-uuidv7-domain","changeKind":"change-identity-format","fromVersion":"0.1.0","toVersion":"1.0.0","applicableTask":"CAP-03.S01.T03","adr":{"id":"ADR-0013","status":"Accepted","decisionScope":"Portable aggregate and revision identity, UUID minting authority, common scholarly value objects, and deterministic Python/TypeScript generation from the core domain schema.","path":"docs/adr/ADR-0013-adopt-uuidv7-aggregate-identities-and-schema-generated-domain-contracts.md","sha256":"b0a99951ad83939e5007412efba423981ee3167f145ef76b371d172fa0109536"},"migration":{"id":"legacy-project-uuidv4-to-canonical-uuidv7","strategy":"reader-bridge","sourceRetention":"preserved","fixturePath":"packages/contracts/project/fixtures/valid-project-manifest.v1.json","fixtureSha256":"f4bc0bd218fa8f42d71861c4bea539cef6d80d8031eac21ce8626e06f71e13e0","compatibilityTestPath":"packages/contracts/domain/compatibility.test.ts","compatibilityTestSha256":"1e2e7eae0f8fb185904bf27822509822b11c1f4d7cef75f1f271a6dda9b65d2a"}}]}""",  # noqa: E501
)
_EVENT_CATALOG: dict[str, Any] = json.loads(
    r"""{"schemaVersion":"1.0","documentType":"research-observatory-domain-event-catalog","catalogVersion":"1.0.0","payloadSchemaId":"sha256:77d82e9fe47c51c7b4bc70c38c203497a0323081a00eb0a0ac899c5849bcb3a3","events":[{"eventType":"domain.lifecycle-transition","eventVersion":"0.1.0","payloadDocumentType":"research-observatory-domain-lifecycle-transition","payloadRequiredFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"],"payloadAllowedFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"]},{"eventType":"domain.lifecycle-transition","eventVersion":"1.0.0","payloadDocumentType":"research-observatory-domain-lifecycle-transition","payloadRequiredFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"],"payloadAllowedFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"]}]}""",
)
_SAFE_SEMVER = re.compile(
    r"^(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\."
    r"(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\."
    r"(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])$"
)
_PORTABLE_ID = re.compile(r"^[a-z][a-z0-9]*(?:[.:_-][a-z0-9]+){0,11}$")
_ADR_ID = re.compile(r"^ADR-[0-9]{4}$")
_SHA256_ID = re.compile(r"^sha256:[0-9a-f]{64}$")
_ROLES = ("desktop", "sidecar", "server")
_CHANGE_KINDS = (
    "add-optional-field",
    "widen-reader-type",
    "deprecate-field",
    "add-required-field",
    "remove-field",
    "rename-field",
    "narrow-reader-type",
    "add-closed-enum-member",
    "add-event-type",
    "change-event-payload",
    "change-identity-format",
    "repurpose-meaning",
)

type FrozenJson = None | bool | int | float | str | tuple["FrozenJson", ...] | Mapping[str, "FrozenJson"]


class DomainCompatibilityProblem(ValueError):
    def __init__(self, codes: Sequence[str]) -> None:
        self.codes = tuple(codes)
        super().__init__(self.codes[0] if self.codes else "compatibility-denied")


def _record(value: object) -> Mapping[str, Any] | None:
    return cast(Mapping[str, Any], value) if isinstance(value, Mapping) else None


def _deep_freeze(value: object) -> FrozenJson:
    if isinstance(value, Mapping):
        return MappingProxyType({str(key): _deep_freeze(item) for key, item in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_deep_freeze(item) for item in value)
    return cast(None | bool | int | float | str, value)


def _exact_keys(value: Mapping[str, Any], keys: Sequence[str]) -> bool:
    return set(value) == set(keys)


def _is_semver(value: object) -> bool:
    return isinstance(value, str) and _SAFE_SEMVER.fullmatch(value) is not None


def _semver_parts(value: str) -> tuple[int, int, int]:
    major, minor, patch = value.split(".")
    return int(major), int(minor), int(patch)


def _compare_semver(left: str, right: str) -> int:
    left_parts = _semver_parts(left)
    right_parts = _semver_parts(right)
    return (left_parts > right_parts) - (left_parts < right_parts)


def _ordered_versions(value: object) -> bool:
    if not isinstance(value, (list, tuple)) or not 1 <= len(value) <= 8 or not all(_is_semver(item) for item in value):
        return False
    versions = cast(Sequence[str], value)
    return all(index == 0 or _compare_semver(versions[index - 1], item) < 0 for index, item in enumerate(versions))


def _valid_relative_fixture(value: object) -> bool:
    return (
        isinstance(value, str)
        and 0 < len(value) <= 240
        and re.fullmatch(r"[A-Za-z0-9._/-]+", value) is not None
        and not value.startswith("/")
        and re.match(r"^[A-Za-z]:", value) is None
        and ".." not in value.split("/")
    )


def domain_compatibility_policy() -> Mapping[str, FrozenJson]:
    return cast(Mapping[str, FrozenJson], _deep_freeze(_POLICY))


def breaking_authority_catalog() -> Mapping[str, FrozenJson]:
    return cast(Mapping[str, FrozenJson], _deep_freeze(_AUTHORITY_CATALOG))


def domain_event_catalog() -> Mapping[str, FrozenJson]:
    return cast(Mapping[str, FrozenJson], _deep_freeze(_EVENT_CATALOG))


def breaking_authority_catalog_errors(value: object) -> tuple[str, ...]:
    catalog = _record(value)
    if (
        catalog is None
        or not _exact_keys(catalog, ("schemaVersion", "documentType", "catalogVersion", "authorities"))
        or catalog["schemaVersion"] != "1.0"
        or catalog["documentType"] != "research-observatory-domain-compatibility-authority-catalog"
        or catalog["catalogVersion"] != "1.0.0"
        or not isinstance(catalog["authorities"], (list, tuple))
        or len(catalog["authorities"]) != 1
    ):
        return ("compatibility-authority-catalog-invalid",)
    candidate = _record(catalog["authorities"][0])
    expected = cast(dict[str, Any], _AUTHORITY_CATALOG["authorities"][0])
    if candidate is None or candidate.get("id") != expected["id"]:
        return ("compatibility-breaking-authority-unknown",)
    candidate_adr = _record(candidate.get("adr"))
    expected_adr = cast(dict[str, Any], expected["adr"])
    if candidate_adr is None or candidate_adr.get("status") != "Accepted":
        return ("compatibility-breaking-authority-status-not-accepted",)
    if (
        candidate_adr.get("decisionScope") != expected_adr["decisionScope"]
        or candidate.get("applicableTask") != expected["applicableTask"]
    ):
        return ("compatibility-breaking-authority-scope-mismatch",)
    candidate_migration = _record(candidate.get("migration"))
    expected_migration = cast(dict[str, Any], expected["migration"])
    if (
        candidate_migration is None
        or candidate_adr.get("sha256") != expected_adr["sha256"]
        or candidate_migration.get("fixtureSha256") != expected_migration["fixtureSha256"]
        or candidate_migration.get("compatibilityTestSha256") != expected_migration["compatibilityTestSha256"]
    ):
        return ("compatibility-breaking-authority-evidence-mismatch",)
    if candidate != expected:
        return ("compatibility-breaking-authority-mismatch",)
    return ()


def contract_releases() -> tuple[Mapping[str, FrozenJson], Mapping[str, FrozenJson]]:
    return (
        cast(Mapping[str, FrozenJson], _deep_freeze(_PRIOR_RELEASE)),
        cast(Mapping[str, FrozenJson], _deep_freeze(_CURRENT_RELEASE)),
    )


def read_compatibility(version: object) -> Mapping[str, FrozenJson]:
    if version == _CURRENT_RELEASE["contractVersion"]:
        value = {
            "mode": "native",
            "contractVersion": version,
            "bridgeId": None,
            "diagnosticCode": "compatibility-read-native",
        }
    elif version == _PRIOR_RELEASE["contractVersion"]:
        value = {
            "mode": "bridge-required",
            "contractVersion": version,
            "bridgeId": "legacy-project-uuidv4-to-canonical-uuidv7",
            "diagnosticCode": "compatibility-read-bridge-required",
        }
    else:
        value = {
            "mode": "unsupported",
            "contractVersion": None,
            "bridgeId": None,
            "diagnosticCode": "compatibility-read-unsupported",
        }
    return cast(Mapping[str, FrozenJson], _deep_freeze(value))


def _basic_proposal(value: object) -> Mapping[str, Any] | None:
    proposal = _record(value)
    keys = (
        "schemaVersion",
        "documentType",
        "fromVersion",
        "toVersion",
        "changeKind",
        "artifactId",
        "adrId",
        "authorityId",
        "migration",
        "deprecation",
    )
    if proposal is None or not _exact_keys(proposal, keys):
        return None
    if (
        proposal["schemaVersion"] != "1.0"
        or proposal["documentType"] != "research-observatory-domain-change-proposal"
        or not _is_semver(proposal["fromVersion"])
        or not _is_semver(proposal["toVersion"])
    ):
        return None
    from_version = cast(str, proposal["fromVersion"])
    to_version = cast(str, proposal["toVersion"])
    if _compare_semver(from_version, to_version) >= 0 or proposal["changeKind"] not in _CHANGE_KINDS:
        return None
    artifact_id = proposal["artifactId"]
    if not isinstance(artifact_id, str) or len(artifact_id) > 128 or _PORTABLE_ID.fullmatch(artifact_id) is None:
        return None
    adr_id = proposal["adrId"]
    if adr_id is not None and (not isinstance(adr_id, str) or _ADR_ID.fullmatch(adr_id) is None):
        return None
    authority_id = proposal["authorityId"]
    if authority_id is not None and (not isinstance(authority_id, str) or _PORTABLE_ID.fullmatch(authority_id) is None):
        return None
    return proposal


def _valid_migration(value: object, from_version: str, to_version: str) -> str | None:
    migration = _record(value)
    keys = ("id", "fromVersion", "toVersion", "strategy", "sourceRetention", "testFixture")
    if migration is None or not _exact_keys(migration, keys):
        return "compatibility-breaking-migration-required"
    migration_id = migration["id"]
    if (
        not isinstance(migration_id, str)
        or _PORTABLE_ID.fullmatch(migration_id) is None
        or migration["strategy"] not in ("reader-bridge", "verified-copy-on-write")
        or migration["sourceRetention"] != "preserved"
        or not _valid_relative_fixture(migration["testFixture"])
    ):
        return "compatibility-breaking-migration-required"
    if migration["fromVersion"] != from_version or migration["toVersion"] != to_version:
        return "compatibility-migration-version-mismatch"
    return None


def _valid_deprecation(value: object, to_version: str) -> str | None:
    deprecation = _record(value)
    if deprecation is None or not _exact_keys(deprecation, ("since", "removalNotBefore", "replacement")):
        return "compatibility-deprecation-window-required"
    removal = deprecation["removalNotBefore"]
    replacement = deprecation["replacement"]
    if (
        deprecation["since"] != to_version
        or not _is_semver(removal)
        or _compare_semver(to_version, cast(str, removal)) >= 0
        or not isinstance(replacement, str)
        or _PORTABLE_ID.fullmatch(replacement) is None
    ):
        return "compatibility-deprecation-window-invalid"
    return None


def assess_domain_change(value: object) -> Mapping[str, FrozenJson]:
    proposal = _basic_proposal(value)
    if proposal is None:
        return cast(
            Mapping[str, FrozenJson],
            _deep_freeze(
                {
                    "classification": None,
                    "allowed": False,
                    "errors": ["compatibility-change-proposal-invalid"],
                    "diagnosticCode": "compatibility-change-denied",
                }
            ),
        )
    rules = cast(list[dict[str, Any]], _POLICY["changeRules"])
    rule = next(item for item in rules if item["changeKind"] == proposal["changeKind"])
    classification = cast(str, rule["classification"])
    errors: list[str] = []
    from_version = cast(str, proposal["fromVersion"])
    to_version = cast(str, proposal["toVersion"])
    from_major = _semver_parts(from_version)[0]
    to_major = _semver_parts(to_version)[0]
    if classification == "additive":
        if from_major != to_major:
            errors.append("compatibility-additive-major-change")
        if (
            proposal["adrId"] is not None
            or proposal["authorityId"] is not None
            or proposal["migration"] is not None
            or proposal["deprecation"] is not None
        ):
            errors.append("compatibility-additive-unexpected-authority")
    elif classification == "deprecation":
        if from_major != to_major:
            errors.append("compatibility-deprecation-major-change")
        error = _valid_deprecation(proposal["deprecation"], to_version)
        if error is not None:
            errors.append(error)
        if proposal["adrId"] is not None or proposal["authorityId"] is not None or proposal["migration"] is not None:
            errors.append("compatibility-deprecation-unexpected-authority")
    else:
        if to_major <= from_major:
            errors.append("compatibility-breaking-major-required")
        adr_id = proposal["adrId"]
        if not isinstance(adr_id, str) or _ADR_ID.fullmatch(adr_id) is None:
            errors.append("compatibility-breaking-adr-required")
        error = _valid_migration(proposal["migration"], from_version, to_version)
        if error is not None:
            errors.append(error)
        authority_id = proposal["authorityId"]
        authorities = cast(list[dict[str, Any]], _AUTHORITY_CATALOG["authorities"])
        authority = next((item for item in authorities if item["id"] == authority_id), None)
        if authority_id is None:
            errors.append("compatibility-breaking-authority-required")
        elif authority is None:
            errors.append("compatibility-breaking-authority-unknown")
        else:
            adr = cast(dict[str, Any], authority["adr"])
            migration = cast(dict[str, Any], authority["migration"])
            proposed_migration = _record(proposal["migration"])
            if (
                authority["changeKind"] != proposal["changeKind"]
                or authority["fromVersion"] != from_version
                or authority["toVersion"] != to_version
                or adr["id"] != proposal["adrId"]
                or proposed_migration is None
                or migration["id"] != proposed_migration.get("id")
                or migration["strategy"] != proposed_migration.get("strategy")
                or migration["sourceRetention"] != proposed_migration.get("sourceRetention")
                or migration["fixturePath"] != proposed_migration.get("testFixture")
            ):
                errors.append("compatibility-breaking-authority-mismatch")
        if proposal["deprecation"] is not None:
            errors.append("compatibility-breaking-unexpected-deprecation")
    return cast(
        Mapping[str, FrozenJson],
        _deep_freeze(
            {
                "classification": classification,
                "allowed": not errors,
                "errors": errors,
                "diagnosticCode": "compatibility-change-accepted" if not errors else "compatibility-change-denied",
            }
        ),
    )


def _audit_event_denial(
    reason_code: str,
    publish_audit: Callable[[Mapping[str, FrozenJson]], None],
) -> Mapping[str, FrozenJson]:
    fact = cast(
        Mapping[str, FrozenJson],
        _deep_freeze(
            {
                "schemaVersion": "1.0",
                "documentType": "research-observatory-domain-compatibility-audit",
                "reasonCode": reason_code,
                "policyVersion": "1.0.0",
                "eventCatalogSha256": f"sha256:{DOMAIN_EVENT_CATALOG_SHA256}",
            }
        ),
    )
    try:
        if not callable(publish_audit):
            raise TypeError("publisher missing")
        publish_audit(fact)
    except Exception as error:
        raise DomainCompatibilityProblem(("compatibility-audit-publication-failed",)) from error
    return cast(
        Mapping[str, FrozenJson],
        _deep_freeze(
            {
                "allowed": False,
                "errors": [reason_code],
                "auditFact": fact,
                "diagnosticCode": "compatibility-event-denied",
            }
        ),
    )


def assess_domain_event(
    value: object,
    publish_audit: Callable[[Mapping[str, FrozenJson]], None],
) -> Mapping[str, FrozenJson]:
    envelope = _record(value)
    if (
        envelope is None
        or not _exact_keys(envelope, ("schemaVersion", "documentType", "eventType", "eventVersion", "payload"))
        or envelope["schemaVersion"] != "1.0"
        or envelope["documentType"] != "research-observatory-domain-event-envelope"
        or not isinstance(envelope["eventType"], str)
        or _PORTABLE_ID.fullmatch(envelope["eventType"]) is None
        or not _is_semver(envelope["eventVersion"])
        or _record(envelope["payload"]) is None
    ):
        return cast(
            Mapping[str, FrozenJson],
            _deep_freeze(
                {
                    "allowed": False,
                    "errors": ["compatibility-event-envelope-invalid"],
                    "auditFact": None,
                    "diagnosticCode": "compatibility-event-denied",
                }
            ),
        )
    events = cast(list[dict[str, Any]], _EVENT_CATALOG["events"])
    if envelope["eventVersion"] not in {item["eventVersion"] for item in events}:
        return _audit_event_denial("compatibility-event-version-unsupported", publish_audit)
    event = next(
        (
            item
            for item in events
            if item["eventType"] == envelope["eventType"] and item["eventVersion"] == envelope["eventVersion"]
        ),
        None,
    )
    if event is None:
        return _audit_event_denial("compatibility-unknown-event", publish_audit)
    payload = cast(Mapping[str, Any], envelope["payload"])
    allowed = cast(list[str], event["payloadAllowedFields"])
    required = cast(list[str], event["payloadRequiredFields"])
    if any(key not in allowed for key in payload):
        return cast(
            Mapping[str, FrozenJson],
            _deep_freeze(
                {
                    "allowed": False,
                    "errors": ["compatibility-event-payload-unknown-field"],
                    "auditFact": None,
                    "diagnosticCode": "compatibility-event-denied",
                }
            ),
        )
    if (
        not all(key in payload for key in required)
        or payload.get("schemaVersion") != "1.0"
        or payload.get("documentType") != event["payloadDocumentType"]
    ):
        return cast(
            Mapping[str, FrozenJson],
            _deep_freeze(
                {
                    "allowed": False,
                    "errors": ["compatibility-event-payload-invalid"],
                    "auditFact": None,
                    "diagnosticCode": "compatibility-event-denied",
                }
            ),
        )
    return cast(
        Mapping[str, FrozenJson],
        _deep_freeze(
            {"allowed": True, "errors": [], "auditFact": None, "diagnosticCode": "compatibility-event-accepted"}
        ),
    )


def _valid_advertisement(value: object) -> bool:
    item = _record(value)
    keys = (
        "schemaVersion",
        "documentType",
        "role",
        "componentVersion",
        "contractFamily",
        "supportedContractVersions",
        "supportedEventVersions",
        "schemaSetId",
    )
    if item is None or not _exact_keys(item, keys):
        return False
    schema_set_id = item["schemaSetId"]
    return (
        item["schemaVersion"] == "1.0"
        and item["documentType"] == "research-observatory-domain-compatibility-advertisement"
        and item["role"] in _ROLES
        and _is_semver(item["componentVersion"])
        and item["contractFamily"] == "research-observatory-domain"
        and _ordered_versions(item["supportedContractVersions"])
        and _ordered_versions(item["supportedEventVersions"])
        and isinstance(schema_set_id, str)
        and _SHA256_ID.fullmatch(schema_set_id) is not None
    )


def _common_highest(items: Sequence[Mapping[str, Any]], key: str) -> str | None:
    first = cast(Sequence[str], items[0][key])
    common = [version for version in first if all(version in cast(Sequence[str], item[key]) for item in items)]
    return max(common, key=_semver_parts) if common else None


def domain_compatibility_negotiation_errors(value: object) -> tuple[str, ...]:
    if (
        not isinstance(value, (list, tuple))
        or not 2 <= len(value) <= 3
        or not all(_valid_advertisement(item) for item in value)
    ):
        return ("compatibility-advertisement-invalid",)
    items = cast(Sequence[Mapping[str, Any]], value)
    roles = [cast(str, item["role"]) for item in items]
    if len(set(roles)) != len(roles):
        return ("compatibility-role-duplicate",)
    if "desktop" not in roles or "sidecar" not in roles:
        return ("compatibility-required-role-missing",)
    if len({item["contractFamily"] for item in items}) != 1:
        return ("compatibility-family-mismatch",)
    if len({item["schemaSetId"] for item in items}) != 1:
        return ("compatibility-schema-set-mismatch",)
    if _common_highest(items, "supportedContractVersions") is None:
        return ("compatibility-contract-version-no-overlap",)
    if _common_highest(items, "supportedEventVersions") is None:
        return ("compatibility-event-version-no-overlap",)
    return ()


def negotiate_domain_compatibility(value: object) -> Mapping[str, FrozenJson]:
    errors = domain_compatibility_negotiation_errors(value)
    if errors:
        raise DomainCompatibilityProblem(errors)
    items = cast(Sequence[Mapping[str, Any]], value)
    contract_version = _common_highest(items, "supportedContractVersions")
    event_version = _common_highest(items, "supportedEventVersions")
    if contract_version is None or event_version is None:
        raise DomainCompatibilityProblem(("compatibility-denied",))
    roles = tuple(role for role in _ROLES if any(item["role"] == role for item in items))
    result = {
        "schemaVersion": "1.0",
        "documentType": "research-observatory-domain-compatibility-negotiation",
        "contractVersion": contract_version,
        "eventVersion": event_version,
        "schemaSetId": items[0]["schemaSetId"],
        "roles": roles,
        "diagnosticCode": "compatibility-negotiated",
    }
    return cast(Mapping[str, FrozenJson], _deep_freeze(result))
