# Generated by packages/contracts/domain/generate-lifecycle.mjs. Do not edit by hand.
# Sources: domain-lifecycle.schema.json and domain-lifecycle.v1.json
from __future__ import annotations

import json
import re
from collections.abc import Callable, Mapping
from datetime import UTC, datetime
from types import MappingProxyType
from typing import Literal, cast

from .domain_contracts import is_uuid_v7

type LifecycleSubjectKind = Literal[
    "project",
    "corpus-item",
    "document",
    "evidence-record",
    "decision",
    "task",
    "dossier",
    "export",
]
type LifecycleSnapshot = Mapping[str, object]
type LifecycleCommand = Mapping[str, object]
type LifecycleTransition = Mapping[str, object]
type DomainLifecycleProfile = Mapping[str, object]

DOMAIN_LIFECYCLE_SCHEMA_SHA256 = "77d82e9fe47c51c7b4bc70c38c203497a0323081a00eb0a0ac899c5849bcb3a3"
DOMAIN_LIFECYCLE_PROFILE_SHA256 = "99386404ed393d385f223680a2dbafba10c995eadfc1e0c4d912e180322c5125"
_PROFILE_SOURCE: dict[str, object] = json.loads(r"""{
  "schemaVersion": "1.0",
  "documentType": "research-observatory-domain-lifecycle-profile",
  "profileVersion": "1.0.0",
  "subjects": [
    {
      "subjectKind": "project",
      "initialState": "active",
      "states": [
        {
          "id": "active",
          "terminal": false,
          "description": "The project accepts governed work."
        },
        {
          "id": "archived",
          "terminal": false,
          "description": "The project is retained read-only until explicitly reopened."
        },
        {
          "id": "deleted",
          "terminal": true,
          "description": "The project identity records an irreversible confirmed deletion."
        }
      ],
      "transitions": [
        {
          "command": "archive",
          "from": "active",
          "to": "archived",
          "kind": "normal"
        },
        {
          "command": "reopen",
          "from": "archived",
          "to": "active",
          "kind": "reopen"
        },
        {
          "command": "delete",
          "from": "active",
          "to": "deleted",
          "kind": "normal"
        },
        {
          "command": "delete",
          "from": "archived",
          "to": "deleted",
          "kind": "normal"
        }
      ]
    },
    {
      "subjectKind": "corpus-item",
      "initialState": "candidate",
      "states": [
        {
          "id": "candidate",
          "terminal": false,
          "description": "The item awaits an inclusion judgment."
        },
        {
          "id": "included",
          "terminal": false,
          "description": "The item is included under the current corpus criteria."
        },
        {
          "id": "excluded",
          "terminal": false,
          "description": "The item is excluded under a recorded reason."
        },
        {
          "id": "withdrawn",
          "terminal": true,
          "description": "The item is retained historically but cannot re-enter this corpus identity."
        }
      ],
      "transitions": [
        {
          "command": "include",
          "from": "candidate",
          "to": "included",
          "kind": "normal"
        },
        {
          "command": "exclude",
          "from": "candidate",
          "to": "excluded",
          "kind": "normal"
        },
        {
          "command": "reconsider",
          "from": "included",
          "to": "candidate",
          "kind": "reopen"
        },
        {
          "command": "reconsider",
          "from": "excluded",
          "to": "candidate",
          "kind": "reopen"
        },
        {
          "command": "withdraw",
          "from": "candidate",
          "to": "withdrawn",
          "kind": "normal"
        },
        {
          "command": "withdraw",
          "from": "included",
          "to": "withdrawn",
          "kind": "normal"
        },
        {
          "command": "withdraw",
          "from": "excluded",
          "to": "withdrawn",
          "kind": "normal"
        }
      ]
    },
    {
      "subjectKind": "document",
      "initialState": "registered",
      "states": [
        {
          "id": "registered",
          "terminal": false,
          "description": "Document identity exists but content availability is not yet established."
        },
        {
          "id": "available",
          "terminal": false,
          "description": "Verified content is available under the current rights decision."
        },
        {
          "id": "unavailable",
          "terminal": false,
          "description": "Content is currently unavailable without erasing its identity or history."
        },
        {
          "id": "retired",
          "terminal": true,
          "description": "The document identity is retained but accepts no further lifecycle transitions."
        }
      ],
      "transitions": [
        {
          "command": "make-available",
          "from": "registered",
          "to": "available",
          "kind": "normal"
        },
        {
          "command": "make-available",
          "from": "unavailable",
          "to": "available",
          "kind": "reopen"
        },
        {
          "command": "mark-unavailable",
          "from": "registered",
          "to": "unavailable",
          "kind": "normal"
        },
        {
          "command": "mark-unavailable",
          "from": "available",
          "to": "unavailable",
          "kind": "normal"
        },
        {
          "command": "retire",
          "from": "registered",
          "to": "retired",
          "kind": "normal"
        },
        {
          "command": "retire",
          "from": "available",
          "to": "retired",
          "kind": "normal"
        },
        {
          "command": "retire",
          "from": "unavailable",
          "to": "retired",
          "kind": "normal"
        }
      ]
    },
    {
      "subjectKind": "evidence-record",
      "initialState": "proposed",
      "states": [
        {
          "id": "proposed",
          "terminal": false,
          "description": "The evidence record awaits a researcher judgment."
        },
        {
          "id": "accepted",
          "terminal": false,
          "description": "The record is accepted for its declared use and scope."
        },
        {
          "id": "disputed",
          "terminal": false,
          "description": "Material disagreement is recorded without forcing resolution."
        },
        {
          "id": "rejected",
          "terminal": true,
          "description": "The proposed revision is rejected but may be explicitly reopened."
        },
        {
          "id": "superseded",
          "terminal": true,
          "description": "A later immutable record has replaced this record for active use."
        }
      ],
      "transitions": [
        {
          "command": "accept",
          "from": "proposed",
          "to": "accepted",
          "kind": "normal"
        },
        {
          "command": "dispute",
          "from": "proposed",
          "to": "disputed",
          "kind": "normal"
        },
        {
          "command": "reject",
          "from": "proposed",
          "to": "rejected",
          "kind": "normal"
        },
        {
          "command": "dispute",
          "from": "accepted",
          "to": "disputed",
          "kind": "normal"
        },
        {
          "command": "accept",
          "from": "disputed",
          "to": "accepted",
          "kind": "normal"
        },
        {
          "command": "reject",
          "from": "disputed",
          "to": "rejected",
          "kind": "normal"
        },
        {
          "command": "supersede",
          "from": "accepted",
          "to": "superseded",
          "kind": "normal"
        },
        {
          "command": "supersede",
          "from": "disputed",
          "to": "superseded",
          "kind": "normal"
        },
        {
          "command": "reopen",
          "from": "rejected",
          "to": "proposed",
          "kind": "reopen"
        }
      ]
    },
    {
      "subjectKind": "decision",
      "initialState": "proposed",
      "states": [
        {
          "id": "proposed",
          "terminal": false,
          "description": "A decision proposal awaits authorized judgment."
        },
        {
          "id": "accepted",
          "terminal": false,
          "description": "The proposal is the current accepted decision."
        },
        {
          "id": "rejected",
          "terminal": true,
          "description": "The proposal is rejected but may be explicitly reopened."
        },
        {
          "id": "superseded",
          "terminal": true,
          "description": "A later accepted decision has replaced this one."
        }
      ],
      "transitions": [
        {
          "command": "accept",
          "from": "proposed",
          "to": "accepted",
          "kind": "normal"
        },
        {
          "command": "reject",
          "from": "proposed",
          "to": "rejected",
          "kind": "normal"
        },
        {
          "command": "supersede",
          "from": "accepted",
          "to": "superseded",
          "kind": "normal"
        },
        {
          "command": "reopen",
          "from": "rejected",
          "to": "proposed",
          "kind": "reopen"
        }
      ]
    },
    {
      "subjectKind": "task",
      "initialState": "pending",
      "states": [
        {
          "id": "pending",
          "terminal": false,
          "description": "The task exists but its dependencies are not yet satisfied."
        },
        {
          "id": "ready",
          "terminal": false,
          "description": "The task is dependency-eligible for execution."
        },
        {
          "id": "in-progress",
          "terminal": false,
          "description": "An authorized actor is executing the task."
        },
        {
          "id": "blocked",
          "terminal": false,
          "description": "A recorded condition currently prevents execution."
        },
        {
          "id": "completed",
          "terminal": true,
          "description": "The task met its acceptance conditions but may be explicitly reopened."
        },
        {
          "id": "cancelled",
          "terminal": true,
          "description": "The task was cancelled but may be explicitly reopened when authority permits."
        }
      ],
      "transitions": [
        {
          "command": "make-ready",
          "from": "pending",
          "to": "ready",
          "kind": "normal"
        },
        {
          "command": "start",
          "from": "ready",
          "to": "in-progress",
          "kind": "normal"
        },
        {
          "command": "block",
          "from": "ready",
          "to": "blocked",
          "kind": "normal"
        },
        {
          "command": "block",
          "from": "in-progress",
          "to": "blocked",
          "kind": "normal"
        },
        {
          "command": "resume",
          "from": "blocked",
          "to": "ready",
          "kind": "reopen"
        },
        {
          "command": "complete",
          "from": "in-progress",
          "to": "completed",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "pending",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "ready",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "in-progress",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "blocked",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "reopen",
          "from": "completed",
          "to": "ready",
          "kind": "reopen"
        },
        {
          "command": "reopen",
          "from": "cancelled",
          "to": "ready",
          "kind": "reopen"
        }
      ]
    },
    {
      "subjectKind": "dossier",
      "initialState": "draft",
      "states": [
        {
          "id": "draft",
          "terminal": false,
          "description": "The dossier is mutable working material."
        },
        {
          "id": "in-review",
          "terminal": false,
          "description": "The dossier is frozen for an authorized review."
        },
        {
          "id": "changes-requested",
          "terminal": false,
          "description": "The review returned bounded required changes."
        },
        {
          "id": "approved",
          "terminal": false,
          "description": "The dossier is the current approved revision."
        },
        {
          "id": "superseded",
          "terminal": true,
          "description": "A later approved dossier revision has replaced this one."
        }
      ],
      "transitions": [
        {
          "command": "submit",
          "from": "draft",
          "to": "in-review",
          "kind": "normal"
        },
        {
          "command": "request-changes",
          "from": "in-review",
          "to": "changes-requested",
          "kind": "normal"
        },
        {
          "command": "revise",
          "from": "changes-requested",
          "to": "draft",
          "kind": "reopen"
        },
        {
          "command": "approve",
          "from": "in-review",
          "to": "approved",
          "kind": "normal"
        },
        {
          "command": "reopen",
          "from": "approved",
          "to": "draft",
          "kind": "reopen"
        },
        {
          "command": "supersede",
          "from": "approved",
          "to": "superseded",
          "kind": "normal"
        }
      ]
    },
    {
      "subjectKind": "export",
      "initialState": "requested",
      "states": [
        {
          "id": "requested",
          "terminal": false,
          "description": "An authorized export request awaits execution."
        },
        {
          "id": "preparing",
          "terminal": false,
          "description": "The bounded export is being assembled and verified."
        },
        {
          "id": "ready",
          "terminal": false,
          "description": "A verified export is available under its retention policy."
        },
        {
          "id": "failed",
          "terminal": true,
          "description": "The attempt failed without publication and may be retried explicitly."
        },
        {
          "id": "cancelled",
          "terminal": true,
          "description": "The attempt was cancelled without publication and may be reopened explicitly."
        },
        {
          "id": "expired",
          "terminal": true,
          "description": "The export authority and retained package have expired."
        }
      ],
      "transitions": [
        {
          "command": "begin",
          "from": "requested",
          "to": "preparing",
          "kind": "normal"
        },
        {
          "command": "publish",
          "from": "preparing",
          "to": "ready",
          "kind": "normal"
        },
        {
          "command": "fail",
          "from": "preparing",
          "to": "failed",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "requested",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "cancel",
          "from": "preparing",
          "to": "cancelled",
          "kind": "normal"
        },
        {
          "command": "expire",
          "from": "ready",
          "to": "expired",
          "kind": "normal"
        },
        {
          "command": "retry",
          "from": "failed",
          "to": "requested",
          "kind": "reopen"
        },
        {
          "command": "reopen",
          "from": "cancelled",
          "to": "requested",
          "kind": "reopen"
        }
      ]
    }
  ]
}""")
_PORTABLE_ID = re.compile(r"^[a-z][a-z0-9]*(?:[.:_-][a-z0-9]+){0,7}$")
_NAME = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+){0,7}$")
_IDEMPOTENCY_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$")
_UTC = re.compile(r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,3}))?Z$")
_ACTOR_KINDS = frozenset({"human", "system", "agent"})
_SAFE_REVISION_MAX = 9_007_199_254_740_991


def _record(value: object) -> Mapping[str, object] | None:
    return cast(Mapping[str, object], value) if isinstance(value, Mapping) else None


def _owned_frozen(value: object) -> object:
    if isinstance(value, Mapping):
        return MappingProxyType({str(key): _owned_frozen(item) for key, item in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_owned_frozen(item) for item in value)
    return value


_PROFILE = cast(DomainLifecycleProfile, _owned_frozen(_PROFILE_SOURCE))
_SUBJECTS = {
    cast(str, subject["subjectKind"]): subject
    for subject in cast(tuple[Mapping[str, object], ...], _PROFILE["subjects"])
}


def _exact_keys(value: Mapping[str, object], expected: frozenset[str]) -> bool:
    return frozenset(value) == expected


def _safe_revision(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and 0 <= value <= _SAFE_REVISION_MAX


def _canonical_utc(value: object) -> bool:
    if not isinstance(value, str):
        return False
    match = _UTC.fullmatch(value)
    if match is None:
        return False
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(UTC)
    except ValueError:
        return False
    expected = f"{match.group(1)}.{(match.group(2) or '').ljust(3, '0')}Z"
    return parsed.isoformat(timespec="milliseconds").replace("+00:00", "Z") == expected


def _valid_snapshot(value: object) -> bool:
    item = _record(value)
    if item is None or not _exact_keys(
        item,
        frozenset(
            {"aggregateId", "documentType", "profileVersion", "revision", "schemaVersion", "state", "subjectKind"}
        ),
    ):
        return False
    return (
        item["schemaVersion"] == "1.0"
        and item["documentType"] == "research-observatory-domain-lifecycle-snapshot"
        and item["profileVersion"] == _PROFILE["profileVersion"]
        and item["subjectKind"] in _SUBJECTS
        and is_uuid_v7(item["aggregateId"])
        and isinstance(item["state"], str)
        and len(item["state"]) <= 80
        and _NAME.fullmatch(item["state"]) is not None
        and _safe_revision(item["revision"])
    )


def _valid_command(value: object) -> bool:
    item = _record(value)
    if item is None or not _exact_keys(
        item,
        frozenset(
            {
                "actor",
                "aggregateId",
                "command",
                "documentType",
                "expectedRevision",
                "idempotencyKey",
                "occurredAt",
                "profileVersion",
                "reason",
                "schemaVersion",
                "subjectKind",
            }
        ),
    ):
        return False
    actor = _record(item["actor"])
    reason = _record(item["reason"])
    return (
        item["schemaVersion"] == "1.0"
        and item["documentType"] == "research-observatory-domain-lifecycle-command"
        and item["profileVersion"] == _PROFILE["profileVersion"]
        and item["subjectKind"] in _SUBJECTS
        and is_uuid_v7(item["aggregateId"])
        and _safe_revision(item["expectedRevision"])
        and isinstance(item["command"], str)
        and len(item["command"]) <= 80
        and _NAME.fullmatch(item["command"]) is not None
        and actor is not None
        and _exact_keys(actor, frozenset({"kind", "id"}))
        and actor["kind"] in _ACTOR_KINDS
        and isinstance(actor["id"], str)
        and len(actor["id"]) <= 128
        and _PORTABLE_ID.fullmatch(actor["id"]) is not None
        and reason is not None
        and _exact_keys(reason, frozenset({"code", "detail"}))
        and isinstance(reason["code"], str)
        and len(reason["code"]) <= 80
        and _NAME.fullmatch(reason["code"]) is not None
        and isinstance(reason["detail"], str)
        and 1 <= len(reason["detail"]) <= 500
        and re.search(r"[\x00-\x1f\x7f]", reason["detail"]) is None
        and _canonical_utc(item["occurredAt"])
        and isinstance(item["idempotencyKey"], str)
        and _IDEMPOTENCY_KEY.fullmatch(item["idempotencyKey"]) is not None
    )


def domain_lifecycle_profile() -> DomainLifecycleProfile:
    return _PROFILE


def lifecycle_transition_errors(current: object, command: object) -> tuple[str, ...]:
    errors: list[str] = []
    if not _valid_snapshot(current):
        errors.append("lifecycle-current-invalid")
    if not _valid_command(command):
        errors.append("lifecycle-command-invalid")
    if errors:
        return tuple(errors)
    snapshot = cast(Mapping[str, object], current)
    request = cast(Mapping[str, object], command)
    if snapshot["subjectKind"] != request["subjectKind"] or snapshot["aggregateId"] != request["aggregateId"]:
        errors.append("lifecycle-subject-mismatch")
    if snapshot["revision"] != request["expectedRevision"]:
        errors.append("lifecycle-revision-conflict")
    if snapshot["revision"] == _SAFE_REVISION_MAX:
        errors.append("lifecycle-revision-exhausted")
    subject = _SUBJECTS[cast(str, snapshot["subjectKind"])]
    states = cast(tuple[Mapping[str, object], ...], subject["states"])
    transitions = cast(tuple[Mapping[str, object], ...], subject["transitions"])
    if not any(state["id"] == snapshot["state"] for state in states):
        errors.append("lifecycle-state-unknown")
    if not any(rule["from"] == snapshot["state"] and rule["command"] == request["command"] for rule in transitions):
        errors.append("lifecycle-command-not-allowed")
    return tuple(errors)


class DomainLifecycleProblem(ValueError):
    def __init__(self, codes: tuple[str, ...]) -> None:
        self.code = codes[0]
        self.codes = codes
        super().__init__(self.code)


def prepare_lifecycle_transition(current: object, command: object) -> LifecycleTransition:
    errors = lifecycle_transition_errors(current, command)
    if errors:
        raise DomainLifecycleProblem(errors)
    snapshot = cast(Mapping[str, object], current)
    request = cast(Mapping[str, object], command)
    subject = _SUBJECTS[cast(str, snapshot["subjectKind"])]
    transitions = cast(tuple[Mapping[str, object], ...], subject["transitions"])
    rule = next(
        candidate
        for candidate in transitions
        if candidate["from"] == snapshot["state"] and candidate["command"] == request["command"]
    )
    actor = cast(Mapping[str, object], request["actor"])
    reason = cast(Mapping[str, object], request["reason"])
    transition = {
        "schemaVersion": "1.0",
        "documentType": "research-observatory-domain-lifecycle-transition",
        "profileVersion": _PROFILE["profileVersion"],
        "subjectKind": snapshot["subjectKind"],
        "aggregateId": snapshot["aggregateId"],
        "fromState": snapshot["state"],
        "toState": rule["to"],
        "command": rule["command"],
        "transitionKind": rule["kind"],
        "priorRevision": snapshot["revision"],
        "revision": cast(int, snapshot["revision"]) + 1,
        "actor": {"kind": actor["kind"], "id": actor["id"]},
        "reason": {"code": reason["code"], "detail": reason["detail"]},
        "occurredAt": request["occurredAt"],
        "idempotencyKey": request["idempotencyKey"],
    }
    return cast(LifecycleTransition, _owned_frozen(transition))


def apply_lifecycle_transition(
    current: object,
    command: object,
    persist: Callable[[LifecycleTransition], None],
) -> LifecycleTransition:
    transition = prepare_lifecycle_transition(current, command)
    persist(transition)
    return transition


def _stable_json(value: object) -> str:
    if isinstance(value, Mapping):
        return (
            "{"
            + ",".join(
                json.dumps(str(key), ensure_ascii=False) + ":" + _stable_json(value[key]) for key in sorted(value)
            )
            + "}"
        )
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(_stable_json(item) for item in value) + "]"
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def lifecycle_transition_json(value: LifecycleTransition) -> str:
    return _stable_json(value)
