# Generated by packages/contracts/domain/generate.mjs. Do not edit by hand.
# Source: packages/contracts/domain/domain-core.schema.json
# ruff: noqa: E501 - embedded governed JSON Schema values retain exact readable text
from __future__ import annotations

import json
import math
import re
import secrets
import time
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any, Literal, TypedDict, cast

type AggregateId = str


type RevisionId = str


type RevisionNumber = int


type ContractVersion = str


type UtcInstant = str


type AggregateKind = Literal[
    "project",
    "record",
    "document",
    "evidence",
    "decision",
    "workflow",
    "ontology",
    "graph",
    "opportunity",
    "monitoring-event",
]


type KnowledgeStatus = Literal[
    "observed",
    "extracted",
    "inferred",
    "verified",
    "disputed",
    "adjudicated",
    "stale",
    "unknown",
    "not-reported",
    "not-applicable",
    "ambiguous",
    "unavailable",
]


class SourceAnchor(TypedDict):
    kind: Literal["record-field", "document-element", "page", "table-cell", "figure", "external-identifier"]
    value: str


class SourceReference(TypedDict):
    sourceAggregateId: AggregateId
    sourceRevision: RevisionNumber
    anchor: SourceAnchor
    sourceLabel: str


type AlternativeDisposition = Literal[
    "candidate",
    "disputed",
    "accepted",
    "rejected",
]


class TextAlternative(TypedDict):
    value: str
    disposition: AlternativeDisposition
    sourceReference: SourceReference


class ObservedText(TypedDict):
    observed: str
    normalized: str | None
    alternatives: list[TextAlternative]


class QuantifiedConfidence(TypedDict):
    kind: Literal["quantified"]
    value: float
    basis: str


class QualitativeConfidence(TypedDict):
    kind: Literal["qualitative"]
    value: Literal["low", "moderate", "high", "mixed"]
    basis: str


class UnknownConfidence(TypedDict):
    kind: Literal["unknown"]


class NotApplicableConfidence(TypedDict):
    kind: Literal["not-applicable"]


type Confidence = QuantifiedConfidence | QualitativeConfidence | UnknownConfidence | NotApplicableConfidence


type RightsUse = Literal[
    "view",
    "extract",
    "analyze",
    "model",
    "share",
    "export",
]


class AllowedRights(TypedDict):
    status: Literal["allowed"]
    allowedUses: list[RightsUse]
    deniedUses: list[RightsUse]
    sourceReferences: list[SourceReference]


class DeniedRights(TypedDict):
    status: Literal["denied"]
    allowedUses: list[RightsUse]
    deniedUses: list[RightsUse]
    sourceReferences: list[SourceReference]


class UnknownRights(TypedDict):
    status: Literal["unknown"]
    allowedUses: list[RightsUse]
    deniedUses: list[RightsUse]
    sourceReferences: list[SourceReference]


class NotApplicableRights(TypedDict):
    status: Literal["not-applicable"]
    allowedUses: list[RightsUse]
    deniedUses: list[RightsUse]
    sourceReferences: list[SourceReference]


type RightsDecision = AllowedRights | DeniedRights | UnknownRights | NotApplicableRights


class ExternalIdentifier(TypedDict):
    scheme: Literal["doi", "pmid", "isbn", "issn", "arxiv", "handle", "orcid", "ror", "url", "other"]
    observedValue: PortableIdentifierText
    normalizedValue: PortableIdentifierText | None
    verificationState: Literal["unverified", "verified", "disputed", "invalid"]
    sourceReference: SourceReference


type PortableIdentifierText = str


type WebIdentifierText = str


class CoreAggregate(TypedDict):
    schemaVersion: Literal["1.0"]
    documentType: Literal["research-observatory-core-aggregate"]
    contractVersion: ContractVersion
    aggregateKind: AggregateKind
    aggregateId: AggregateId
    revisionId: RevisionId
    revision: RevisionNumber
    createdAt: UtcInstant
    modifiedAt: UtcInstant
    displayLabel: ObservedText
    status: KnowledgeStatus
    confidence: Confidence
    rights: RightsDecision
    sourceReferences: list[SourceReference]
    externalIdentifiers: list[ExternalIdentifier]


CORE_DOMAIN_SCHEMA_SHA256 = "7fc254970fffd5f32342837e75972144372ee80d2bdd97af2b18096c13ecf23b"
_CORE_DOMAIN_SCHEMA: dict[str, Any] = json.loads(r"""{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://research-observatory.local/contracts/domain/domain-core.schema.json",
  "title": "Research Observatory portable core aggregate",
  "description": "Framework-neutral identity, revision, source, epistemic, confidence, rights, and principal-aggregate envelope contract.",
  "x-research-observatory-semanticRules": [
    {
      "ruleId": "modified-at-not-before-created-at",
      "operator": "instant-not-after",
      "leftPointer": "/createdAt",
      "rightPointer": "/modifiedAt"
    },
    {
      "ruleId": "revision-identity-distinct",
      "operator": "not-equal",
      "leftPointer": "/aggregateId",
      "rightPointer": "/revisionId"
    },
    {
      "ruleId": "rights-allowed-and-denied-disjoint",
      "operator": "set-disjoint",
      "leftPointer": "/rights/allowedUses",
      "rightPointer": "/rights/deniedUses"
    }
  ],
  "$ref": "#/$defs/CoreAggregate",
  "$defs": {
    "AggregateId": {
      "type": "string",
      "description": "Canonical lower-case RFC 9562 UUIDv7.",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?![\\s\\S])"
    },
    "RevisionId": {
      "type": "string",
      "description": "Immutable revision identity represented as canonical lower-case UUIDv7.",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}(?![\\s\\S])"
    },
    "RevisionNumber": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "ContractVersion": {
      "type": "string",
      "pattern": "^(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])(?![\\s\\S])"
    },
    "UtcInstant": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z(?![\\s\\S])"
    },
    "AggregateKind": {
      "type": "string",
      "enum": [
        "project",
        "record",
        "document",
        "evidence",
        "decision",
        "workflow",
        "ontology",
        "graph",
        "opportunity",
        "monitoring-event"
      ]
    },
    "KnowledgeStatus": {
      "type": "string",
      "enum": [
        "observed",
        "extracted",
        "inferred",
        "verified",
        "disputed",
        "adjudicated",
        "stale",
        "unknown",
        "not-reported",
        "not-applicable",
        "ambiguous",
        "unavailable"
      ]
    },
    "SourceAnchor": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value"
      ],
      "properties": {
        "kind": {
          "enum": [
            "record-field",
            "document-element",
            "page",
            "table-cell",
            "figure",
            "external-identifier"
          ]
        },
        "value": {
          "type": "string",
          "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}(?![\\s\\S])"
        }
      }
    },
    "SourceReference": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceAggregateId",
        "sourceRevision",
        "anchor",
        "sourceLabel"
      ],
      "properties": {
        "sourceAggregateId": {
          "$ref": "#/$defs/AggregateId"
        },
        "sourceRevision": {
          "$ref": "#/$defs/RevisionNumber"
        },
        "anchor": {
          "$ref": "#/$defs/SourceAnchor"
        },
        "sourceLabel": {
          "type": "string",
          "minLength": 1,
          "maxLength": 240,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
        }
      }
    },
    "AlternativeDisposition": {
      "type": "string",
      "enum": [
        "candidate",
        "disputed",
        "accepted",
        "rejected"
      ]
    },
    "TextAlternative": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "value",
        "disposition",
        "sourceReference"
      ],
      "properties": {
        "value": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
        },
        "disposition": {
          "$ref": "#/$defs/AlternativeDisposition"
        },
        "sourceReference": {
          "$ref": "#/$defs/SourceReference"
        }
      }
    },
    "ObservedText": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "observed",
        "normalized",
        "alternatives"
      ],
      "properties": {
        "observed": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
        },
        "normalized": {
          "oneOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 4096,
              "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
            },
            {
              "type": "null"
            }
          ]
        },
        "alternatives": {
          "type": "array",
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/TextAlternative"
          }
        }
      }
    },
    "QuantifiedConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value",
        "basis"
      ],
      "properties": {
        "kind": {
          "const": "quantified"
        },
        "value": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "basis": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
        }
      }
    },
    "QualitativeConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value",
        "basis"
      ],
      "properties": {
        "kind": {
          "const": "qualitative"
        },
        "value": {
          "enum": [
            "low",
            "moderate",
            "high",
            "mixed"
          ]
        },
        "basis": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
        }
      }
    },
    "UnknownConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "const": "unknown"
        }
      }
    },
    "NotApplicableConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "const": "not-applicable"
        }
      }
    },
    "Confidence": {
      "oneOf": [
        {
          "$ref": "#/$defs/QuantifiedConfidence"
        },
        {
          "$ref": "#/$defs/QualitativeConfidence"
        },
        {
          "$ref": "#/$defs/UnknownConfidence"
        },
        {
          "$ref": "#/$defs/NotApplicableConfidence"
        }
      ]
    },
    "RightsUse": {
      "type": "string",
      "enum": [
        "view",
        "extract",
        "analyze",
        "model",
        "share",
        "export"
      ]
    },
    "AllowedRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "allowed"
        },
        "allowedUses": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "DeniedRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "denied"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "UnknownRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "unknown"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "NotApplicableRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "not-applicable"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "RightsDecision": {
      "oneOf": [
        {
          "$ref": "#/$defs/AllowedRights"
        },
        {
          "$ref": "#/$defs/DeniedRights"
        },
        {
          "$ref": "#/$defs/UnknownRights"
        },
        {
          "$ref": "#/$defs/NotApplicableRights"
        }
      ]
    },
    "ExternalIdentifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "scheme",
        "observedValue",
        "normalizedValue",
        "verificationState",
        "sourceReference"
      ],
      "properties": {
        "scheme": {
          "enum": [
            "doi",
            "pmid",
            "isbn",
            "issn",
            "arxiv",
            "handle",
            "orcid",
            "ror",
            "url",
            "other"
          ]
        },
        "observedValue": {
          "$ref": "#/$defs/PortableIdentifierText"
        },
        "normalizedValue": {
          "oneOf": [
            {
              "$ref": "#/$defs/PortableIdentifierText"
            },
            {
              "type": "null"
            }
          ]
        },
        "verificationState": {
          "enum": [
            "unverified",
            "verified",
            "disputed",
            "invalid"
          ]
        },
        "sourceReference": {
          "$ref": "#/$defs/SourceReference"
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "scheme": {
                "const": "url"
              }
            },
            "required": [
              "scheme"
            ]
          },
          "then": {
            "properties": {
              "observedValue": {
                "$ref": "#/$defs/WebIdentifierText"
              },
              "normalizedValue": {
                "oneOf": [
                  {
                    "$ref": "#/$defs/WebIdentifierText"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          }
        }
      ]
    },
    "PortableIdentifierText": {
      "type": "string",
      "minLength": 1,
      "maxLength": 512,
      "description": "Portable identifier text that cannot encode a local filesystem location.",
      "pattern": "^(?![A-Za-z]:)(?![\\\\/])(?!~[\\\\/])(?!\\.\\.?[\\\\/])(?![Ff][Ii][Ll][Ee]:)[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
    },
    "WebIdentifierText": {
      "type": "string",
      "minLength": 1,
      "maxLength": 512,
      "description": "Portable HTTP(S) URL identifier; local and file URI forms are forbidden.",
      "pattern": "^[Hh][Tt][Tt][Pp][Ss]?://[^\\u0000-\\u001f\\u007f]+(?![\\s\\S])"
    },
    "CoreAggregate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "schemaVersion",
        "documentType",
        "contractVersion",
        "aggregateKind",
        "aggregateId",
        "revisionId",
        "revision",
        "createdAt",
        "modifiedAt",
        "displayLabel",
        "status",
        "confidence",
        "rights",
        "sourceReferences",
        "externalIdentifiers"
      ],
      "properties": {
        "schemaVersion": {
          "const": "1.0"
        },
        "documentType": {
          "const": "research-observatory-core-aggregate"
        },
        "contractVersion": {
          "$ref": "#/$defs/ContractVersion"
        },
        "aggregateKind": {
          "$ref": "#/$defs/AggregateKind"
        },
        "aggregateId": {
          "$ref": "#/$defs/AggregateId"
        },
        "revisionId": {
          "$ref": "#/$defs/RevisionId"
        },
        "revision": {
          "$ref": "#/$defs/RevisionNumber"
        },
        "createdAt": {
          "$ref": "#/$defs/UtcInstant"
        },
        "modifiedAt": {
          "$ref": "#/$defs/UtcInstant"
        },
        "displayLabel": {
          "$ref": "#/$defs/ObservedText"
        },
        "status": {
          "$ref": "#/$defs/KnowledgeStatus"
        },
        "confidence": {
          "$ref": "#/$defs/Confidence"
        },
        "rights": {
          "$ref": "#/$defs/RightsDecision"
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 256,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        },
        "externalIdentifiers": {
          "type": "array",
          "maxItems": 128,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/ExternalIdentifier"
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "status": {
                "const": "disputed"
              }
            },
            "required": [
              "status"
            ]
          },
          "then": {
            "properties": {
              "displayLabel": {
                "type": "object",
                "properties": {
                  "alternatives": {
                    "type": "array",
                    "contains": {
                      "type": "object",
                      "properties": {
                        "disposition": {
                          "const": "disputed"
                        }
                      },
                      "required": [
                        "disposition"
                      ]
                    },
                    "minContains": 1
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}""")
_UUID_V7 = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
_UTC = re.compile(r"^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,3}))?Z$")
_MAX_SNAPSHOT_COLLECTION_ITEMS = 256


def _record(value: object) -> dict[str, Any] | None:
    return cast(dict[str, Any], value) if isinstance(value, dict) else None


def _deep_equal(left: object, right: object) -> bool:
    return left == right and type(left) is type(right)


def _stable_json(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


class _FrozenDict(dict[str, Any]):
    def _immutable(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("decoded domain snapshot is immutable")

    __setitem__ = _immutable
    __delitem__ = _immutable
    clear = _immutable
    pop = _immutable
    popitem = _immutable  # type: ignore[assignment]
    setdefault = _immutable
    update = _immutable
    __ior__ = _immutable  # type: ignore[assignment]


class _FrozenList(list[Any]):
    def _immutable(self, *_args: object, **_kwargs: object) -> None:
        raise TypeError("decoded domain snapshot is immutable")

    __setitem__ = _immutable
    __delitem__ = _immutable
    append = _immutable
    clear = _immutable
    extend = _immutable
    insert = _immutable
    pop = _immutable
    remove = _immutable
    reverse = _immutable
    sort = _immutable
    __iadd__ = _immutable  # type: ignore[assignment]
    __imul__ = _immutable  # type: ignore[assignment]


def _owned_frozen_json(value: object) -> object:
    if isinstance(value, dict):
        if len(value) > _MAX_SNAPSHOT_COLLECTION_ITEMS:
            raise ValueError("domain snapshot object exceeds bound")
        return _FrozenDict({key: _owned_frozen_json(item) for key, item in value.items()})
    if isinstance(value, list):
        if len(value) > _MAX_SNAPSHOT_COLLECTION_ITEMS:
            raise ValueError("domain snapshot collection exceeds bound")
        return _FrozenList(_owned_frozen_json(item) for item in value)
    return value


def _owned_frozen_snapshot(value: object, node: dict[str, Any]) -> object:
    if "$ref" in node:
        return _owned_frozen_snapshot(value, _resolve_reference(node["$ref"]))
    alternatives = node.get("oneOf") if isinstance(node.get("oneOf"), list) else node.get("anyOf")
    if isinstance(alternatives, list):
        for alternative in alternatives:
            candidate = cast(dict[str, Any], alternative)
            if not _validation_errors(value, candidate, "$"):
                return _owned_frozen_snapshot(value, candidate)
    if node.get("type") == "integer" and isinstance(value, float) and value.is_integer():
        return int(value)
    if node.get("type") == "array" and isinstance(value, list):
        item_schema = cast(dict[str, Any], node.get("items", {}))
        return _FrozenList(_owned_frozen_snapshot(item, item_schema) for item in value)
    if node.get("type") == "object" and isinstance(value, dict):
        properties = cast(dict[str, dict[str, Any]], node.get("properties", {}))
        return _FrozenDict({key: _owned_frozen_snapshot(item, properties.get(key, {})) for key, item in value.items()})
    return value


def _resolve_reference(reference: object) -> dict[str, Any]:
    prefix = "#/$defs/"
    if not isinstance(reference, str) or not reference.startswith(prefix):
        raise ValueError("unsupported domain schema reference")
    return cast(dict[str, Any], _CORE_DOMAIN_SCHEMA["$defs"][reference[len(prefix) :]])


def _canonical_utc(value: str) -> bool:
    match = _UTC.fullmatch(value)
    if match is None:
        return False
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(UTC)
    except ValueError:
        return False
    expected = f"{match.group(1)}.{(match.group(2) or '').ljust(3, '0')}Z"
    return parsed.isoformat(timespec="milliseconds").replace("+00:00", "Z") == expected


def _validation_errors(value: object, node: dict[str, Any], path: str) -> list[str]:
    if "$ref" in node:
        return _validation_errors(value, _resolve_reference(node["$ref"]), path)
    errors: list[str] = []
    if "const" in node and not _deep_equal(value, node["const"]):
        errors.append(f"{path}: const")
    enum = node.get("enum")
    if isinstance(enum, list) and not any(_deep_equal(value, item) for item in enum):
        errors.append(f"{path}: enum")
    alternatives = node.get("oneOf") if isinstance(node.get("oneOf"), list) else node.get("anyOf")
    if isinstance(alternatives, list):
        matches = sum(not _validation_errors(value, cast(dict[str, Any], item), path) for item in alternatives)
        if ("oneOf" in node and matches != 1) or ("anyOf" in node and matches == 0):
            errors.append(f"{path}: alternatives")
    kind = node.get("type")
    if kind == "null" and value is not None:
        errors.append(f"{path}: null")
    if kind == "boolean" and not isinstance(value, bool):
        errors.append(f"{path}: boolean")
    if kind == "integer" and (
        not isinstance(value, (int, float))
        or isinstance(value, bool)
        or not math.isfinite(value)
        or not float(value).is_integer()
        or abs(value) > 9_007_199_254_740_991
    ):
        errors.append(f"{path}: safe integer")
    if kind == "number" and (
        not isinstance(value, (int, float)) or isinstance(value, bool) or not math.isfinite(value)
    ):
        errors.append(f"{path}: finite number")
    if isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value):
        if isinstance(node.get("minimum"), (int, float)) and value < node["minimum"]:
            errors.append(f"{path}: minimum")
        if isinstance(node.get("maximum"), (int, float)) and value > node["maximum"]:
            errors.append(f"{path}: maximum")
    if kind == "string":
        if not isinstance(value, str):
            errors.append(f"{path}: string")
        else:
            if isinstance(node.get("minLength"), int) and len(value) < node["minLength"]:
                errors.append(f"{path}: minLength")
            if isinstance(node.get("maxLength"), int) and len(value) > node["maxLength"]:
                errors.append(f"{path}: maxLength")
            if isinstance(node.get("pattern"), str) and re.search(node["pattern"], value) is None:
                errors.append(f"{path}: pattern")
            if node.get("format") == "date-time" and not _canonical_utc(value):
                errors.append(f"{path}: canonical UTC date-time")
    if kind == "array":
        if not isinstance(value, list):
            errors.append(f"{path}: array")
        else:
            if isinstance(node.get("minItems"), int) and len(value) < node["minItems"]:
                errors.append(f"{path}: minItems")
            if isinstance(node.get("maxItems"), int) and len(value) > node["maxItems"]:
                errors.append(f"{path}: maxItems")
                return errors
            if node.get("uniqueItems") is True and len({_stable_json(item) for item in value}) != len(value):
                errors.append(f"{path}: uniqueItems")
            if isinstance(node.get("items"), dict):
                for index, item in enumerate(value):
                    errors.extend(_validation_errors(item, node["items"], f"{path}/{index}"))
            if isinstance(node.get("contains"), dict):
                matches = sum(not _validation_errors(item, node["contains"], path) for item in value)
                minimum = node.get("minContains", 1)
                if not isinstance(minimum, int) or matches < minimum:
                    errors.append(f"{path}: minContains")
    if kind == "object":
        candidate = _record(value)
        if candidate is None:
            errors.append(f"{path}: object")
        else:
            required = node.get("required", [])
            if isinstance(required, list):
                for key in required:
                    if isinstance(key, str) and key not in candidate:
                        errors.append(f"{path}/{key}: required")
            properties = node.get("properties", {})
            if not isinstance(properties, dict):
                raise ValueError("generated domain schema properties are malformed")
            if node.get("additionalProperties") is False:
                for key in candidate:
                    if key not in properties:
                        errors.append(f"{path}/{key}: additional property")
            for key, property_schema in properties.items():
                if key in candidate:
                    errors.extend(
                        _validation_errors(candidate[key], cast(dict[str, Any], property_schema), f"{path}/{key}")
                    )
    elif isinstance(node.get("properties"), dict):
        candidate = _record(value)
        if candidate is not None:
            for key, property_schema in node["properties"].items():
                if key in candidate:
                    errors.extend(
                        _validation_errors(candidate[key], cast(dict[str, Any], property_schema), f"{path}/{key}")
                    )
    if isinstance(node.get("allOf"), list):
        for item in node["allOf"]:
            errors.extend(_validation_errors(value, cast(dict[str, Any], item), path))
    if (
        isinstance(node.get("if"), dict)
        and not _validation_errors(value, node["if"], path)
        and isinstance(node.get("then"), dict)
    ):
        errors.extend(_validation_errors(value, node["then"], path))
    return errors


def _pointer_value(value: object, pointer: object) -> object:
    if not isinstance(pointer, str) or not pointer.startswith("/"):
        raise ValueError("invalid semantic-rule pointer")
    current = value
    for segment in pointer[1:].split("/"):
        candidate = _record(current)
        if candidate is None or segment not in candidate:
            raise ValueError("semantic-rule pointer is missing")
        current = candidate[segment]
    return current


def _semantic_errors(value: object) -> list[str]:
    errors: list[str] = []
    rules = _CORE_DOMAIN_SCHEMA["x-research-observatory-semanticRules"]
    if not isinstance(rules, list):
        raise ValueError("semantic rules are malformed")
    for raw_rule in rules:
        rule = cast(dict[str, object], raw_rule)
        left = _pointer_value(value, rule["leftPointer"])
        right = _pointer_value(value, rule["rightPointer"])
        valid = False
        if rule["operator"] == "instant-not-after" and isinstance(left, str) and isinstance(right, str):
            valid = datetime.fromisoformat(left.replace("Z", "+00:00")) <= datetime.fromisoformat(
                right.replace("Z", "+00:00")
            )
        if rule["operator"] == "not-equal":
            valid = not _deep_equal(left, right)
        if rule["operator"] == "set-disjoint" and isinstance(left, list) and isinstance(right, list):
            right_values = {_stable_json(item) for item in right}
            valid = all(_stable_json(item) not in right_values for item in left)
        if not valid:
            errors.append(str(rule["ruleId"]))
    return errors


def is_uuid_v7(value: object) -> bool:
    return isinstance(value, str) and _UUID_V7.fullmatch(value) is not None


def new_uuid_v7(
    *,
    timestamp_ms: int | None = None,
    random_source: Callable[[int], bytes] = secrets.token_bytes,
) -> str:
    """Mint a canonical UUIDv7 at the trusted Core boundary using RFC 9562 layout."""

    instant = time.time_ns() // 1_000_000 if timestamp_ms is None else timestamp_ms
    if not isinstance(instant, int) or isinstance(instant, bool) or not 0 <= instant < 2**48:
        raise ValueError("UUIDv7 timestamp must be an unsigned 48-bit Unix millisecond value")
    random = random_source(10)
    if not isinstance(random, bytes) or len(random) != 10:
        raise ValueError("UUIDv7 random source must return exactly 10 bytes")
    value = bytearray(16)
    value[0:6] = instant.to_bytes(6, "big")
    value[6] = 0x70 | (random[0] & 0x0F)
    value[7] = random[1]
    value[8] = 0x80 | (random[2] & 0x3F)
    value[9:16] = random[3:10]
    hexadecimal = value.hex()
    return f"{hexadecimal[:8]}-{hexadecimal[8:12]}-{hexadecimal[12:16]}-{hexadecimal[16:20]}-{hexadecimal[20:]}"


def domain_contract_errors(value: object) -> tuple[str, ...]:
    errors = _validation_errors(value, _CORE_DOMAIN_SCHEMA, "$")
    if errors:
        return tuple(errors)
    try:
        return tuple(_semantic_errors(value))
    except KeyError, TypeError, ValueError:
        return ("semantic-rule-input-invalid",)


def decode_core_aggregate(value: object) -> CoreAggregate | None:
    try:
        owned = _owned_frozen_json(value)
    except ValueError:
        return None
    if domain_contract_errors(owned):
        return None
    return cast(CoreAggregate, _owned_frozen_snapshot(owned, _CORE_DOMAIN_SCHEMA))
