// Generated by packages/contracts/rights/generate.mjs. Do not edit by hand.
// Source: packages/contracts/rights/rights-policy.schema.json

export type BoundedText = string;

export type Confidence = "reported" | "confirmed" | "verified" | "disputed";

export type CopyLocation = "local-project-object" | "local-source" | "provider-hosted" | "collaboration-copy";

export type DestinationKind = "local-project" | "local-export" | "remote-model" | "external-export" | "collaboration";

export type Digest = string;

export type Identity = string;

export type PermissionValue = "permitted" | "denied" | "unknown";

export type ProjectIdentity = string;

export type ProvenanceBasis = "source-observation" | "researcher-confirmed" | "verified-entitlement";

export type ResourceClass = "metadata" | "full-text" | "derived-text" | "embedding";

export type RightsAction = "store" | "inspect" | "index" | "derive" | "model-use" | "quote" | "export" | "share";

export interface RightsPermission {
  readonly assertionId: Identity;
  readonly subject: RightsSubject;
  readonly use: RightsUse;
  readonly value: PermissionValue;
  readonly basis: ProvenanceBasis;
  readonly confidence: Confidence;
  readonly assertedByActorId: Identity | null;
  readonly granteeActorId: Identity | null;
  readonly evidenceRevisionIds: ReadonlyArray<Identity>;
  readonly licenseObservationRevisionId: Identity | null;
  readonly entitlementRevisionId: Identity | null;
  readonly recordedAt: string;
  readonly expiresAt: string | null;
  readonly confirmationRequired: boolean;
}

export interface RightsSourceObservation {
  readonly projectId: ProjectIdentity;
  readonly sourceAssertionRevisionId: Identity;
  readonly address: SourceAddress;
  readonly sourceRevisionId: Identity;
  readonly sourceSha256: Digest;
  readonly provider: string;
  readonly terms: SourceTerms;
  readonly retrievedAt: string | null;
}

export interface RightsSubject {
  readonly projectId: ProjectIdentity;
  readonly sourceAssertionRevisionId: Identity;
  readonly address: SourceAddress;
  readonly copyId: Identity;
  readonly copyLocation: CopyLocation;
  readonly resourceClass: ResourceClass;
}

export interface RightsUse {
  readonly action: RightsAction;
  readonly purpose: string;
  readonly destinationKind: DestinationKind;
  readonly provider: string | null;
  readonly region: string | null;
  readonly shareGroup: string | null;
}

export interface SourceAddress {
  readonly kind: "import-member" | "connector-record";
  readonly contextId: Identity;
  readonly revisionId: Identity;
  readonly ordinal: number;
  readonly recordKey: Digest | null;
}

export interface SourceObservation {
  readonly state: "reported" | "not-reported" | "unknown" | "not-applicable";
  readonly value: BoundedText | null;
}

export interface SourceTerms {
  readonly license: SourceObservation;
  readonly terms: SourceObservation;
  readonly access: "open" | "closed" | "unknown" | "not-reported";
}

export interface RightsPolicyRevision {
  readonly schemaVersion: "1.0";
  readonly contractVersion: "1.0.0";
  readonly documentType: "research-observatory-rights-policy-revision";
  readonly revisionId: Identity;
  readonly predecessorRevisionId: Identity | null;
  readonly subject: RightsSubject;
  readonly sourceObservation: RightsSourceObservation | null;
  readonly permissions: ReadonlyArray<RightsPermission>;
}

export type AuthorityKind = "policy" | "legacy-import-bridge" | "none";

export type DecisionCode = "allow" | "deny" | "unknown" | "require-confirmation";

export interface RightsDecision {
  readonly schemaVersion: "1.0";
  readonly contractVersion: "1.0.0";
  readonly documentType: "research-observatory-rights-decision";
  readonly code: DecisionCode;
  readonly reasonCode: string;
  readonly authorityKind: AuthorityKind;
  readonly actorId: Identity;
  readonly subject: RightsSubject;
  readonly use: RightsUse;
  readonly policyRevisionId: Identity | null;
  readonly governingAssertionIds: ReadonlyArray<Identity>;
  readonly sourceAssertionSha256: Digest | null;
  readonly evaluatedAt: string;
  readonly expiresAt: string | null;
}

export type RightsDocument = RightsPolicyRevision | RightsDecision;
export const RIGHTS_POLICY_SCHEMA_SHA256 = "00d5a013a85c52d01a3d6a513981c13345e95b366e6eab77f8efed1c4ce99dc3";

const SCHEMA: unknown = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://research-observatory.local/contracts/rights/rights-policy.schema.json",
  "title": "Research Observatory rights policy and decision documents",
  "description": "Versioned source/copy-specific values; Core rechecks current policy and independent actor, Intent, privacy and project authority at use time.",
  "x-research-observatory-semanticRules": [
    "one-exact-project-source-address-copy-resource-per-policy",
    "unique-assertion-and-evidence-identities",
    "action-purpose-destination-context-is-exact",
    "source-observation-is-not-permission",
    "reported-license-access-and-terms-are-non-granting-source-observations",
    "source-observation-binds-the-exact-record-assertion-and-hash",
    "entitlement-and-confirmation-provenance",
    "canonical-real-utc-millisecond-time-and-expiry",
    "decision-is-a-historical-fact-not-use-authority",
    "legacy-import-bridge-requires-exact-retained-assertion-hash-and-local-metadata-scope"
  ],
  "oneOf": [
    {
      "$ref": "#/$defs/RightsPolicyRevision"
    },
    {
      "$ref": "#/$defs/RightsDecision"
    }
  ],
  "$defs": {
    "BoundedText": {
      "maxLength": 65536,
      "minLength": 1,
      "type": "string"
    },
    "Confidence": {
      "enum": [
        "reported",
        "confirmed",
        "verified",
        "disputed"
      ],
      "type": "string"
    },
    "CopyLocation": {
      "enum": [
        "local-project-object",
        "local-source",
        "provider-hosted",
        "collaboration-copy"
      ],
      "type": "string"
    },
    "DestinationKind": {
      "enum": [
        "local-project",
        "local-export",
        "remote-model",
        "external-export",
        "collaboration"
      ],
      "type": "string"
    },
    "Digest": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "Identity": {
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "type": "string"
    },
    "PermissionValue": {
      "enum": [
        "permitted",
        "denied",
        "unknown"
      ],
      "type": "string"
    },
    "ProjectIdentity": {
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[47][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "type": "string"
    },
    "ProvenanceBasis": {
      "enum": [
        "source-observation",
        "researcher-confirmed",
        "verified-entitlement"
      ],
      "type": "string"
    },
    "ResourceClass": {
      "enum": [
        "metadata",
        "full-text",
        "derived-text",
        "embedding"
      ],
      "type": "string"
    },
    "RightsAction": {
      "enum": [
        "store",
        "inspect",
        "index",
        "derive",
        "model-use",
        "quote",
        "export",
        "share"
      ],
      "type": "string"
    },
    "RightsPermission": {
      "additionalProperties": false,
      "properties": {
        "assertionId": {
          "$ref": "#/$defs/Identity"
        },
        "subject": {
          "$ref": "#/$defs/RightsSubject"
        },
        "use": {
          "$ref": "#/$defs/RightsUse"
        },
        "value": {
          "$ref": "#/$defs/PermissionValue"
        },
        "basis": {
          "$ref": "#/$defs/ProvenanceBasis"
        },
        "confidence": {
          "$ref": "#/$defs/Confidence"
        },
        "assertedByActorId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "granteeActorId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "evidenceRevisionIds": {
          "items": {
            "$ref": "#/$defs/Identity"
          },
          "maxItems": 16,
          "type": "array"
        },
        "licenseObservationRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "entitlementRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "recordedAt": {
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
          "type": "string"
        },
        "expiresAt": {
          "anyOf": [
            {
              "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "confirmationRequired": {
          "type": "boolean"
        }
      },
      "required": [
        "assertionId",
        "subject",
        "use",
        "value",
        "basis",
        "confidence",
        "assertedByActorId",
        "granteeActorId",
        "evidenceRevisionIds",
        "licenseObservationRevisionId",
        "entitlementRevisionId",
        "recordedAt",
        "expiresAt",
        "confirmationRequired"
      ],
      "type": "object"
    },
    "RightsSourceObservation": {
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "$ref": "#/$defs/ProjectIdentity"
        },
        "sourceAssertionRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "address": {
          "$ref": "#/$defs/SourceAddress"
        },
        "sourceRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "sourceSha256": {
          "$ref": "#/$defs/Digest"
        },
        "provider": {
          "pattern": "^[a-z][a-z0-9-]{0,63}$",
          "type": "string"
        },
        "terms": {
          "$ref": "#/$defs/SourceTerms"
        },
        "retrievedAt": {
          "anyOf": [
            {
              "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "projectId",
        "sourceAssertionRevisionId",
        "address",
        "sourceRevisionId",
        "sourceSha256",
        "provider",
        "terms",
        "retrievedAt"
      ],
      "type": "object"
    },
    "RightsSubject": {
      "additionalProperties": false,
      "properties": {
        "projectId": {
          "$ref": "#/$defs/ProjectIdentity"
        },
        "sourceAssertionRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "address": {
          "$ref": "#/$defs/SourceAddress"
        },
        "copyId": {
          "$ref": "#/$defs/Identity"
        },
        "copyLocation": {
          "$ref": "#/$defs/CopyLocation"
        },
        "resourceClass": {
          "$ref": "#/$defs/ResourceClass"
        }
      },
      "required": [
        "projectId",
        "sourceAssertionRevisionId",
        "address",
        "copyId",
        "copyLocation",
        "resourceClass"
      ],
      "type": "object"
    },
    "RightsUse": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "$ref": "#/$defs/RightsAction"
        },
        "purpose": {
          "pattern": "^[a-z][a-z0-9-]{0,63}$",
          "type": "string"
        },
        "destinationKind": {
          "$ref": "#/$defs/DestinationKind"
        },
        "provider": {
          "anyOf": [
            {
              "pattern": "^[a-z][a-z0-9-]{0,63}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "region": {
          "anyOf": [
            {
              "pattern": "^[a-z][a-z0-9-]{0,63}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "shareGroup": {
          "anyOf": [
            {
              "pattern": "^[a-z][a-z0-9-]{0,63}$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "action",
        "purpose",
        "destinationKind",
        "provider",
        "region",
        "shareGroup"
      ],
      "type": "object"
    },
    "SourceAddress": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "enum": [
            "import-member",
            "connector-record"
          ],
          "type": "string"
        },
        "contextId": {
          "$ref": "#/$defs/Identity"
        },
        "revisionId": {
          "$ref": "#/$defs/Identity"
        },
        "ordinal": {
          "maximum": 200000,
          "minimum": 0,
          "type": "integer"
        },
        "recordKey": {
          "anyOf": [
            {
              "$ref": "#/$defs/Digest"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "kind",
        "contextId",
        "revisionId",
        "ordinal",
        "recordKey"
      ],
      "type": "object"
    },
    "SourceObservation": {
      "additionalProperties": false,
      "properties": {
        "state": {
          "enum": [
            "reported",
            "not-reported",
            "unknown",
            "not-applicable"
          ],
          "type": "string"
        },
        "value": {
          "anyOf": [
            {
              "$ref": "#/$defs/BoundedText"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "state",
        "value"
      ],
      "type": "object"
    },
    "SourceTerms": {
      "additionalProperties": false,
      "properties": {
        "license": {
          "$ref": "#/$defs/SourceObservation"
        },
        "terms": {
          "$ref": "#/$defs/SourceObservation"
        },
        "access": {
          "enum": [
            "open",
            "closed",
            "unknown",
            "not-reported"
          ],
          "type": "string"
        }
      },
      "required": [
        "license",
        "terms",
        "access"
      ],
      "type": "object"
    },
    "RightsPolicyRevision": {
      "additionalProperties": false,
      "properties": {
        "schemaVersion": {
          "const": "1.0",
          "type": "string"
        },
        "contractVersion": {
          "const": "1.0.0",
          "type": "string"
        },
        "documentType": {
          "const": "research-observatory-rights-policy-revision",
          "type": "string"
        },
        "revisionId": {
          "$ref": "#/$defs/Identity"
        },
        "predecessorRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "subject": {
          "$ref": "#/$defs/RightsSubject"
        },
        "sourceObservation": {
          "anyOf": [
            {
              "$ref": "#/$defs/RightsSourceObservation"
            },
            {
              "type": "null"
            }
          ]
        },
        "permissions": {
          "items": {
            "$ref": "#/$defs/RightsPermission"
          },
          "maxItems": 256,
          "type": "array"
        }
      },
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "revisionId",
        "predecessorRevisionId",
        "subject",
        "sourceObservation",
        "permissions"
      ],
      "type": "object"
    },
    "AuthorityKind": {
      "enum": [
        "policy",
        "legacy-import-bridge",
        "none"
      ],
      "type": "string"
    },
    "DecisionCode": {
      "enum": [
        "allow",
        "deny",
        "unknown",
        "require-confirmation"
      ],
      "type": "string"
    },
    "RightsDecision": {
      "additionalProperties": false,
      "properties": {
        "schemaVersion": {
          "const": "1.0",
          "type": "string"
        },
        "contractVersion": {
          "const": "1.0.0",
          "type": "string"
        },
        "documentType": {
          "const": "research-observatory-rights-decision",
          "type": "string"
        },
        "code": {
          "$ref": "#/$defs/DecisionCode"
        },
        "reasonCode": {
          "pattern": "^[a-z][a-z0-9-]{0,63}$",
          "type": "string"
        },
        "authorityKind": {
          "$ref": "#/$defs/AuthorityKind"
        },
        "actorId": {
          "$ref": "#/$defs/Identity"
        },
        "subject": {
          "$ref": "#/$defs/RightsSubject"
        },
        "use": {
          "$ref": "#/$defs/RightsUse"
        },
        "policyRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "governingAssertionIds": {
          "items": {
            "$ref": "#/$defs/Identity"
          },
          "maxItems": 256,
          "type": "array"
        },
        "sourceAssertionSha256": {
          "anyOf": [
            {
              "$ref": "#/$defs/Digest"
            },
            {
              "type": "null"
            }
          ]
        },
        "evaluatedAt": {
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
          "type": "string"
        },
        "expiresAt": {
          "anyOf": [
            {
              "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "code",
        "reasonCode",
        "authorityKind",
        "actorId",
        "subject",
        "use",
        "policyRevisionId",
        "governingAssertionIds",
        "sourceAssertionSha256",
        "evaluatedAt",
        "expiresAt"
      ],
      "type": "object"
    }
  }
};
type JsonRecord = Record<string, unknown>;
const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);

function record(value: unknown): JsonRecord | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) return null;
  const descriptors = Object.getOwnPropertyDescriptors(value);
  if (Object.keys(descriptors).length > 64 || Object.entries(descriptors).some(([key, property]) =>
    FORBIDDEN.has(key) || !("value" in property))) return null;
  return value as JsonRecord;
}

function matches(value: unknown, rawNode: unknown, depth = 0): boolean {
  if (depth > 14) return false;
  const node = record(rawNode);
  const definitions = record(record(SCHEMA)?.$defs);
  if (!node || !definitions) return false;
  if (typeof node.$ref === "string") {
    const name = node.$ref.startsWith("#/$defs/") ? node.$ref.slice(8) : "";
    return name !== "" && matches(value, definitions[name], depth + 1);
  }
  if (Object.hasOwn(node, "const") && value !== node.const) return false;
  if (Array.isArray(node.enum) && !node.enum.includes(value)) return false;
  if (Array.isArray(node.anyOf) && !node.anyOf.some((option) => matches(value, option, depth + 1))) return false;
  if (Array.isArray(node.oneOf) && node.oneOf.filter((option) => matches(value, option, depth + 1)).length !== 1) return false;
  if (node.type === "null") return value === null;
  if (node.type === "string" || typeof node.pattern === "string") {
    if (typeof value !== "string") return false;
    const scalarLength = Array.from(value).length;
    if (scalarLength > 65536) return false;
    if (typeof node.minLength === "number" && scalarLength < node.minLength) return false;
    if (typeof node.maxLength === "number" && scalarLength > node.maxLength) return false;
    if (typeof node.maxLength !== "number" && scalarLength > 256) return false;
    if (typeof node.pattern === "string") {
      const hit = new RegExp(node.pattern, "u").exec(value);
      if (!hit || hit.index !== 0 || hit[0].length !== value.length) return false;
    }
  }
  if (node.type === "integer") {
    if (!Number.isSafeInteger(value)) return false;
    if (typeof node.minimum === "number" && (value as number) < node.minimum) return false;
    if (typeof node.maximum === "number" && (value as number) > node.maximum) return false;
  }
  if (node.type === "boolean" && typeof value !== "boolean") return false;
  if (node.type === "array") {
    if (!Array.isArray(value) || value.length > 256) return false;
    if (typeof node.maxItems === "number" && value.length > node.maxItems) return false;
    if (!value.every((item) => matches(item, node.items, depth + 1))) return false;
  }
  if (node.type === "object") {
    const item = record(value);
    const properties = record(node.properties);
    if (!item || !properties || !Array.isArray(node.required)) return false;
    const keys = Object.keys(item);
    if (node.additionalProperties === false && keys.some((key) => !Object.hasOwn(properties, key))) return false;
    if (!node.required.every((key) => typeof key === "string" && Object.hasOwn(item, key))) return false;
    if (!keys.every((key) => matches(item[key], properties[key], depth + 1))) return false;
  }
  return true;
}

function canonicalUtcMillis(value: unknown): value is string {
  return typeof value === "string" && !value.startsWith("0000")
    && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
}

function sameSubject(first: JsonRecord, second: JsonRecord): boolean {
  for (const key of ["projectId", "sourceAssertionRevisionId", "copyId", "copyLocation", "resourceClass"])
    if (first[key] !== second[key]) return false;
  const left = record(first.address);
  const right = record(second.address);
  if (!left || !right) return false;
  return ["kind", "contextId", "revisionId", "ordinal", "recordKey"].every((key) => left[key] === right[key]);
}

function validAddress(subject: JsonRecord): boolean {
  const address = record(subject.address);
  if (!address) return false;
  if (address.kind === "import-member") return typeof address.ordinal === "number"
    && address.ordinal >= 1 && typeof address.recordKey === "string";
  return address.kind === "connector-record" && typeof address.ordinal === "number"
    && address.ordinal <= 999 && address.recordKey === null;
}

function validUse(raw: unknown): boolean {
  const use = record(raw);
  if (!use) return false;
  const action = use.action;
  const destination = use.destinationKind;
  if (["store", "inspect", "index", "derive", "quote"].includes(String(action)) && destination !== "local-project") return false;
  if (action === "model-use" && !["local-project", "remote-model"].includes(String(destination))) return false;
  if (action === "export" && !["local-export", "external-export"].includes(String(destination))) return false;
  if (action === "share" && destination !== "collaboration") return false;
  if (["remote-model", "external-export"].includes(String(destination)))
    return use.provider !== null && use.region !== null && use.shareGroup === null;
  if (destination === "collaboration")
    return use.shareGroup !== null && use.provider === null && use.region === null;
  return use.provider === null && use.region === null && use.shareGroup === null;
}

function validPermission(raw: unknown, subject: JsonRecord): boolean {
  const item = record(raw);
  const itemSubject = record(item?.subject);
  if (!item || !itemSubject || !sameSubject(subject, itemSubject) || !validUse(item.use)) return false;
  if (!canonicalUtcMillis(item.recordedAt)) return false;
  if (item.expiresAt !== null && (!canonicalUtcMillis(item.expiresAt) || item.expiresAt <= item.recordedAt)) return false;
  const evidence = item.evidenceRevisionIds;
  if (!Array.isArray(evidence) || new Set(evidence).size !== evidence.length) return false;
  if (item.value !== "unknown" && evidence.length === 0) return false;
  if (item.confirmationRequired && item.value !== "permitted") return false;
  if (item.basis === "source-observation") return item.assertedByActorId === null
    && item.entitlementRevisionId === null && ["reported", "disputed"].includes(String(item.confidence))
    && item.confirmationRequired === false;
  if (item.basis === "researcher-confirmed") return item.assertedByActorId !== null
    && item.entitlementRevisionId === null && item.confidence === "confirmed";
  return item.basis === "verified-entitlement" && item.assertedByActorId !== null
    && item.entitlementRevisionId !== null && item.confidence === "verified";
}

function validObservation(raw: unknown, subject: JsonRecord): boolean {
  if (raw === null) return true;
  const observation = record(raw);
  const source = record(observation?.address);
  const address = record(subject.address);
  const terms = record(observation?.terms);
  if (!observation || !source || !address || !terms
    || observation.projectId !== subject.projectId
    || observation.sourceAssertionRevisionId !== subject.sourceAssertionRevisionId
    || !["kind", "contextId", "revisionId", "ordinal", "recordKey"]
      .every((key) => source[key] === address[key])) return false;
  if (address.kind === "connector-record"
    && (observation.sourceRevisionId !== address.revisionId || observation.retrievedAt === null)) return false;
  if (observation.retrievedAt !== null && !canonicalUtcMillis(observation.retrievedAt)) return false;
  for (const name of ["license", "terms"]) {
    const reported = record(terms[name]);
    if (!reported || (reported.state === "reported") !== (reported.value !== null)) return false;
  }
  return true;
}

function semanticError(document: JsonRecord): string | null {
  const subject = record(document.subject);
  if (!subject || !validAddress(subject)) return "rights-source-address-invalid";
  if (document.documentType === "research-observatory-rights-policy-revision") {
    if (document.revisionId === document.predecessorRevisionId) return "rights-revision-self-predecessor";
    if (!validObservation(document.sourceObservation, subject)) return "rights-observation-invalid";
    const permissions = document.permissions;
    if (!Array.isArray(permissions)) return "rights-permissions-invalid";
    const seen = new Set<string>();
    for (const permission of permissions) {
      const item = record(permission);
      if (!item || !validPermission(item, subject) || typeof item.assertionId !== "string"
        || seen.has(item.assertionId)) return "rights-permission-invalid";
      seen.add(item.assertionId);
    }
    return null;
  }
  if (document.documentType === "research-observatory-rights-decision") {
    if (!validUse(document.use) || !canonicalUtcMillis(document.evaluatedAt)) return "rights-decision-invalid";
    if (document.expiresAt !== null && !canonicalUtcMillis(document.expiresAt)) return "rights-decision-invalid";
    const ids = document.governingAssertionIds;
    if (!Array.isArray(ids) || ids.some((item, index) => index > 0 && ids[index - 1] >= item))
      return "rights-decision-invalid";
    const authority = document.authorityKind;
    if ((authority === "policy") !== (document.policyRevisionId !== null))
      return "rights-decision-invalid";
    if (authority === "legacy-import-bridge") {
      const requested = record(document.use);
      const address = record(subject.address);
      if (document.code !== "allow" || document.reasonCode !== "rights-legacy-import-confirmed"
        || ids.length !== 1 || ids[0] !== subject.sourceAssertionRevisionId
        || document.sourceAssertionSha256 === null || address?.kind !== "import-member"
        || subject.copyId !== subject.sourceAssertionRevisionId || subject.copyLocation !== "local-source"
        || subject.resourceClass !== "metadata" || !requested
        || !["store", "inspect", "derive", "index"].includes(String(requested.action))
        || requested.purpose !== "corpus-membership" || requested.destinationKind !== "local-project"
        || document.expiresAt !== null) return "rights-decision-invalid";
    }
    if (document.code === "allow" && (authority === "none" || ids.length === 0
      || (document.expiresAt !== null && document.expiresAt <= document.evaluatedAt)))
      return "rights-decision-invalid";
    return null;
  }
  return "rights-document-type-invalid";
}

export function rightsContractErrors(value: unknown): ReadonlyArray<string> {
  try {
    if (!matches(value, SCHEMA)) return Object.freeze(["rights-contract-schema-invalid"]);
    const error = semanticError(value as JsonRecord);
    return Object.freeze(error === null ? [] : [error]);
  } catch {
    return Object.freeze(["rights-contract-schema-invalid"]);
  }
}

function freezeDeep(value: unknown): void {
  if (value === null || typeof value !== "object") return;
  for (const child of Object.values(value)) freezeDeep(child);
  Object.freeze(value);
}

export function decodeRightsDocument(value: unknown): RightsDocument | null {
  if (rightsContractErrors(value).length !== 0) return null;
  try {
    const copy: unknown = JSON.parse(JSON.stringify(value));
    freezeDeep(copy);
    return copy as RightsDocument;
  } catch {
    return null;
  }
}
