// Generated by packages/contracts/provenance/generate.mjs. Do not edit by hand.
// Source: packages/contracts/provenance/provenance-event.schema.json

export type ProvenanceSensitivity =
  | "public-metadata"
  | "licensed-metadata"
  | "open-full-text"
  | "licensed-full-text"
  | "private-research"
  | "restricted";
export type ProvenanceRetentionClass =
  | "project-lifetime"
  | "legal-hold"
  | "policy-bound"
  | "time-bounded"
  | "tombstone-only";
export type ProvenanceAgentType = "human" | "software" | "model" | "system";
export type ProvenanceActivityStatus = "succeeded" | "failed" | "cancelled" | "denied";
export type ProvenanceRelationType =
  | "used"
  | "wasGeneratedBy"
  | "wasAssociatedWith"
  | "wasDerivedFrom"
  | "wasInvalidatedBy"
  | "wasAttributedTo";

export interface ProvenanceAgent {
  readonly agentId: string;
  readonly agentType: ProvenanceAgentType;
  readonly role: string;
}
export interface VersionedConfiguration {
  readonly configurationId: string;
  readonly configurationVersion: string;
  readonly configurationHash: string;
}
export interface ProvenanceActivity {
  readonly activityId: string;
  readonly activityType: string;
  readonly status: ProvenanceActivityStatus;
  readonly startedAt: string;
  readonly endedAt: string;
  readonly configuration: VersionedConfiguration;
}
export interface ProvenanceEntity {
  readonly entityId: string;
  readonly revisionId: string;
  readonly entityKind: string;
  readonly contentHash: string;
  readonly sensitivity: ProvenanceSensitivity;
  readonly retentionClass: ProvenanceRetentionClass;
}
export interface ProvenanceEntityReference {
  readonly entityId: string;
  readonly revisionId: string;
}
export interface ProvenanceRelation {
  readonly relationId: string;
  readonly relationType: ProvenanceRelationType;
  readonly entity: ProvenanceEntityReference | null;
  readonly relatedEntity: ProvenanceEntityReference | null;
  readonly activityId: string | null;
  readonly agentId: string | null;
  readonly occurredAt: string;
}
export type EventPayloadReference =
  | { readonly state: "not-applicable" }
  | {
      readonly state: "referenced";
      readonly objectId: string;
      readonly revisionId: string;
      readonly contentHash: string;
      readonly mediaType: string;
    };
export interface ProvenanceData {
  readonly agent: ProvenanceAgent;
  readonly activity: ProvenanceActivity;
  readonly inputs: readonly ProvenanceEntity[];
  readonly outputs: readonly ProvenanceEntity[];
  readonly relations: readonly ProvenanceRelation[];
  readonly payloadReference: EventPayloadReference;
}
export interface ProvenanceEvent {
  readonly specversion: "1.0";
  readonly id: string;
  readonly source: "urn:research-observatory:core";
  readonly type: string;
  readonly subject: string;
  readonly time: string;
  readonly dataschema: "urn:research-observatory:schema:provenance-event:1.0.0";
  readonly datacontenttype: "application/json";
  readonly projectid: string;
  readonly actorid: string;
  readonly correlationid: string;
  readonly causationid: string | null;
  readonly traceparent: string;
  readonly sensitivity: ProvenanceSensitivity;
  readonly retentionclass: ProvenanceRetentionClass;
  readonly schemaversion: "1.0.0";
  readonly data: ProvenanceData;
}

export const PROVENANCE_SCHEMA_SHA256 = "905ed187737757c7fd9f610fe1edc7af34fd0af40c25ad39ebac9580ee9bd1e9";
export const KNOWN_PROVENANCE_EVENT_ACTIVITIES = Object.freeze({
  "org.research-observatory.source.acquired.v1": "source-acquisition",
  "org.research-observatory.document.parsed.v1": "parsing",
  "org.research-observatory.evidence.extracted.v1": "extraction",
  "org.research-observatory.evidence.verified.v1": "verification",
  "org.research-observatory.decision.recorded.v1": "decision",
  "org.research-observatory.synthesis.produced.v1": "synthesis",
  "org.research-observatory.export.created.v1": "export",
  "org.research-observatory.entity.invalidated.v1": "invalidation",
} as const);

type JsonRecord = Record<string, unknown>;
const DANGEROUS_KEYS = new Set(["__proto__", "constructor", "prototype"]);
const UUID_V7 = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const PROJECT_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-(?:4[0-9a-f]{3}|7[0-9a-f]{3})-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const UTC_INSTANT = /^(?!0000)[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])T(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\.[0-9]{3}Z$/u;
const SEMVER = /^(?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8})\.(?:0|[1-9][0-9]{0,8})$/u;
const SHA256 = /^sha256:[0-9a-f]{64}$/u;
const PORTABLE_KEY = /^[a-z][a-z0-9]*(?:[._:-][a-z0-9]+){0,15}$/u;
const EVENT_TYPE = /^org\.research-observatory\.[a-z][a-z0-9]*(?:\.[a-z][a-z0-9-]*){1,8}\.v[1-9][0-9]{0,5}$/u;
const TRACEPARENT = /^00-(?!0{32})[0-9a-f]{32}-(?!0{16})[0-9a-f]{16}-[0-9a-f]{2}$/u;
const ENTITY_SUBJECT = /^project\/[0-9a-f]{8}-[0-9a-f]{4}-(?:4[0-9a-f]{3}|7[0-9a-f]{3})-[89ab][0-9a-f]{3}-[0-9a-f]{12}\/entity\/[a-z][a-z0-9-]{0,63}\/[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\/revision\/[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const ACTIVITY_SUBJECT = /^project\/[0-9a-f]{8}-[0-9a-f]{4}-(?:4[0-9a-f]{3}|7[0-9a-f]{3})-[89ab][0-9a-f]{3}-[0-9a-f]{12}\/activity\/[a-z][a-z0-9]*(?:[._:-][a-z0-9]+){0,15}\/[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;
const MEDIA_TYPE = /^[a-z0-9][a-z0-9!#$&^_.+-]{0,49}\/[a-z0-9][a-z0-9!#$&^_.+-]{0,49}$/u;
const SENSITIVITY = new Set<ProvenanceSensitivity>([
  "public-metadata", "licensed-metadata", "open-full-text", "licensed-full-text", "private-research", "restricted",
]);
const RETENTION = new Set<ProvenanceRetentionClass>([
  "project-lifetime", "legal-hold", "policy-bound", "time-bounded", "tombstone-only",
]);
const AGENT_TYPES = new Set<ProvenanceAgentType>(["human", "software", "model", "system"]);
const ACTIVITY_STATUSES = new Set<ProvenanceActivityStatus>(["succeeded", "failed", "cancelled", "denied"]);
const RELATION_TYPES = new Set<ProvenanceRelationType>([
  "used", "wasGeneratedBy", "wasAssociatedWith", "wasDerivedFrom", "wasInvalidatedBy", "wasAttributedTo",
]);

function record(value: unknown): JsonRecord | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) return null;
  const candidate = value as JsonRecord;
  return Object.keys(candidate).some((key) => DANGEROUS_KEYS.has(key)) ? null : candidate;
}

function exactKeys(value: JsonRecord, keys: readonly string[], path: string, errors: string[]): void {
  const expected = new Set(keys);
  for (const key of keys) if (!Object.hasOwn(value, key)) errors.push(`${path}/${key}: required`);
  for (const key of Object.keys(value)) if (!expected.has(key)) errors.push(`${path}/${key}: additional property`);
}

function stringPattern(value: unknown, pattern: RegExp, path: string, errors: string[], maxLength = 240): value is string {
  if (typeof value !== "string" || value.length > maxLength || !pattern.test(value)) {
    errors.push(`${path}: pattern`);
    return false;
  }
  return true;
}

function utcInstant(value: unknown, path: string, errors: string[]): value is string {
  if (!stringPattern(value, UTC_INSTANT, path, errors, 24)) return false;
  const date = new Date(value);
  if (!Number.isFinite(date.valueOf()) || date.toISOString() !== value) {
    errors.push(`${path}: calendar`);
    return false;
  }
  return true;
}

function nullableUuid(value: unknown, path: string, errors: string[]): value is string | null {
  return value === null || stringPattern(value, UUID_V7, path, errors, 36);
}

function entityErrors(value: unknown, path: string, errors: string[]): void {
  const item = record(value);
  if (!item) { errors.push(`${path}: object`); return; }
  exactKeys(item, ["entityId", "revisionId", "entityKind", "contentHash", "sensitivity", "retentionClass"], path, errors);
  stringPattern(item.entityId, UUID_V7, `${path}/entityId`, errors, 36);
  stringPattern(item.revisionId, UUID_V7, `${path}/revisionId`, errors, 36);
  stringPattern(item.entityKind, PORTABLE_KEY, `${path}/entityKind`, errors, 128);
  stringPattern(item.contentHash, SHA256, `${path}/contentHash`, errors, 71);
  if (!SENSITIVITY.has(item.sensitivity as ProvenanceSensitivity)) errors.push(`${path}/sensitivity: enum`);
  if (!RETENTION.has(item.retentionClass as ProvenanceRetentionClass)) errors.push(`${path}/retentionClass: enum`);
}

function entityReferenceErrors(value: unknown, path: string, errors: string[]): void {
  if (value === null) return;
  const item = record(value);
  if (!item) { errors.push(`${path}: object-or-null`); return; }
  exactKeys(item, ["entityId", "revisionId"], path, errors);
  stringPattern(item.entityId, UUID_V7, `${path}/entityId`, errors, 36);
  stringPattern(item.revisionId, UUID_V7, `${path}/revisionId`, errors, 36);
}

function relationErrors(value: unknown, path: string, errors: string[]): void {
  const item = record(value);
  if (!item) { errors.push(`${path}: object`); return; }
  exactKeys(item, ["relationId", "relationType", "entity", "relatedEntity", "activityId", "agentId", "occurredAt"], path, errors);
  stringPattern(item.relationId, UUID_V7, `${path}/relationId`, errors, 36);
  if (!RELATION_TYPES.has(item.relationType as ProvenanceRelationType)) errors.push(`${path}/relationType: enum`);
  entityReferenceErrors(item.entity, `${path}/entity`, errors);
  entityReferenceErrors(item.relatedEntity, `${path}/relatedEntity`, errors);
  nullableUuid(item.activityId, `${path}/activityId`, errors);
  nullableUuid(item.agentId, `${path}/agentId`, errors);
  utcInstant(item.occurredAt, `${path}/occurredAt`, errors);
}

function structuralErrors(value: unknown): string[] {
  const errors: string[] = [];
  const event = record(value);
  if (!event) return ["$: object"];
  const topKeys = [
    "specversion", "id", "source", "type", "subject", "time", "dataschema", "datacontenttype",
    "projectid", "actorid", "correlationid", "causationid", "traceparent", "sensitivity",
    "retentionclass", "schemaversion", "data",
  ];
  exactKeys(event, topKeys, "$", errors);
  if (event.specversion !== "1.0") errors.push("$/specversion: const");
  stringPattern(event.id, UUID_V7, "$/id", errors, 36);
  if (event.source !== "urn:research-observatory:core") errors.push("$/source: const");
  stringPattern(event.type, EVENT_TYPE, "$/type", errors, 160);
  if (
    typeof event.subject !== "string"
    || event.subject.length > 300
    || (!ENTITY_SUBJECT.test(event.subject) && !ACTIVITY_SUBJECT.test(event.subject))
  ) errors.push("$/subject: pattern");
  utcInstant(event.time, "$/time", errors);
  if (event.dataschema !== "urn:research-observatory:schema:provenance-event:1.0.0") errors.push("$/dataschema: const");
  if (event.datacontenttype !== "application/json") errors.push("$/datacontenttype: const");
  stringPattern(event.projectid, PROJECT_ID, "$/projectid", errors, 36);
  stringPattern(event.actorid, UUID_V7, "$/actorid", errors, 36);
  stringPattern(event.correlationid, UUID_V7, "$/correlationid", errors, 36);
  nullableUuid(event.causationid, "$/causationid", errors);
  stringPattern(event.traceparent, TRACEPARENT, "$/traceparent", errors, 55);
  if (!SENSITIVITY.has(event.sensitivity as ProvenanceSensitivity)) errors.push("$/sensitivity: enum");
  if (!RETENTION.has(event.retentionclass as ProvenanceRetentionClass)) errors.push("$/retentionclass: enum");
  if (event.schemaversion !== "1.0.0") errors.push("$/schemaversion: const");
  const data = record(event.data);
  if (!data) return [...errors, "$/data: object"];
  exactKeys(data, ["agent", "activity", "inputs", "outputs", "relations", "payloadReference"], "$/data", errors);
  const agent = record(data.agent);
  if (!agent) errors.push("$/data/agent: object");
  else {
    exactKeys(agent, ["agentId", "agentType", "role"], "$/data/agent", errors);
    stringPattern(agent.agentId, UUID_V7, "$/data/agent/agentId", errors, 36);
    if (!AGENT_TYPES.has(agent.agentType as ProvenanceAgentType)) errors.push("$/data/agent/agentType: enum");
    stringPattern(agent.role, PORTABLE_KEY, "$/data/agent/role", errors, 128);
  }
  const activity = record(data.activity);
  if (!activity) errors.push("$/data/activity: object");
  else {
    exactKeys(activity, ["activityId", "activityType", "status", "startedAt", "endedAt", "configuration"], "$/data/activity", errors);
    stringPattern(activity.activityId, UUID_V7, "$/data/activity/activityId", errors, 36);
    stringPattern(activity.activityType, PORTABLE_KEY, "$/data/activity/activityType", errors, 128);
    if (!ACTIVITY_STATUSES.has(activity.status as ProvenanceActivityStatus)) errors.push("$/data/activity/status: enum");
    utcInstant(activity.startedAt, "$/data/activity/startedAt", errors);
    utcInstant(activity.endedAt, "$/data/activity/endedAt", errors);
    const configuration = record(activity.configuration);
    if (!configuration) errors.push("$/data/activity/configuration: object");
    else {
      exactKeys(configuration, ["configurationId", "configurationVersion", "configurationHash"], "$/data/activity/configuration", errors);
      stringPattern(configuration.configurationId, PORTABLE_KEY, "$/data/activity/configuration/configurationId", errors, 128);
      stringPattern(configuration.configurationVersion, SEMVER, "$/data/activity/configuration/configurationVersion", errors, 29);
      stringPattern(configuration.configurationHash, SHA256, "$/data/activity/configuration/configurationHash", errors, 71);
    }
  }
  for (const name of ["inputs", "outputs"] as const) {
    const items = data[name];
    if (!Array.isArray(items) || items.length > 256) errors.push(`$/data/${name}: array bound`);
    else items.forEach((item, index) => entityErrors(item, `$/data/${name}/${index}`, errors));
  }
  if (!Array.isArray(data.relations) || data.relations.length < 1 || data.relations.length > 1024) errors.push("$/data/relations: array bound");
  else data.relations.forEach((item, index) => relationErrors(item, `$/data/relations/${index}`, errors));
  const payload = record(data.payloadReference);
  if (!payload) errors.push("$/data/payloadReference: object");
  else if (payload.state === "not-applicable") exactKeys(payload, ["state"], "$/data/payloadReference", errors);
  else if (payload.state === "referenced") {
    exactKeys(payload, ["state", "objectId", "revisionId", "contentHash", "mediaType"], "$/data/payloadReference", errors);
    stringPattern(payload.objectId, UUID_V7, "$/data/payloadReference/objectId", errors, 36);
    stringPattern(payload.revisionId, UUID_V7, "$/data/payloadReference/revisionId", errors, 36);
    stringPattern(payload.contentHash, SHA256, "$/data/payloadReference/contentHash", errors, 71);
    stringPattern(payload.mediaType, MEDIA_TYPE, "$/data/payloadReference/mediaType", errors, 100);
  } else errors.push("$/data/payloadReference/state: alternatives");
  return errors;
}

const referenceKey = (reference: ProvenanceEntityReference): string =>
  `${reference.entityId}:${reference.revisionId}`;
const entityReference = (entity: ProvenanceEntity): ProvenanceEntityReference => ({
  entityId: entity.entityId,
  revisionId: entity.revisionId,
});
const entitySubject = (projectId: string, entity: ProvenanceEntity): string =>
  `project/${projectId}/entity/${entity.entityKind}/${entity.entityId}/revision/${entity.revisionId}`;

function semanticErrors(event: ProvenanceEvent): string[] {
  const errors: string[] = [];
  const { activity, agent, inputs, outputs, relations } = event.data;
  const allEntities = [...inputs, ...outputs];
  const inputKeys = new Set(inputs.map((item) => referenceKey(item)));
  const outputKeys = new Set(outputs.map((item) => referenceKey(item)));
  const allEntityKeys = allEntities.map((item) => referenceKey(item));
  const allKeys = new Set(allEntityKeys);
  const refKeyOrNull = (reference: ProvenanceEntityReference | null): string | null =>
    reference === null ? null : referenceKey(reference);

  if (event.actorid !== agent.agentId) errors.push("actor-and-agent-match");
  if (!event.subject.startsWith(`project/${event.projectid}/`)) errors.push("event-project-and-subject-match");
  if (activity.startedAt > activity.endedAt) errors.push("activity-time-is-ordered");
  if (event.time !== activity.endedAt) errors.push("event-time-matches-activity-end");
  if (event.causationid === event.id) errors.push("causation-is-not-self");
  if ([...inputKeys].some((key) => outputKeys.has(key))) errors.push("input-output-revisions-are-disjoint");
  if (allKeys.size !== allEntityKeys.length) errors.push("entity-references-are-unique");
  if (allEntities.some((item) => item.sensitivity !== event.sensitivity || item.retentionClass !== event.retentionclass)) {
    errors.push("entity-policy-does-not-weaken-event");
  }

  const relationIds = relations.map((relation) => relation.relationId);
  const revisionIds = allEntities.map((entity) => entity.revisionId);
  const globalIds = [
    event.id,
    activity.activityId,
    agent.agentId,
    event.correlationid,
    ...(event.causationid === null ? [] : [event.causationid]),
    ...relationIds,
    ...revisionIds,
  ];
  const stableEntityIds = new Set(allEntities.map((entity) => entity.entityId));
  if (
    new Set(globalIds).size !== globalIds.length
    || [...stableEntityIds].some((entityId) => globalIds.includes(entityId))
  ) errors.push("identity-namespace-is-consistent");

  const exactActivitySubject = `project/${event.projectid}/activity/${activity.activityType}/${activity.activityId}`;
  const subjectEntity = allEntities.find((entity) => entitySubject(event.projectid, entity) === event.subject);
  if (subjectEntity === undefined && event.subject !== exactActivitySubject) {
    errors.push("subject-binds-exact-event-object");
  }
  if (allEntities.length > 0 && event.subject === exactActivitySubject) {
    errors.push("subject-binds-exact-event-object");
  }

  const expectedShape: Record<ProvenanceRelationType, readonly boolean[]> = {
    used: [true, false, true, false],
    wasGeneratedBy: [true, false, true, false],
    wasAssociatedWith: [false, false, true, true],
    wasDerivedFrom: [true, true, true, false],
    wasInvalidatedBy: [true, false, true, false],
    wasAttributedTo: [true, false, false, true],
  };
  const relationShape = relations.every((relation) => {
    if (relation.occurredAt < activity.startedAt || relation.occurredAt > activity.endedAt) return false;
    const entityKey = refKeyOrNull(relation.entity);
    const relatedKey = refKeyOrNull(relation.relatedEntity);
    if (entityKey !== null && !allKeys.has(entityKey)) return false;
    if (relatedKey !== null && !allKeys.has(relatedKey)) return false;
    if (relation.activityId !== null && relation.activityId !== activity.activityId) return false;
    if (relation.agentId !== null && relation.agentId !== agent.agentId) return false;
    const values = [relation.entity, relation.relatedEntity, relation.activityId, relation.agentId];
    return expectedShape[relation.relationType].every((present, index) => (values[index] !== null) === present);
  });
  if (!relationShape) errors.push("relations-close-over-event-objects");

  const relationFacts = relations.map((relation) => JSON.stringify([
    relation.relationType,
    refKeyOrNull(relation.entity),
    refKeyOrNull(relation.relatedEntity),
    relation.activityId,
    relation.agentId,
    relation.occurredAt,
  ]));
  if (new Set(relationIds).size !== relationIds.length || new Set(relationFacts).size !== relationFacts.length) {
    errors.push("relation-identities-and-facts-are-unique");
  }

  const relationRolesMatch = relations.every((relation) => {
    const entityKey = refKeyOrNull(relation.entity);
    const relatedKey = refKeyOrNull(relation.relatedEntity);
    if (relation.relationType === "used") return entityKey !== null && inputKeys.has(entityKey);
    if (relation.relationType === "wasGeneratedBy" || relation.relationType === "wasAttributedTo") {
      return entityKey !== null && outputKeys.has(entityKey);
    }
    if (relation.relationType === "wasDerivedFrom") {
      return entityKey !== null && relatedKey !== null && entityKey !== relatedKey
        && outputKeys.has(entityKey) && inputKeys.has(relatedKey);
    }
    if (relation.relationType === "wasInvalidatedBy") return entityKey !== null && inputKeys.has(entityKey);
    return relation.relationType === "wasAssociatedWith";
  });
  if (!relationRolesMatch) errors.push("relation-roles-match-event-objects");

  const producesFacts = new Set<ProvenanceRelationType>([
    "wasGeneratedBy", "wasDerivedFrom", "wasInvalidatedBy", "wasAttributedTo",
  ]);
  if (
    activity.status !== "succeeded"
    && relations.some((relation) => producesFacts.has(relation.relationType)
      || (activity.status === "denied" && relation.relationType === "used"))
  ) errors.push("relation-outcome-matches-activity-status");

  const associationCount = relations.filter((relation) => relation.relationType === "wasAssociatedWith").length;
  if (associationCount !== 1) errors.push("activity-agent-relation-is-complete");

  const knownActivity = KNOWN_PROVENANCE_EVENT_ACTIVITIES[event.type as keyof typeof KNOWN_PROVENANCE_EVENT_ACTIVITIES];
  if (knownActivity !== undefined && knownActivity !== activity.activityType) errors.push("known-event-type-matches-activity");
  if (knownActivity !== undefined) {
    const validShape = activity.status !== "succeeded"
      ? outputs.length === 0 && (knownActivity === "source-acquisition" ? inputs.length === 0 : inputs.length > 0)
      : knownActivity === "source-acquisition"
        ? inputs.length === 0 && outputs.length > 0
        : knownActivity === "invalidation"
          ? inputs.length > 0 && outputs.length === 0
          : inputs.length > 0 && outputs.length > 0;
    if (!validShape) errors.push("known-event-shape-matches-operation");

    const allowed = activity.status === "succeeded"
      ? knownActivity === "source-acquisition"
        ? new Set<ProvenanceRelationType>(["wasAssociatedWith", "wasGeneratedBy", "wasAttributedTo"])
        : knownActivity === "invalidation"
          ? new Set<ProvenanceRelationType>(["wasAssociatedWith", "wasInvalidatedBy"])
          : new Set<ProvenanceRelationType>([
              "used", "wasGeneratedBy", "wasAssociatedWith", "wasDerivedFrom", "wasAttributedTo",
            ])
      : new Set<ProvenanceRelationType>(
          activity.status === "denied" || knownActivity === "source-acquisition"
            ? ["wasAssociatedWith"]
            : ["used", "wasAssociatedWith"],
        );
    if (relations.some((relation) => !allowed.has(relation.relationType))) {
      errors.push("known-event-relations-match-operation");
    }

    const expectedSubjects = activity.status === "succeeded"
      ? knownActivity === "invalidation" ? inputs : outputs
      : knownActivity === "source-acquisition" ? [] : inputs;
    const validKnownSubject = expectedSubjects.length === 0
      ? event.subject === exactActivitySubject
      : expectedSubjects.some((entity) => entitySubject(event.projectid, entity) === event.subject);
    if (!validKnownSubject) errors.push("subject-binds-exact-event-object");

    if (activity.status === "succeeded") {
      const exactRelationCount = (
        type: ProvenanceRelationType,
        entity: ProvenanceEntity,
        related: ProvenanceEntity | null = null,
      ): number => relations.filter((relation) =>
        relation.relationType === type
        && refKeyOrNull(relation.entity) === referenceKey(entityReference(entity))
        && refKeyOrNull(relation.relatedEntity) === (related === null ? null : referenceKey(entityReference(related)))
      ).length;
      if (
        knownActivity !== "source-acquisition"
        && knownActivity !== "invalidation"
        && inputs.some((entity) => exactRelationCount("used", entity) !== 1)
      ) errors.push("input-use-relations-are-complete");
      if (
        knownActivity === "invalidation"
        && inputs.some((entity) => exactRelationCount("wasInvalidatedBy", entity) !== 1)
      ) errors.push("input-use-relations-are-complete");
      if (outputs.some((entity) => exactRelationCount("wasGeneratedBy", entity) !== 1)) {
        errors.push("output-generation-relations-are-complete");
      }
      if (outputs.some((entity) => exactRelationCount("wasAttributedTo", entity) !== 1)) {
        errors.push("output-attribution-relations-are-complete");
      }
      if (
        knownActivity !== "source-acquisition"
        && knownActivity !== "invalidation"
        && outputs.some((output) => !inputs.some((input) => exactRelationCount("wasDerivedFrom", output, input) === 1))
      ) errors.push("output-generation-relations-are-complete");
    }
  }
  return [...new Set(errors)];
}

function ownedFrozen(value: unknown): unknown {
  if (Array.isArray(value)) return Object.freeze(value.map(ownedFrozen));
  const candidate = record(value);
  if (!candidate) {
    if (value !== null && typeof value === "object") throw new Error("provenance value is not plain data");
    return value;
  }
  const owned = Object.create(null) as JsonRecord;
  for (const key of Object.keys(candidate)) owned[key] = ownedFrozen(candidate[key]);
  return Object.freeze(owned);
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  const candidate = record(value);
  if (candidate) return `{${Object.keys(candidate).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(candidate[key])}`).join(",")}}`;
  const rendered = JSON.stringify(value);
  if (rendered === undefined) throw new Error("provenance value is not canonical JSON");
  return rendered;
}

export function provenanceEventErrors(value: unknown): readonly string[] {
  const structural = structuralErrors(value);
  return structural.length > 0 ? structural : semanticErrors(value as ProvenanceEvent);
}

export function decodeProvenanceEvent(value: unknown): ProvenanceEvent | null {
  try {
    const owned = ownedFrozen(value);
    return provenanceEventErrors(owned).length === 0 ? owned as ProvenanceEvent : null;
  } catch {
    return null;
  }
}

export function isKnownProvenanceEvent(event: ProvenanceEvent): boolean {
  return Object.hasOwn(KNOWN_PROVENANCE_EVENT_ACTIVITIES, event.type);
}

export function canonicalProvenanceJson(value: unknown): string {
  const decoded = decodeProvenanceEvent(value);
  if (!decoded) throw new Error("invalid provenance event");
  return canonicalJson(decoded);
}
