"""Two-process, real persisted predecessor proof; synthetic plaintext fixture only."""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))
from tests.e2e.test_workflow_profile_matrix import (  # noqa: E402
    AUTHORITY,
    HEADERS,
    TestClient,
    WorkflowProfileMatrixEndToEndTests,
    development_plaintext_database_fixture,
)
from tests.service.test_research_intents import draft_request, accept_request  # noqa: E402

PROOF = REPO / "artifacts/evidence/W1.A09.T01.predecessor-before-02.json"
AFTER = REPO / "artifacts/evidence/W1.A09.T01.predecessor-after-02.json"
SEMANTIC_FILES = (
    "packages/contracts/workflow-profile/generated.ts",
    "packages/contracts/workflow-profile/workflow-profile.schema.json",
    "services/core-api/src/research_observatory_core/workflow_profile_contracts.py",
    "packages/contracts/workflow-profile/fixtures/approved-workflow-profile-catalog.v1.json",
    "packages/contracts/workflow-profile/fixtures/valid-project-workflow-selection.v1.json",
    "packages/contracts/workflow-profile/fixtures/valid-project-workflow-selection-change.v1.json",
    "packages/contracts/workflow-profile/fixtures/valid-workflow-stage-state.v1.json",
    "packages/contracts/workflow-profile/fixtures/valid-workflow-profile-migration.v1.json",
)


def source_hashes():
    return {name: hashlib.sha256((REPO / name).read_bytes()).hexdigest() for name in SEMANTIC_FILES}


def rows(root):
    with sqlite3.connect(f"{Path(root).as_uri()}/state/project.sqlite3?mode=ro", uri=True) as connection:
        return {
            table: [list(row) for row in connection.execute(f"SELECT * FROM {table} ORDER BY rowid")]
            for table in ("settings", "aggregate_revisions", "schema_migrations")
        }


def request(client, path, payload, **kwargs):
    response = client.post(path, json=payload, **kwargs)
    assert response.status_code == 200, (path, response.status_code, response.text)
    return response.json()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("mode", choices=("prepare", "reopen"))
    args = parser.parse_args()
    prepare = args.mode == "prepare"
    destination = PROOF if prepare else AFTER
    assert not destination.exists(), "Never overwrite a predecessor proof"
    before = None if prepare else json.loads(PROOF.read_text(encoding="utf-8"))
    if prepare:
        assert "RO-UI-ACADEMIC-MINIMAL-1.5" in (REPO / "design/ui-reference/APPROVAL.yaml").read_text()
        parent = Path(tempfile.mkdtemp(prefix="W1.A09.T01-predecessor-", dir=REPO / "artifacts/tmp"))
        root = str(parent / "preserved-project")
    else:
        root = before["root"]
        resolved = Path(root).resolve(strict=True)
        resolved.relative_to((REPO / "artifacts/tmp").resolve())
        assert resolved.parent.name.startswith("W1.A09.T01-predecessor-")
        assert source_hashes() == before["semanticRawHashes"], "Semantic generated bytes changed"
        assert rows(root) == before["immutableRows"], "Persisted predecessor changed before reopen"

    test = WorkflowProfileMatrixEndToEndTests()
    with development_plaintext_database_fixture():
        projects, intents, progress = test._stack()
        try:
            with TestClient(test._app(projects, intents, progress), base_url=f"http://{AUTHORITY}",
                            headers=HEADERS, client=("127.0.0.1", 50000)) as client:
                catalog, _ = test._catalog(client)
                if prepare:
                    created = request(client, "/projects", {
                        "parentDirectory": str(parent), "directoryName": "preserved-project",
                        "displayName": "Synthetic predecessor compatibility",
                        "primaryUseCase": "systematic-review",
                        "researchObjective": "Verify exact persisted workflow compatibility without researcher data.",
                    })
                    assert Path(created["root"]) == Path(root)
                request(client, "/projects/open", {"root": root})
                if prepare:
                    # Real 1.5 profile migration, prior intent revisions and explicit
                    # synthetic human acceptance precede the presentation replacement.
                    draft = draft_request(root, expected_revision=1)
                    preview = intents.preview(draft.to_impact_request())
                    draft = draft.model_copy(update={"impact_acknowledgement": preview.acknowledgement_token})
                    saved = intents.save_draft(draft, trace_id="3" * 32, idempotency_key="3" * 32)
                    accepted = intents.accept(
                        accept_request(saved).model_copy(update={"root": root}),
                        trace_id="4" * 32, idempotency_key="4" * 32,
                    )
                    assert accepted.status == "accepted" and accepted.revision == 3
                    state = request(client, "/projects/workflow-progress", {"root": root})
                    state = request(client, "/projects/workflow-progress/commands",
                                    test._command(root, state, "start"),
                                    headers={"Idempotency-Key": "1" * 32})
                    request(client, "/projects/workflow-progress/commands",
                            test._command(root, state, "open-supporting", stageKey=state["current"]["stageKey"],
                                          supportingPageContractId="application-settings.html"),
                            headers={"Idempotency-Key": "2" * 32})
                intent = request(client, "/projects/intent", {"root": root})
                assert intent["current"]["status"] == "accepted"
                projection = request(client, "/projects/workflow-progress", {"root": root})
                handoff = projection["supportingHandoff"]
                assert handoff["returnStageStateRevisionId"] == projection["current"]["stageStateRevisionId"]
                if not prepare:
                    assert catalog == before["catalog"]
                    assert intent == before["intent"], "Accepted intent/selection history changed"
                    assert projection == before["projection"], "Stage history or supporting return changed"
                request(client, "/projects/close", {"root": root})
        finally:
            projects.shutdown()
    immutable_rows = rows(root)
    if not prepare:
        assert immutable_rows == before["immutableRows"], "Reopen rewrote immutable rows or migrations"
    report = {
        "taskId": "W1.A09.T01", "mode": args.mode, "ok": True,
        "checkedAt": datetime.now(timezone.utc).isoformat(),
        "producerCommit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO, text=True).strip(),
        "helperSha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "boundary": "actual Core API/services and persisted SQLite; explicit synthetic plaintext fixture, not native/encrypted qualification",
        "root": root, "semanticRawHashes": source_hashes(), "catalog": catalog,
        "intent": intent, "projection": projection, "immutableRows": immutable_rows,
        "predecessorSha256": None if prepare else hashlib.sha256(PROOF.read_bytes()).hexdigest(),
    }
    with destination.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(json.dumps(report, indent=2) + "\n")
    print(json.dumps({"ok": True, "mode": args.mode, "proof": str(destination),
                      "immutableRows": {key: len(value) for key, value in immutable_rows.items()}}))


if __name__ == "__main__":
    main()
