// Generated by packages/contracts/domain/generate-compatibility.mjs. Do not edit by hand.
// Sources: compatibility schema/policy, authority and event catalogs, and release fixtures.

export type CompatibilityRole = "desktop" | "sidecar" | "server";
export type CompatibilityClassification = "additive" | "deprecation" | "breaking";
export type CompatibilityChangeKind =
  | "add-optional-field"
  | "widen-reader-type"
  | "deprecate-field"
  | "add-required-field"
  | "remove-field"
  | "rename-field"
  | "narrow-reader-type"
  | "add-closed-enum-member"
  | "add-event-type"
  | "change-event-payload"
  | "change-identity-format"
  | "repurpose-meaning";

export interface ContractRelease {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-domain-contract-release";
  readonly contractFamily: "research-observatory-domain";
  readonly contractVersion: string;
  readonly identityFormat: "legacy-project-uuidv4-bridge" | "canonical-uuidv7";
  readonly readerMode: "native" | "bridge-required";
  readonly writerMode: "native" | "denied";
  readonly schemaSetId: string;
}

export interface ComponentAdvertisement {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-domain-compatibility-advertisement";
  readonly role: CompatibilityRole;
  readonly componentVersion: string;
  readonly contractFamily: "research-observatory-domain";
  readonly supportedContractVersions: ReadonlyArray<string>;
  readonly supportedEventVersions: ReadonlyArray<string>;
  readonly schemaSetId: string;
}

export interface CompatibilityNegotiation {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-domain-compatibility-negotiation";
  readonly contractVersion: string;
  readonly eventVersion: string;
  readonly schemaSetId: string;
  readonly roles: ReadonlyArray<CompatibilityRole>;
  readonly diagnosticCode: "compatibility-negotiated";
}

export interface CompatibilityChangeAssessment {
  readonly classification: CompatibilityClassification | null;
  readonly allowed: boolean;
  readonly errors: ReadonlyArray<string>;
  readonly diagnosticCode: "compatibility-change-accepted" | "compatibility-change-denied";
}

export interface DomainEventEnvelope {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-domain-event-envelope";
  readonly eventType: string;
  readonly eventVersion: string;
  readonly payload: Readonly<JsonRecord>;
}

export interface CompatibilityAuditFact {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-domain-compatibility-audit";
  readonly reasonCode: "compatibility-unknown-event" | "compatibility-event-version-unsupported";
  readonly policyVersion: "1.0.0";
  readonly eventCatalogSha256: string;
}

export interface DomainEventAssessment {
  readonly allowed: boolean;
  readonly errors: ReadonlyArray<string>;
  readonly auditFact: CompatibilityAuditFact | null;
  readonly diagnosticCode: "compatibility-event-accepted" | "compatibility-event-denied";
}

type JsonRecord = Record<string, unknown>;

export const DOMAIN_COMPATIBILITY_SCHEMA_SHA256 = "296fa313639a1e39512624755894936f46516a1fa6f662bce41794ec748bea89";
export const DOMAIN_COMPATIBILITY_POLICY_SHA256 = "371a01c41b4869420ce51377f298895bcd04a86b1fb5f9f00a7f7c6d36b2a92c";
export const PRIOR_DOMAIN_RELEASE_SHA256 = "ae4e052b69143eef0615ffd138e013063631dc8ca3869847d229b560d8e1110f";
export const CURRENT_DOMAIN_RELEASE_SHA256 = "bc299d6f2890717f16be9bb1f81e10470a606fd58e0dbf8584628a2a075f8418";
export const DOMAIN_COMPATIBILITY_AUTHORITY_SHA256 = "f434d7bad975f75041693c1752f173ce01524a0391ac119d8d8ba1baf8da440b";
export const DOMAIN_EVENT_CATALOG_SHA256 = "909191221f3ff762b1129b3777d8347371c011a62c0bef13a89d1a249fa2a697";

const POLICY = deepFreeze(JSON.parse(String.raw`{"schemaVersion":"1.0","documentType":"research-observatory-domain-compatibility-policy","policyVersion":"1.0.0","contractFamily":"research-observatory-domain","priorContractVersion":"0.1.0","currentContractVersion":"1.0.0","changeRules":[{"changeKind":"add-optional-field","classification":"additive","requirements":[]},{"changeKind":"widen-reader-type","classification":"additive","requirements":[]},{"changeKind":"deprecate-field","classification":"deprecation","requirements":["deprecation-window"]},{"changeKind":"add-required-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"remove-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"rename-field","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"narrow-reader-type","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"add-closed-enum-member","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"add-event-type","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"change-event-payload","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"change-identity-format","classification":"breaking","requirements":["adr","migration"]},{"changeKind":"repurpose-meaning","classification":"breaking","requirements":["adr","migration"]}],"eventPolicy":{"envelopeVersioned":true,"unknownEvent":"deny-and-audit","payloadUnknownFields":"reject","supportedVersions":["0.1.0","1.0.0"]},"negotiation":{"roles":["desktop","sidecar","server"],"selection":"highest-exact-common","schemaSet":"exact-match","noOverlap":"deny"},"bridges":[{"id":"legacy-project-uuidv4-to-canonical-uuidv7","fromVersion":"0.1.0","toVersion":"1.0.0","adrId":"ADR-0013","strategy":"reader-bridge","sourceRetention":"preserved","testFixture":"packages/contracts/project/fixtures/valid-project-manifest.v1.json"}]}`) as JsonRecord);
const PRIOR_RELEASE = deepFreeze(JSON.parse(String.raw`{"schemaVersion":"1.0","documentType":"research-observatory-domain-contract-release","contractFamily":"research-observatory-domain","contractVersion":"0.1.0","identityFormat":"legacy-project-uuidv4-bridge","readerMode":"bridge-required","writerMode":"denied","schemaSetId":"sha256:1f9604bf780bc9182ad09b38119929c3af17276ed35599b79706e331c37ba8a9"}`) as unknown as ContractRelease);
const CURRENT_RELEASE = deepFreeze(JSON.parse(String.raw`{"schemaVersion":"1.0","documentType":"research-observatory-domain-contract-release","contractFamily":"research-observatory-domain","contractVersion":"1.0.0","identityFormat":"canonical-uuidv7","readerMode":"native","writerMode":"native","schemaSetId":"sha256:60cd81eb55668ffc279d7e904d7163a5b87110f81b120e9ff1a6b23e4f13b59e"}`) as unknown as ContractRelease);
const AUTHORITY_CATALOG = deepFreeze(JSON.parse(String.raw`{"schemaVersion":"1.0","documentType":"research-observatory-domain-compatibility-authority-catalog","catalogVersion":"1.0.0","authorities":[{"id":"authority.uuidv4-project-to-uuidv7-domain","changeKind":"change-identity-format","fromVersion":"0.1.0","toVersion":"1.0.0","applicableTask":"CAP-03.S01.T03","adr":{"id":"ADR-0013","status":"Accepted","decisionScope":"Portable aggregate and revision identity, UUID minting authority, common scholarly value objects, and deterministic Python/TypeScript generation from the core domain schema.","path":"docs/adr/ADR-0013-adopt-uuidv7-aggregate-identities-and-schema-generated-domain-contracts.md","sha256":"3f930f56a3a570d47c036a34c53391c8616db6dd81c0a729c2b3e665dfc8d9dc"},"migration":{"id":"legacy-project-uuidv4-to-canonical-uuidv7","strategy":"reader-bridge","sourceRetention":"preserved","fixturePath":"packages/contracts/project/fixtures/valid-project-manifest.v1.json","fixtureSha256":"f4bc0bd218fa8f42d71861c4bea539cef6d80d8031eac21ce8626e06f71e13e0","compatibilityTestPath":"packages/contracts/domain/compatibility.test.ts","compatibilityTestSha256":"1e2e7eae0f8fb185904bf27822509822b11c1f4d7cef75f1f271a6dda9b65d2a"}}]}`) as JsonRecord);
const EVENT_CATALOG = deepFreeze(JSON.parse(String.raw`{"schemaVersion":"1.0","documentType":"research-observatory-domain-event-catalog","catalogVersion":"1.0.0","payloadSchemaId":"sha256:77d82e9fe47c51c7b4bc70c38c203497a0323081a00eb0a0ac899c5849bcb3a3","events":[{"eventType":"domain.lifecycle-transition","eventVersion":"0.1.0","payloadDocumentType":"research-observatory-domain-lifecycle-transition","payloadRequiredFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"],"payloadAllowedFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"]},{"eventType":"domain.lifecycle-transition","eventVersion":"1.0.0","payloadDocumentType":"research-observatory-domain-lifecycle-transition","payloadRequiredFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"],"payloadAllowedFields":["schemaVersion","documentType","profileVersion","subjectKind","aggregateId","fromState","toState","command","transitionKind","priorRevision","revision","actor","reason","occurredAt","idempotencyKey"]}]}`) as JsonRecord);
const SAFE_SEMVER = /^(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])$/;
const PORTABLE_ID = /^[a-z][a-z0-9]*(?:[.:_-][a-z0-9]+){0,11}$/;
const ADR_ID = /^ADR-[0-9]{4}$/;
const SHA256_ID = /^sha256:[0-9a-f]{64}$/;
const ROLES: ReadonlyArray<CompatibilityRole> = Object.freeze(["desktop", "sidecar", "server"]);
const CHANGE_KINDS: ReadonlyArray<CompatibilityChangeKind> = Object.freeze([
  "add-optional-field",
  "widen-reader-type",
  "deprecate-field",
  "add-required-field",
  "remove-field",
  "rename-field",
  "narrow-reader-type",
  "add-closed-enum-member",
  "add-event-type",
  "change-event-payload",
  "change-identity-format",
  "repurpose-meaning",
]);

export class DomainCompatibilityProblem extends Error {
  readonly codes: ReadonlyArray<string>;

  constructor(codes: ReadonlyArray<string>) {
    const owned = Object.freeze([...codes]);
    super(owned[0] ?? "compatibility-denied");
    this.name = "DomainCompatibilityProblem";
    this.codes = owned;
  }
}

function record(value: unknown): JsonRecord | null {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? (value as JsonRecord) : null;
}

function deepFreeze<T>(value: T): T {
  if (typeof value === "object" && value !== null) {
    for (const item of Object.values(value)) deepFreeze(item);
    Object.freeze(value);
  }
  return value;
}

function exactKeys(value: JsonRecord, keys: ReadonlyArray<string>): boolean {
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  return actual.length === expected.length && actual.every((key, index) => key === expected[index]);
}

function isSemver(value: unknown): value is string {
  return typeof value === "string" && SAFE_SEMVER.test(value);
}

function semverParts(value: string): readonly [number, number, number] {
  const parts = value.split(".").map(Number);
  return [parts[0]!, parts[1]!, parts[2]!];
}

function compareSemver(left: string, right: string): number {
  const l = semverParts(left);
  const r = semverParts(right);
  for (let index = 0; index < 3; index += 1) {
    if (l[index] !== r[index]) return l[index]! < r[index]! ? -1 : 1;
  }
  return 0;
}

function orderedVersions(value: unknown): value is ReadonlyArray<string> {
  return Array.isArray(value) && value.length > 0 && value.length <= 8 && value.every(isSemver) &&
    value.every((item, index) => index === 0 || compareSemver(value[index - 1]!, item) < 0);
}

function validRelativeFixture(value: unknown): value is string {
  return typeof value === "string" && value.length > 0 && value.length <= 240 &&
    /^[A-Za-z0-9._/-]+$/.test(value) && !value.startsWith("/") && !/^[A-Za-z]:/.test(value) &&
    !value.split("/").includes("..");
}

function policyRules(): ReadonlyArray<JsonRecord> {
  return POLICY.changeRules as ReadonlyArray<JsonRecord>;
}

export function domainCompatibilityPolicy(): Readonly<JsonRecord> {
  return POLICY;
}

export function breakingAuthorityCatalog(): Readonly<JsonRecord> {
  return AUTHORITY_CATALOG;
}

export function domainEventCatalog(): Readonly<JsonRecord> {
  return EVENT_CATALOG;
}

export function breakingAuthorityCatalogErrors(value: unknown): ReadonlyArray<string> {
  const catalog = record(value);
  if (!catalog || !exactKeys(catalog, ["schemaVersion", "documentType", "catalogVersion", "authorities"]) ||
      catalog.schemaVersion !== "1.0" || catalog.documentType !== "research-observatory-domain-compatibility-authority-catalog" ||
      catalog.catalogVersion !== "1.0.0" || !Array.isArray(catalog.authorities) || catalog.authorities.length !== 1) {
    return Object.freeze(["compatibility-authority-catalog-invalid"]);
  }
  const candidate = record(catalog.authorities[0]);
  const expected = (AUTHORITY_CATALOG.authorities as ReadonlyArray<JsonRecord>)[0]!;
  if (!candidate || candidate.id !== expected.id) return Object.freeze(["compatibility-breaking-authority-unknown"]);
  const candidateAdr = record(candidate.adr);
  const expectedAdr = expected.adr as JsonRecord;
  if (!candidateAdr || candidateAdr.status !== "Accepted") return Object.freeze(["compatibility-breaking-authority-status-not-accepted"]);
  if (candidateAdr.decisionScope !== expectedAdr.decisionScope || candidate.applicableTask !== expected.applicableTask) {
    return Object.freeze(["compatibility-breaking-authority-scope-mismatch"]);
  }
  const candidateMigration = record(candidate.migration);
  const expectedMigration = expected.migration as JsonRecord;
  if (!candidateMigration || candidateAdr.sha256 !== expectedAdr.sha256 ||
      candidateMigration.fixtureSha256 !== expectedMigration.fixtureSha256 ||
      candidateMigration.compatibilityTestSha256 !== expectedMigration.compatibilityTestSha256) {
    return Object.freeze(["compatibility-breaking-authority-evidence-mismatch"]);
  }
  if (JSON.stringify(candidate) !== JSON.stringify(expected)) return Object.freeze(["compatibility-breaking-authority-mismatch"]);
  return Object.freeze([]);
}

export function contractReleases(): ReadonlyArray<ContractRelease> {
  return Object.freeze([PRIOR_RELEASE, CURRENT_RELEASE]);
}

export function readCompatibility(version: unknown): Readonly<JsonRecord> {
  if (version === CURRENT_RELEASE.contractVersion) {
    return deepFreeze({ mode: "native", contractVersion: version, bridgeId: null, diagnosticCode: "compatibility-read-native" });
  }
  if (version === PRIOR_RELEASE.contractVersion) {
    return deepFreeze({
      mode: "bridge-required",
      contractVersion: version,
      bridgeId: "legacy-project-uuidv4-to-canonical-uuidv7",
      diagnosticCode: "compatibility-read-bridge-required",
    });
  }
  return deepFreeze({ mode: "unsupported", contractVersion: null, bridgeId: null, diagnosticCode: "compatibility-read-unsupported" });
}

function basicProposal(value: unknown): JsonRecord | null {
  const proposal = record(value);
  const keys = ["schemaVersion", "documentType", "fromVersion", "toVersion", "changeKind", "artifactId", "adrId", "authorityId", "migration", "deprecation"];
  if (!proposal || !exactKeys(proposal, keys)) return null;
  if (proposal.schemaVersion !== "1.0" || proposal.documentType !== "research-observatory-domain-change-proposal") return null;
  if (!isSemver(proposal.fromVersion) || !isSemver(proposal.toVersion) || compareSemver(proposal.fromVersion, proposal.toVersion) >= 0) return null;
  if (!CHANGE_KINDS.includes(proposal.changeKind as CompatibilityChangeKind)) return null;
  if (typeof proposal.artifactId !== "string" || proposal.artifactId.length > 128 || !PORTABLE_ID.test(proposal.artifactId)) return null;
  if (proposal.adrId !== null && (typeof proposal.adrId !== "string" || !ADR_ID.test(proposal.adrId))) return null;
  if (proposal.authorityId !== null && (typeof proposal.authorityId !== "string" || !PORTABLE_ID.test(proposal.authorityId))) return null;
  return proposal;
}

function validMigration(value: unknown, fromVersion: string, toVersion: string): string | null {
  const migration = record(value);
  const keys = ["id", "fromVersion", "toVersion", "strategy", "sourceRetention", "testFixture"];
  if (!migration || !exactKeys(migration, keys)) return "compatibility-breaking-migration-required";
  if (typeof migration.id !== "string" || !PORTABLE_ID.test(migration.id) ||
      !["reader-bridge", "verified-copy-on-write"].includes(String(migration.strategy)) ||
      migration.sourceRetention !== "preserved" || !validRelativeFixture(migration.testFixture)) {
    return "compatibility-breaking-migration-required";
  }
  if (migration.fromVersion !== fromVersion || migration.toVersion !== toVersion) return "compatibility-migration-version-mismatch";
  return null;
}

function validDeprecation(value: unknown, toVersion: string): string | null {
  const deprecation = record(value);
  if (!deprecation || !exactKeys(deprecation, ["since", "removalNotBefore", "replacement"])) return "compatibility-deprecation-window-required";
  if (deprecation.since !== toVersion || !isSemver(deprecation.removalNotBefore) || compareSemver(toVersion, deprecation.removalNotBefore) >= 0 ||
      typeof deprecation.replacement !== "string" || !PORTABLE_ID.test(deprecation.replacement)) {
    return "compatibility-deprecation-window-invalid";
  }
  return null;
}

export function assessDomainChange(value: unknown): CompatibilityChangeAssessment {
  const proposal = basicProposal(value);
  if (!proposal) return deepFreeze({ classification: null, allowed: false, errors: ["compatibility-change-proposal-invalid"], diagnosticCode: "compatibility-change-denied" });
  const rule = policyRules().find((item) => item.changeKind === proposal.changeKind)!;
  const classification = rule.classification as CompatibilityClassification;
  const errors: string[] = [];
  const fromVersion = proposal.fromVersion as string;
  const toVersion = proposal.toVersion as string;
  const [fromMajor] = semverParts(fromVersion);
  const [toMajor] = semverParts(toVersion);
  if (classification === "additive") {
    if (fromMajor !== toMajor) errors.push("compatibility-additive-major-change");
    if (proposal.adrId !== null || proposal.authorityId !== null || proposal.migration !== null || proposal.deprecation !== null) errors.push("compatibility-additive-unexpected-authority");
  } else if (classification === "deprecation") {
    if (fromMajor !== toMajor) errors.push("compatibility-deprecation-major-change");
    const error = validDeprecation(proposal.deprecation, toVersion);
    if (error) errors.push(error);
    if (proposal.adrId !== null || proposal.authorityId !== null || proposal.migration !== null) errors.push("compatibility-deprecation-unexpected-authority");
  } else {
    if (toMajor <= fromMajor) errors.push("compatibility-breaking-major-required");
    if (typeof proposal.adrId !== "string" || !ADR_ID.test(proposal.adrId)) errors.push("compatibility-breaking-adr-required");
    const error = validMigration(proposal.migration, fromVersion, toVersion);
    if (error) errors.push(error);
    const authority = (AUTHORITY_CATALOG.authorities as ReadonlyArray<JsonRecord>).find((item) => item.id === proposal.authorityId);
    if (proposal.authorityId === null) {
      errors.push("compatibility-breaking-authority-required");
    } else if (!authority) {
      errors.push("compatibility-breaking-authority-unknown");
    } else {
      const adr = authority.adr as JsonRecord;
      const migration = authority.migration as JsonRecord;
      const proposedMigration = record(proposal.migration);
      if (authority.changeKind !== proposal.changeKind || authority.fromVersion !== fromVersion || authority.toVersion !== toVersion ||
          adr.id !== proposal.adrId || !proposedMigration || migration.id !== proposedMigration.id ||
          migration.strategy !== proposedMigration.strategy || migration.sourceRetention !== proposedMigration.sourceRetention ||
          migration.fixturePath !== proposedMigration.testFixture) {
        errors.push("compatibility-breaking-authority-mismatch");
      }
    }
    if (proposal.deprecation !== null) errors.push("compatibility-breaking-unexpected-deprecation");
  }
  return deepFreeze({
    classification,
    allowed: errors.length === 0,
    errors,
    diagnosticCode: errors.length === 0 ? "compatibility-change-accepted" : "compatibility-change-denied",
  });
}

function auditEventDenial(reasonCode: CompatibilityAuditFact["reasonCode"], publishAudit: (fact: CompatibilityAuditFact) => void): DomainEventAssessment {
  const fact = deepFreeze({
    schemaVersion: "1.0" as const,
    documentType: "research-observatory-domain-compatibility-audit" as const,
    reasonCode,
    policyVersion: "1.0.0" as const,
    eventCatalogSha256: `sha256:${DOMAIN_EVENT_CATALOG_SHA256}`,
  });
  try {
    if (typeof publishAudit !== "function") throw new Error("publisher missing");
    publishAudit(fact);
  } catch {
    throw new DomainCompatibilityProblem(["compatibility-audit-publication-failed"]);
  }
  return deepFreeze({ allowed: false, errors: [reasonCode], auditFact: fact, diagnosticCode: "compatibility-event-denied" });
}

export function assessDomainEvent(value: unknown, publishAudit: (fact: CompatibilityAuditFact) => void): DomainEventAssessment {
  const envelope = record(value);
  if (!envelope || !exactKeys(envelope, ["schemaVersion", "documentType", "eventType", "eventVersion", "payload"]) ||
      envelope.schemaVersion !== "1.0" || envelope.documentType !== "research-observatory-domain-event-envelope" ||
      typeof envelope.eventType !== "string" || !PORTABLE_ID.test(envelope.eventType) || !isSemver(envelope.eventVersion) || !record(envelope.payload)) {
    return deepFreeze({ allowed: false, errors: ["compatibility-event-envelope-invalid"], auditFact: null, diagnosticCode: "compatibility-event-denied" });
  }
  const catalog = EVENT_CATALOG.events as ReadonlyArray<JsonRecord>;
  const supportedVersions = new Set(catalog.map((item) => item.eventVersion));
  if (!supportedVersions.has(envelope.eventVersion)) return auditEventDenial("compatibility-event-version-unsupported", publishAudit);
  const event = catalog.find((item) => item.eventType === envelope.eventType && item.eventVersion === envelope.eventVersion);
  if (!event) return auditEventDenial("compatibility-unknown-event", publishAudit);
  const payload = envelope.payload as JsonRecord;
  const required = event.payloadRequiredFields as ReadonlyArray<string>;
  const allowed = event.payloadAllowedFields as ReadonlyArray<string>;
  if (Object.keys(payload).some((key) => !allowed.includes(key))) {
    return deepFreeze({ allowed: false, errors: ["compatibility-event-payload-unknown-field"], auditFact: null, diagnosticCode: "compatibility-event-denied" });
  }
  if (!required.every((key) => Object.hasOwn(payload, key)) || payload.schemaVersion !== "1.0" ||
      payload.documentType !== event.payloadDocumentType) {
    return deepFreeze({ allowed: false, errors: ["compatibility-event-payload-invalid"], auditFact: null, diagnosticCode: "compatibility-event-denied" });
  }
  return deepFreeze({ allowed: true, errors: [], auditFact: null, diagnosticCode: "compatibility-event-accepted" });
}

function validAdvertisement(value: unknown): value is ComponentAdvertisement {
  const item = record(value);
  const keys = ["schemaVersion", "documentType", "role", "componentVersion", "contractFamily", "supportedContractVersions", "supportedEventVersions", "schemaSetId"];
  return item !== null && exactKeys(item, keys) && item.schemaVersion === "1.0" &&
    item.documentType === "research-observatory-domain-compatibility-advertisement" &&
    ROLES.includes(item.role as CompatibilityRole) && isSemver(item.componentVersion) &&
    item.contractFamily === "research-observatory-domain" && orderedVersions(item.supportedContractVersions) &&
    orderedVersions(item.supportedEventVersions) && typeof item.schemaSetId === "string" && SHA256_ID.test(item.schemaSetId);
}

function commonHighest(advertisements: ReadonlyArray<ComponentAdvertisement>, key: "supportedContractVersions" | "supportedEventVersions"): string | null {
  const common = advertisements[0]![key].filter((version) => advertisements.every((item) => item[key].includes(version)));
  return common.length === 0 ? null : common.reduce((highest, item) => compareSemver(highest, item) < 0 ? item : highest);
}

export function domainCompatibilityNegotiationErrors(value: unknown): ReadonlyArray<string> {
  if (!Array.isArray(value) || value.length < 2 || value.length > 3 || !value.every(validAdvertisement)) return Object.freeze(["compatibility-advertisement-invalid"]);
  const items = value as ReadonlyArray<ComponentAdvertisement>;
  const roles = items.map((item) => item.role);
  if (new Set(roles).size !== roles.length) return Object.freeze(["compatibility-role-duplicate"]);
  if (!roles.includes("desktop") || !roles.includes("sidecar")) return Object.freeze(["compatibility-required-role-missing"]);
  if (new Set(items.map((item) => item.contractFamily)).size !== 1) return Object.freeze(["compatibility-family-mismatch"]);
  if (new Set(items.map((item) => item.schemaSetId)).size !== 1) return Object.freeze(["compatibility-schema-set-mismatch"]);
  if (commonHighest(items, "supportedContractVersions") === null) return Object.freeze(["compatibility-contract-version-no-overlap"]);
  if (commonHighest(items, "supportedEventVersions") === null) return Object.freeze(["compatibility-event-version-no-overlap"]);
  return Object.freeze([]);
}

export function negotiateDomainCompatibility(value: unknown): CompatibilityNegotiation {
  const errors = domainCompatibilityNegotiationErrors(value);
  if (errors.length > 0) throw new DomainCompatibilityProblem(errors);
  const items = value as ReadonlyArray<ComponentAdvertisement>;
  const contractVersion = commonHighest(items, "supportedContractVersions")!;
  const eventVersion = commonHighest(items, "supportedEventVersions")!;
  const roles = ROLES.filter((role) => items.some((item) => item.role === role));
  return deepFreeze({
    schemaVersion: "1.0",
    documentType: "research-observatory-domain-compatibility-negotiation",
    contractVersion,
    eventVersion,
    schemaSetId: items[0]!.schemaSetId,
    roles,
    diagnosticCode: "compatibility-negotiated",
  });
}
