// Generated by packages/contracts/domain/generate.mjs. Do not edit by hand.
// Source: packages/contracts/domain/domain-core.schema.json

export type AggregateId = string;

export type RevisionId = string;

export type RevisionNumber = number;

export type ContractVersion = string;

export type UtcInstant = string;

export type AggregateKind = "project" | "record" | "document" | "evidence" | "decision" | "workflow" | "ontology" | "graph" | "opportunity" | "monitoring-event";

export type KnowledgeStatus = "observed" | "extracted" | "inferred" | "verified" | "disputed" | "adjudicated" | "stale" | "unknown" | "not-reported" | "not-applicable" | "ambiguous" | "unavailable";

export interface SourceAnchor {
  readonly kind: "record-field" | "document-element" | "page" | "table-cell" | "figure" | "external-identifier";
  readonly value: string;
}

export interface SourceReference {
  readonly sourceAggregateId: AggregateId;
  readonly sourceRevision: RevisionNumber;
  readonly anchor: SourceAnchor;
  readonly sourceLabel: string;
}

export type AlternativeDisposition = "candidate" | "disputed" | "accepted" | "rejected";

export interface TextAlternative {
  readonly value: string;
  readonly disposition: AlternativeDisposition;
  readonly sourceReference: SourceReference;
}

export interface ObservedText {
  readonly observed: string;
  readonly normalized: string | null;
  readonly alternatives: ReadonlyArray<TextAlternative>;
}

export interface QuantifiedConfidence {
  readonly kind: "quantified";
  readonly value: number;
  readonly basis: string;
}

export interface QualitativeConfidence {
  readonly kind: "qualitative";
  readonly value: "low" | "moderate" | "high" | "mixed";
  readonly basis: string;
}

export interface UnknownConfidence {
  readonly kind: "unknown";
}

export interface NotApplicableConfidence {
  readonly kind: "not-applicable";
}

export type Confidence = QuantifiedConfidence | QualitativeConfidence | UnknownConfidence | NotApplicableConfidence;

export type RightsUse = "view" | "extract" | "analyze" | "model" | "share" | "export";

export interface AllowedRights {
  readonly status: "allowed";
  readonly allowedUses: ReadonlyArray<RightsUse>;
  readonly deniedUses: ReadonlyArray<RightsUse>;
  readonly sourceReferences: ReadonlyArray<SourceReference>;
}

export interface DeniedRights {
  readonly status: "denied";
  readonly allowedUses: ReadonlyArray<RightsUse>;
  readonly deniedUses: ReadonlyArray<RightsUse>;
  readonly sourceReferences: ReadonlyArray<SourceReference>;
}

export interface UnknownRights {
  readonly status: "unknown";
  readonly allowedUses: ReadonlyArray<RightsUse>;
  readonly deniedUses: ReadonlyArray<RightsUse>;
  readonly sourceReferences: ReadonlyArray<SourceReference>;
}

export interface NotApplicableRights {
  readonly status: "not-applicable";
  readonly allowedUses: ReadonlyArray<RightsUse>;
  readonly deniedUses: ReadonlyArray<RightsUse>;
  readonly sourceReferences: ReadonlyArray<SourceReference>;
}

export type RightsDecision = AllowedRights | DeniedRights | UnknownRights | NotApplicableRights;

export interface ExternalIdentifier {
  readonly scheme: "doi" | "pmid" | "isbn" | "issn" | "arxiv" | "handle" | "orcid" | "ror" | "url" | "other";
  readonly observedValue: string;
  readonly normalizedValue: string | null;
  readonly verificationState: "unverified" | "verified" | "disputed" | "invalid";
  readonly sourceReference: SourceReference;
}

export interface CoreAggregate {
  readonly schemaVersion: "1.0";
  readonly documentType: "research-observatory-core-aggregate";
  readonly contractVersion: ContractVersion;
  readonly aggregateKind: AggregateKind;
  readonly aggregateId: AggregateId;
  readonly revisionId: RevisionId;
  readonly revision: RevisionNumber;
  readonly createdAt: UtcInstant;
  readonly modifiedAt: UtcInstant;
  readonly displayLabel: ObservedText;
  readonly status: KnowledgeStatus;
  readonly confidence: Confidence;
  readonly rights: RightsDecision;
  readonly sourceReferences: ReadonlyArray<SourceReference>;
  readonly externalIdentifiers: ReadonlyArray<ExternalIdentifier>;
}

export const CORE_DOMAIN_SCHEMA_SHA256 = "0c1f7b5522949f35cc23deddab129fcd924cbe7c5b4294beda757137110569e4";

const CORE_DOMAIN_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://research-observatory.local/contracts/domain/domain-core.schema.json",
  "title": "Research Observatory portable core aggregate",
  "description": "Framework-neutral identity, revision, source, epistemic, confidence, rights, and principal-aggregate envelope contract.",
  "x-research-observatory-semanticRules": [
    {
      "ruleId": "modified-at-not-before-created-at",
      "operator": "instant-not-after",
      "leftPointer": "/createdAt",
      "rightPointer": "/modifiedAt"
    },
    {
      "ruleId": "revision-identity-distinct",
      "operator": "not-equal",
      "leftPointer": "/aggregateId",
      "rightPointer": "/revisionId"
    },
    {
      "ruleId": "rights-allowed-and-denied-disjoint",
      "operator": "set-disjoint",
      "leftPointer": "/rights/allowedUses",
      "rightPointer": "/rights/deniedUses"
    }
  ],
  "$ref": "#/$defs/CoreAggregate",
  "$defs": {
    "AggregateId": {
      "type": "string",
      "description": "Canonical lower-case RFC 9562 UUIDv7.",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "RevisionId": {
      "type": "string",
      "description": "Immutable revision identity represented as canonical lower-case UUIDv7.",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "RevisionNumber": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    },
    "ContractVersion": {
      "type": "string",
      "pattern": "^(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])\\.(0|[1-9][0-9]{0,14}|[1-8][0-9]{15}|900719925474099[01])$"
    },
    "UtcInstant": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,3})?Z$"
    },
    "AggregateKind": {
      "type": "string",
      "enum": [
        "project",
        "record",
        "document",
        "evidence",
        "decision",
        "workflow",
        "ontology",
        "graph",
        "opportunity",
        "monitoring-event"
      ]
    },
    "KnowledgeStatus": {
      "type": "string",
      "enum": [
        "observed",
        "extracted",
        "inferred",
        "verified",
        "disputed",
        "adjudicated",
        "stale",
        "unknown",
        "not-reported",
        "not-applicable",
        "ambiguous",
        "unavailable"
      ]
    },
    "SourceAnchor": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value"
      ],
      "properties": {
        "kind": {
          "enum": [
            "record-field",
            "document-element",
            "page",
            "table-cell",
            "figure",
            "external-identifier"
          ]
        },
        "value": {
          "type": "string",
          "pattern": "^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$"
        }
      }
    },
    "SourceReference": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "sourceAggregateId",
        "sourceRevision",
        "anchor",
        "sourceLabel"
      ],
      "properties": {
        "sourceAggregateId": {
          "$ref": "#/$defs/AggregateId"
        },
        "sourceRevision": {
          "$ref": "#/$defs/RevisionNumber"
        },
        "anchor": {
          "$ref": "#/$defs/SourceAnchor"
        },
        "sourceLabel": {
          "type": "string",
          "minLength": 1,
          "maxLength": 240,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        }
      }
    },
    "AlternativeDisposition": {
      "type": "string",
      "enum": [
        "candidate",
        "disputed",
        "accepted",
        "rejected"
      ]
    },
    "TextAlternative": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "value",
        "disposition",
        "sourceReference"
      ],
      "properties": {
        "value": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        },
        "disposition": {
          "$ref": "#/$defs/AlternativeDisposition"
        },
        "sourceReference": {
          "$ref": "#/$defs/SourceReference"
        }
      }
    },
    "ObservedText": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "observed",
        "normalized",
        "alternatives"
      ],
      "properties": {
        "observed": {
          "type": "string",
          "minLength": 1,
          "maxLength": 4096,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        },
        "normalized": {
          "oneOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 4096,
              "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
            },
            {
              "type": "null"
            }
          ]
        },
        "alternatives": {
          "type": "array",
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/TextAlternative"
          }
        }
      }
    },
    "QuantifiedConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value",
        "basis"
      ],
      "properties": {
        "kind": {
          "const": "quantified"
        },
        "value": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        },
        "basis": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        }
      }
    },
    "QualitativeConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value",
        "basis"
      ],
      "properties": {
        "kind": {
          "const": "qualitative"
        },
        "value": {
          "enum": [
            "low",
            "moderate",
            "high",
            "mixed"
          ]
        },
        "basis": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        }
      }
    },
    "UnknownConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "const": "unknown"
        }
      }
    },
    "NotApplicableConfidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "const": "not-applicable"
        }
      }
    },
    "Confidence": {
      "oneOf": [
        {
          "$ref": "#/$defs/QuantifiedConfidence"
        },
        {
          "$ref": "#/$defs/QualitativeConfidence"
        },
        {
          "$ref": "#/$defs/UnknownConfidence"
        },
        {
          "$ref": "#/$defs/NotApplicableConfidence"
        }
      ]
    },
    "RightsUse": {
      "type": "string",
      "enum": [
        "view",
        "extract",
        "analyze",
        "model",
        "share",
        "export"
      ]
    },
    "AllowedRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "allowed"
        },
        "allowedUses": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "DeniedRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "denied"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "minItems": 1,
          "maxItems": 6,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "minItems": 1,
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "UnknownRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "unknown"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 32,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "NotApplicableRights": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "status",
        "allowedUses",
        "deniedUses",
        "sourceReferences"
      ],
      "properties": {
        "status": {
          "const": "not-applicable"
        },
        "allowedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "deniedUses": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/RightsUse"
          }
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 0,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        }
      }
    },
    "RightsDecision": {
      "oneOf": [
        {
          "$ref": "#/$defs/AllowedRights"
        },
        {
          "$ref": "#/$defs/DeniedRights"
        },
        {
          "$ref": "#/$defs/UnknownRights"
        },
        {
          "$ref": "#/$defs/NotApplicableRights"
        }
      ]
    },
    "ExternalIdentifier": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "scheme",
        "observedValue",
        "normalizedValue",
        "verificationState",
        "sourceReference"
      ],
      "properties": {
        "scheme": {
          "enum": [
            "doi",
            "pmid",
            "isbn",
            "issn",
            "arxiv",
            "handle",
            "orcid",
            "ror",
            "url",
            "other"
          ]
        },
        "observedValue": {
          "type": "string",
          "minLength": 1,
          "maxLength": 512,
          "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
        },
        "normalizedValue": {
          "oneOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 512,
              "pattern": "^[^\\u0000-\\u001f\\u007f]+$"
            },
            {
              "type": "null"
            }
          ]
        },
        "verificationState": {
          "enum": [
            "unverified",
            "verified",
            "disputed",
            "invalid"
          ]
        },
        "sourceReference": {
          "$ref": "#/$defs/SourceReference"
        }
      }
    },
    "CoreAggregate": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "schemaVersion",
        "documentType",
        "contractVersion",
        "aggregateKind",
        "aggregateId",
        "revisionId",
        "revision",
        "createdAt",
        "modifiedAt",
        "displayLabel",
        "status",
        "confidence",
        "rights",
        "sourceReferences",
        "externalIdentifiers"
      ],
      "properties": {
        "schemaVersion": {
          "const": "1.0"
        },
        "documentType": {
          "const": "research-observatory-core-aggregate"
        },
        "contractVersion": {
          "$ref": "#/$defs/ContractVersion"
        },
        "aggregateKind": {
          "$ref": "#/$defs/AggregateKind"
        },
        "aggregateId": {
          "$ref": "#/$defs/AggregateId"
        },
        "revisionId": {
          "$ref": "#/$defs/RevisionId"
        },
        "revision": {
          "$ref": "#/$defs/RevisionNumber"
        },
        "createdAt": {
          "$ref": "#/$defs/UtcInstant"
        },
        "modifiedAt": {
          "$ref": "#/$defs/UtcInstant"
        },
        "displayLabel": {
          "$ref": "#/$defs/ObservedText"
        },
        "status": {
          "$ref": "#/$defs/KnowledgeStatus"
        },
        "confidence": {
          "$ref": "#/$defs/Confidence"
        },
        "rights": {
          "$ref": "#/$defs/RightsDecision"
        },
        "sourceReferences": {
          "type": "array",
          "maxItems": 256,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/SourceReference"
          }
        },
        "externalIdentifiers": {
          "type": "array",
          "maxItems": 128,
          "uniqueItems": true,
          "items": {
            "$ref": "#/$defs/ExternalIdentifier"
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "status": {
                "const": "disputed"
              }
            },
            "required": [
              "status"
            ]
          },
          "then": {
            "properties": {
              "displayLabel": {
                "type": "object",
                "properties": {
                  "alternatives": {
                    "type": "array",
                    "contains": {
                      "type": "object",
                      "properties": {
                        "disposition": {
                          "const": "disputed"
                        }
                      },
                      "required": [
                        "disposition"
                      ]
                    },
                    "minContains": 1
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
} as const;
const UUID_V7 = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

type JsonRecord = Readonly<Record<string, unknown>>;

function record(value: unknown): JsonRecord | null {
  return value !== null && typeof value === "object" && !Array.isArray(value) ? value as JsonRecord : null;
}

function deepEqual(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) return true;
  if (Array.isArray(left) || Array.isArray(right)) {
    return Array.isArray(left) && Array.isArray(right) && left.length === right.length
      && left.every((item, index) => deepEqual(item, right[index]));
  }
  const leftRecord = record(left);
  const rightRecord = record(right);
  if (!leftRecord || !rightRecord) return false;
  const leftKeys = Object.keys(leftRecord).sort();
  const rightKeys = Object.keys(rightRecord).sort();
  return leftKeys.length === rightKeys.length
    && leftKeys.every((key, index) => key === rightKeys[index] && deepEqual(leftRecord[key], rightRecord[key]));
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  const candidate = record(value);
  if (candidate) return `{${Object.keys(candidate).sort().map((key) => `${JSON.stringify(key)}:${stableJson(candidate[key])}`).join(",")}}`;
  return JSON.stringify(value);
}

function schemaRecord(value: unknown): JsonRecord {
  const candidate = record(value);
  if (!candidate) throw new Error("generated domain schema is malformed");
  return candidate;
}

function resolveReference(reference: unknown): JsonRecord {
  const prefix = "#/$defs/";
  if (typeof reference !== "string" || !reference.startsWith(prefix)) throw new Error("unsupported domain schema reference");
  const definitions = schemaRecord(CORE_DOMAIN_SCHEMA.$defs);
  return schemaRecord(definitions[reference.slice(prefix.length)]);
}

function canonicalUtc(value: string): boolean {
  const match = /^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,3}))?Z$/.exec(value);
  if (!match) return false;
  const timestamp = Date.parse(value);
  if (!Number.isFinite(timestamp)) return false;
  const expected = `${match[1]}.${(match[2] ?? "").padEnd(3, "0")}Z`;
  return new Date(timestamp).toISOString() === expected;
}

function validationErrors(value: unknown, rawSchema: unknown, path: string): string[] {
  const node = schemaRecord(rawSchema);
  if (node.$ref !== undefined) return validationErrors(value, resolveReference(node.$ref), path);
  const errors: string[] = [];
  if (Object.hasOwn(node, "const") && !deepEqual(value, node.const)) errors.push(`${path}: const`);
  if (Array.isArray(node.enum) && !node.enum.some((item) => deepEqual(value, item))) errors.push(`${path}: enum`);
  const alternatives = Array.isArray(node.oneOf) ? node.oneOf : Array.isArray(node.anyOf) ? node.anyOf : null;
  if (alternatives) {
    const matches = alternatives.filter((item) => validationErrors(value, item, path).length === 0).length;
    if ((Array.isArray(node.oneOf) && matches !== 1) || (Array.isArray(node.anyOf) && matches === 0)) errors.push(`${path}: alternatives`);
  }
  const type = node.type;
  if (type === "null" && value !== null) errors.push(`${path}: null`);
  if (type === "boolean" && typeof value !== "boolean") errors.push(`${path}: boolean`);
  if (type === "integer" && (typeof value !== "number" || !Number.isSafeInteger(value))) errors.push(`${path}: safe integer`);
  if (type === "number" && (typeof value !== "number" || !Number.isFinite(value))) errors.push(`${path}: finite number`);
  if (typeof value === "number" && Number.isFinite(value)) {
    if (typeof node.minimum === "number" && value < node.minimum) errors.push(`${path}: minimum`);
    if (typeof node.maximum === "number" && value > node.maximum) errors.push(`${path}: maximum`);
  }
  if (type === "string") {
    if (typeof value !== "string") errors.push(`${path}: string`);
    else {
      const length = Array.from(value).length;
      if (typeof node.minLength === "number" && length < node.minLength) errors.push(`${path}: minLength`);
      if (typeof node.maxLength === "number" && length > node.maxLength) errors.push(`${path}: maxLength`);
      if (typeof node.pattern === "string" && !new RegExp(node.pattern, "u").test(value)) errors.push(`${path}: pattern`);
      if (node.format === "date-time" && !canonicalUtc(value)) errors.push(`${path}: canonical UTC date-time`);
    }
  }
  if (type === "array") {
    if (!Array.isArray(value)) errors.push(`${path}: array`);
    else {
      if (typeof node.minItems === "number" && value.length < node.minItems) errors.push(`${path}: minItems`);
      if (typeof node.maxItems === "number" && value.length > node.maxItems) errors.push(`${path}: maxItems`);
      if (node.uniqueItems === true && new Set(value.map(stableJson)).size !== value.length) errors.push(`${path}: uniqueItems`);
      if (node.items !== undefined) value.forEach((item, index) => errors.push(...validationErrors(item, node.items, `${path}/${index}`)));
      if (node.contains !== undefined) {
        const matches = value.filter((item) => validationErrors(item, node.contains, path).length === 0).length;
        if (matches < (typeof node.minContains === "number" ? node.minContains : 1)) errors.push(`${path}: minContains`);
      }
    }
  }
  if (type === "object") {
    const candidate = record(value);
    if (!candidate) errors.push(`${path}: object`);
    else {
      const required = Array.isArray(node.required) ? node.required.filter((item): item is string => typeof item === "string") : [];
      for (const key of required) if (!Object.hasOwn(candidate, key)) errors.push(`${path}/${key}: required`);
      const properties = node.properties === undefined ? {} : schemaRecord(node.properties);
      if (node.additionalProperties === false) {
        for (const key of Object.keys(candidate)) if (!Object.hasOwn(properties, key)) errors.push(`${path}/${key}: additional property`);
      }
      for (const [key, propertySchema] of Object.entries(properties)) {
        if (Object.hasOwn(candidate, key)) errors.push(...validationErrors(candidate[key], propertySchema, `${path}/${key}`));
      }
    }
  } else if (node.properties !== undefined) {
    const candidate = record(value);
    if (candidate) {
      for (const [key, propertySchema] of Object.entries(schemaRecord(node.properties))) {
        if (Object.hasOwn(candidate, key)) errors.push(...validationErrors(candidate[key], propertySchema, `${path}/${key}`));
      }
    }
  }
  if (Array.isArray(node.allOf)) for (const item of node.allOf) errors.push(...validationErrors(value, item, path));
  if (node.if !== undefined && validationErrors(value, node.if, path).length === 0 && node.then !== undefined) {
    errors.push(...validationErrors(value, node.then, path));
  }
  return errors;
}

function pointerValue(value: unknown, pointer: unknown): unknown {
  if (typeof pointer !== "string" || !pointer.startsWith("/")) throw new Error("invalid semantic-rule pointer");
  let current: unknown = value;
  for (const segment of pointer.slice(1).split("/")) {
    const candidate = record(current);
    if (!candidate || !Object.hasOwn(candidate, segment)) throw new Error("semantic-rule pointer is missing");
    current = candidate[segment];
  }
  return current;
}

function semanticErrors(value: unknown): string[] {
  const errors: string[] = [];
  for (const rawRule of CORE_DOMAIN_SCHEMA["x-research-observatory-semanticRules"]) {
    const rule = schemaRecord(rawRule);
    const left = pointerValue(value, rule.leftPointer);
    const right = pointerValue(value, rule.rightPointer);
    let valid = false;
    if (rule.operator === "instant-not-after" && typeof left === "string" && typeof right === "string") valid = Date.parse(left) <= Date.parse(right);
    if (rule.operator === "not-equal") valid = !deepEqual(left, right);
    if (rule.operator === "set-disjoint" && Array.isArray(left) && Array.isArray(right)) {
      const rightValues = new Set(right.map(stableJson));
      valid = left.every((item) => !rightValues.has(stableJson(item)));
    }
    if (!valid) errors.push(String(rule.ruleId));
  }
  return errors;
}

export function isUuidV7(value: unknown): value is AggregateId {
  return typeof value === "string" && UUID_V7.test(value);
}

export function domainContractErrors(value: unknown): readonly string[] {
  const errors = validationErrors(value, CORE_DOMAIN_SCHEMA, "$");
  if (errors.length > 0) return errors;
  try { return semanticErrors(value); } catch { return ["semantic-rule-input-invalid"]; }
}

export function decodeCoreAggregate(value: unknown): CoreAggregate | null {
  return domainContractErrors(value).length === 0 ? value as CoreAggregate : null;
}
