// Generated by packages/contracts/corpus-reports/generate.mjs. Do not edit by hand.
// Source: packages/contracts/corpus-reports/corpus-report.schema.json

export type Count = number;

export interface CoverageSummary {
  readonly dimension: ReportDimension;
  readonly known: Count;
  readonly notReported: Count;
  readonly unknown: Count;
  readonly unavailable: Count;
}

export type Digest = string;

export type DiscoveryPathCount = number;

export type DiscoveryPathPairCount = number;

export type Identity = string;

export interface MembershipCount {
  readonly membership: ReportMembership;
  readonly itemCount: Count;
}

export type ProjectIdentity = string;

export type ReportDimension = "identifier" | "year" | "venue" | "language" | "discipline" | "oa" | "full-text";

export type ReportMembership = "candidate" | "included" | "excluded" | "withdrawn";

export type ReportRoute = "import-member" | "connector-record" | "citation" | "recommendation" | "manual";

export interface RouteContribution {
  readonly route: ReportRoute;
  readonly itemCount: Count;
  readonly discoveryPathCount: DiscoveryPathCount;
}

export interface RouteOverlap {
  readonly leftRoute: ReportRoute;
  readonly rightRoute: ReportRoute;
  readonly itemCount: Count;
  readonly discoveryPathPairCount: DiscoveryPathPairCount;
}

export interface SourceContribution {
  readonly sourceKey: SourceKey;
  readonly itemCount: Count;
  readonly discoveryPathCount: DiscoveryPathCount;
}

export type SourceKey = string;

export interface SourceOverlap {
  readonly leftSourceKey: SourceKey;
  readonly rightSourceKey: SourceKey;
  readonly itemCount: Count;
  readonly discoveryPathPairCount: DiscoveryPathPairCount;
}

export interface ValueBucket {
  readonly value: string;
  readonly itemCount: Count;
}

export interface ValueDistribution {
  readonly dimension: ReportDimension;
  readonly buckets: ReadonlyArray<ValueBucket>;
  readonly otherKnownCount: Count;
  readonly truncated: boolean;
}

export interface CorpusReportSnapshot {
  readonly schemaVersion: "1.0";
  readonly contractVersion: "1.0.0";
  readonly documentType: "research-observatory-corpus-report-snapshot";
  readonly snapshotId: Identity;
  readonly projectId: ProjectIdentity;
  readonly intentRevisionId: Identity;
  readonly protocolRevisionId: Identity;
  readonly ruleVersion: "corpus-report/1.0.0";
  readonly createdAt: string;
  readonly memberCount: Count;
  readonly discoveryPathCount: DiscoveryPathCount;
  readonly membersSha256: Digest;
  readonly membershipCounts: ReadonlyArray<MembershipCount>;
  readonly duplicateLinkedItemCount: Count;
  readonly unattributedItemCount: Count;
  readonly unattributedDiscoveryPathCount: DiscoveryPathCount;
  readonly sourceContributions: ReadonlyArray<SourceContribution>;
  readonly sourceOverlaps: ReadonlyArray<SourceOverlap>;
  readonly routeContributions: ReadonlyArray<RouteContribution>;
  readonly routeOverlaps: ReadonlyArray<RouteOverlap>;
  readonly coverage: ReadonlyArray<CoverageSummary>;
  readonly valueDistributions: ReadonlyArray<ValueDistribution>;
}

export interface ReportField {
  readonly dimension: ReportDimension;
  readonly state: ReportState;
  readonly value: string | null;
  readonly witnessRevisionId: Identity | null;
}

export interface ReportPath {
  readonly pathId: Identity;
  readonly sourceRevisionId: Identity;
  readonly contextRevisionId: Identity;
  readonly sourceKey: SourceKey | null;
  readonly route: ReportRoute;
  readonly metadataAssertionStatus: "retained" | "no-external-assertion";
  readonly reportInspectStatus: "allowed" | "unassessed";
  readonly rightsPolicyRevisionId: Identity | null;
  readonly rightsExpiresAt: string | null;
  readonly sourceCopyAvailability: "unknown";
}

export type ReportState = "known" | "not-reported" | "unknown" | "unavailable";

export interface CorpusReportMember {
  readonly schemaVersion: "1.0";
  readonly contractVersion: "1.0.0";
  readonly documentType: "research-observatory-corpus-report-member";
  readonly snapshotId: Identity;
  readonly projectId: ProjectIdentity;
  readonly itemId: Identity;
  readonly itemRevisionId: Identity;
  readonly workId: Identity;
  readonly workRevisionId: Identity;
  readonly membership: ReportMembership;
  readonly duplicateOfItemId: Identity | null;
  readonly displayLabel: string | null;
  readonly paths: ReadonlyArray<ReportPath>;
  readonly fields: ReadonlyArray<ReportField>;
}

export interface CorpusReportFilter {
  readonly kind: ReportFilterKind;
  readonly membership: ReportMembership | null;
  readonly sourceKey: SourceKey | null;
  readonly leftSourceKey: SourceKey | null;
  readonly rightSourceKey: SourceKey | null;
  readonly route: ReportRoute | null;
  readonly leftRoute: ReportRoute | null;
  readonly rightRoute: ReportRoute | null;
  readonly dimension: ReportDimension | null;
  readonly state: ReportState | null;
  readonly value: string | null;
}

export type ReportFilterKind = "all" | "membership" | "duplicate-linked" | "unattributed" | "source" | "route" | "source-overlap" | "route-overlap" | "coverage";

export interface CorpusReportDrillPage {
  readonly schemaVersion: "1.0";
  readonly contractVersion: "1.0.0";
  readonly documentType: "research-observatory-corpus-report-drill-page";
  readonly snapshotId: Identity;
  readonly projectId: ProjectIdentity;
  readonly filter: CorpusReportFilter;
  readonly members: ReadonlyArray<CorpusReportMember>;
  readonly nextCursor: string | null;
  readonly total: Count;
}

export type CorpusReportDocument = CorpusReportSnapshot | CorpusReportMember | CorpusReportDrillPage;
export const CORPUS_REPORT_SCHEMA_SHA256 = "b8d15056f472d640aff0ede1ff11c7000b255603c8741073ab62c9cd55dbd9fb";

const SCHEMA: unknown = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://research-observatory.local/contracts/corpus-reports/corpus-report.schema.json",
  "title": "Research Observatory corpus report snapshot, member and drill page",
  "description": "Immutable canonical-item report values. Core rechecks project, Intent, source, rights and current read authority in protected storage.",
  "x-research-observatory-semanticRules": [
    "snapshot-denominator-is-one-current-revision-per-canonical-item",
    "report-member-rows-are-strictly-ordered-by-item-id",
    "source-and-route-contributions-count-distinct-member-items-not-paths",
    "source-and-route-overlap-count-distinct-items-in-pair-intersection",
    "unattributed-paths-never-invent-source-roots",
    "all-seven-dimensions-classify-every-member-once",
    "known-values-require-exact-retained-rights-authorized-witness",
    "missing-values-are-not-zero-or-imputed",
    "summary-overflow-is-explicit-and-member-drill-stays-exact",
    "report-creation-and-current-read-authority-remain-core-responsibilities"
  ],
  "oneOf": [
    {
      "$ref": "#/$defs/CorpusReportSnapshot"
    },
    {
      "$ref": "#/$defs/CorpusReportMember"
    },
    {
      "$ref": "#/$defs/CorpusReportDrillPage"
    }
  ],
  "$defs": {
    "Count": {
      "maximum": 100000,
      "minimum": 0,
      "type": "integer"
    },
    "CoverageSummary": {
      "additionalProperties": false,
      "properties": {
        "dimension": {
          "$ref": "#/$defs/ReportDimension"
        },
        "known": {
          "$ref": "#/$defs/Count"
        },
        "notReported": {
          "$ref": "#/$defs/Count"
        },
        "unknown": {
          "$ref": "#/$defs/Count"
        },
        "unavailable": {
          "$ref": "#/$defs/Count"
        }
      },
      "required": [
        "dimension",
        "known",
        "notReported",
        "unknown",
        "unavailable"
      ],
      "type": "object"
    },
    "Digest": {
      "pattern": "^[0-9a-f]{64}$",
      "type": "string"
    },
    "DiscoveryPathCount": {
      "maximum": 100000000,
      "minimum": 0,
      "type": "integer"
    },
    "DiscoveryPathPairCount": {
      "maximum": 49950000000,
      "minimum": 0,
      "type": "integer"
    },
    "Identity": {
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "type": "string"
    },
    "MembershipCount": {
      "additionalProperties": false,
      "properties": {
        "membership": {
          "$ref": "#/$defs/ReportMembership"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        }
      },
      "required": [
        "membership",
        "itemCount"
      ],
      "type": "object"
    },
    "ProjectIdentity": {
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[47][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "type": "string"
    },
    "ReportDimension": {
      "enum": [
        "identifier",
        "year",
        "venue",
        "language",
        "discipline",
        "oa",
        "full-text"
      ],
      "type": "string"
    },
    "ReportMembership": {
      "enum": [
        "candidate",
        "included",
        "excluded",
        "withdrawn"
      ],
      "type": "string"
    },
    "ReportRoute": {
      "enum": [
        "import-member",
        "connector-record",
        "citation",
        "recommendation",
        "manual"
      ],
      "type": "string"
    },
    "RouteContribution": {
      "additionalProperties": false,
      "properties": {
        "route": {
          "$ref": "#/$defs/ReportRoute"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        },
        "discoveryPathCount": {
          "$ref": "#/$defs/DiscoveryPathCount"
        }
      },
      "required": [
        "route",
        "itemCount",
        "discoveryPathCount"
      ],
      "type": "object"
    },
    "RouteOverlap": {
      "additionalProperties": false,
      "properties": {
        "leftRoute": {
          "$ref": "#/$defs/ReportRoute"
        },
        "rightRoute": {
          "$ref": "#/$defs/ReportRoute"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        },
        "discoveryPathPairCount": {
          "$ref": "#/$defs/DiscoveryPathPairCount"
        }
      },
      "required": [
        "leftRoute",
        "rightRoute",
        "itemCount",
        "discoveryPathPairCount"
      ],
      "type": "object"
    },
    "SourceContribution": {
      "additionalProperties": false,
      "properties": {
        "sourceKey": {
          "$ref": "#/$defs/SourceKey"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        },
        "discoveryPathCount": {
          "$ref": "#/$defs/DiscoveryPathCount"
        }
      },
      "required": [
        "sourceKey",
        "itemCount",
        "discoveryPathCount"
      ],
      "type": "object"
    },
    "SourceKey": {
      "maxLength": 90,
      "pattern": "^(?:import:[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|connector:[a-z][a-z0-9-]{0,63})$",
      "type": "string"
    },
    "SourceOverlap": {
      "additionalProperties": false,
      "properties": {
        "leftSourceKey": {
          "$ref": "#/$defs/SourceKey"
        },
        "rightSourceKey": {
          "$ref": "#/$defs/SourceKey"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        },
        "discoveryPathPairCount": {
          "$ref": "#/$defs/DiscoveryPathPairCount"
        }
      },
      "required": [
        "leftSourceKey",
        "rightSourceKey",
        "itemCount",
        "discoveryPathPairCount"
      ],
      "type": "object"
    },
    "ValueBucket": {
      "additionalProperties": false,
      "properties": {
        "value": {
          "maxLength": 512,
          "minLength": 1,
          "type": "string"
        },
        "itemCount": {
          "$ref": "#/$defs/Count"
        }
      },
      "required": [
        "value",
        "itemCount"
      ],
      "type": "object"
    },
    "ValueDistribution": {
      "additionalProperties": false,
      "properties": {
        "dimension": {
          "$ref": "#/$defs/ReportDimension"
        },
        "buckets": {
          "items": {
            "$ref": "#/$defs/ValueBucket"
          },
          "maxItems": 50,
          "type": "array"
        },
        "otherKnownCount": {
          "$ref": "#/$defs/Count"
        },
        "truncated": {
          "type": "boolean"
        }
      },
      "required": [
        "dimension",
        "buckets",
        "otherKnownCount",
        "truncated"
      ],
      "type": "object"
    },
    "CorpusReportSnapshot": {
      "additionalProperties": false,
      "properties": {
        "schemaVersion": {
          "const": "1.0",
          "type": "string"
        },
        "contractVersion": {
          "const": "1.0.0",
          "type": "string"
        },
        "documentType": {
          "const": "research-observatory-corpus-report-snapshot",
          "type": "string"
        },
        "snapshotId": {
          "$ref": "#/$defs/Identity"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectIdentity"
        },
        "intentRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "protocolRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "ruleVersion": {
          "const": "corpus-report/1.0.0",
          "type": "string"
        },
        "createdAt": {
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
          "type": "string"
        },
        "memberCount": {
          "$ref": "#/$defs/Count"
        },
        "discoveryPathCount": {
          "$ref": "#/$defs/DiscoveryPathCount"
        },
        "membersSha256": {
          "$ref": "#/$defs/Digest"
        },
        "membershipCounts": {
          "items": {
            "$ref": "#/$defs/MembershipCount"
          },
          "maxItems": 4,
          "minItems": 4,
          "type": "array"
        },
        "duplicateLinkedItemCount": {
          "$ref": "#/$defs/Count"
        },
        "unattributedItemCount": {
          "$ref": "#/$defs/Count"
        },
        "unattributedDiscoveryPathCount": {
          "$ref": "#/$defs/DiscoveryPathCount"
        },
        "sourceContributions": {
          "items": {
            "$ref": "#/$defs/SourceContribution"
          },
          "maxItems": 512,
          "type": "array"
        },
        "sourceOverlaps": {
          "items": {
            "$ref": "#/$defs/SourceOverlap"
          },
          "maxItems": 20000,
          "type": "array"
        },
        "routeContributions": {
          "items": {
            "$ref": "#/$defs/RouteContribution"
          },
          "maxItems": 5,
          "minItems": 5,
          "type": "array"
        },
        "routeOverlaps": {
          "items": {
            "$ref": "#/$defs/RouteOverlap"
          },
          "maxItems": 10,
          "type": "array"
        },
        "coverage": {
          "items": {
            "$ref": "#/$defs/CoverageSummary"
          },
          "maxItems": 7,
          "minItems": 7,
          "type": "array"
        },
        "valueDistributions": {
          "items": {
            "$ref": "#/$defs/ValueDistribution"
          },
          "maxItems": 6,
          "minItems": 6,
          "type": "array"
        }
      },
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "snapshotId",
        "projectId",
        "intentRevisionId",
        "protocolRevisionId",
        "ruleVersion",
        "createdAt",
        "memberCount",
        "discoveryPathCount",
        "membersSha256",
        "membershipCounts",
        "duplicateLinkedItemCount",
        "unattributedItemCount",
        "unattributedDiscoveryPathCount",
        "sourceContributions",
        "sourceOverlaps",
        "routeContributions",
        "routeOverlaps",
        "coverage",
        "valueDistributions"
      ],
      "type": "object"
    },
    "ReportField": {
      "additionalProperties": false,
      "properties": {
        "dimension": {
          "$ref": "#/$defs/ReportDimension"
        },
        "state": {
          "$ref": "#/$defs/ReportState"
        },
        "value": {
          "anyOf": [
            {
              "maxLength": 512,
              "minLength": 1,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "witnessRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "dimension",
        "state",
        "value",
        "witnessRevisionId"
      ],
      "type": "object"
    },
    "ReportPath": {
      "additionalProperties": false,
      "properties": {
        "pathId": {
          "$ref": "#/$defs/Identity"
        },
        "sourceRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "contextRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "sourceKey": {
          "anyOf": [
            {
              "$ref": "#/$defs/SourceKey"
            },
            {
              "type": "null"
            }
          ]
        },
        "route": {
          "$ref": "#/$defs/ReportRoute"
        },
        "metadataAssertionStatus": {
          "enum": [
            "retained",
            "no-external-assertion"
          ],
          "type": "string"
        },
        "reportInspectStatus": {
          "enum": [
            "allowed",
            "unassessed"
          ],
          "type": "string"
        },
        "rightsPolicyRevisionId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "rightsExpiresAt": {
          "anyOf": [
            {
              "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$",
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "sourceCopyAvailability": {
          "const": "unknown",
          "type": "string"
        }
      },
      "required": [
        "pathId",
        "sourceRevisionId",
        "contextRevisionId",
        "sourceKey",
        "route",
        "metadataAssertionStatus",
        "reportInspectStatus",
        "rightsPolicyRevisionId",
        "rightsExpiresAt",
        "sourceCopyAvailability"
      ],
      "type": "object"
    },
    "ReportState": {
      "enum": [
        "known",
        "not-reported",
        "unknown",
        "unavailable"
      ],
      "type": "string"
    },
    "CorpusReportMember": {
      "additionalProperties": false,
      "properties": {
        "schemaVersion": {
          "const": "1.0",
          "type": "string"
        },
        "contractVersion": {
          "const": "1.0.0",
          "type": "string"
        },
        "documentType": {
          "const": "research-observatory-corpus-report-member",
          "type": "string"
        },
        "snapshotId": {
          "$ref": "#/$defs/Identity"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectIdentity"
        },
        "itemId": {
          "$ref": "#/$defs/Identity"
        },
        "itemRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "workId": {
          "$ref": "#/$defs/Identity"
        },
        "workRevisionId": {
          "$ref": "#/$defs/Identity"
        },
        "membership": {
          "$ref": "#/$defs/ReportMembership"
        },
        "duplicateOfItemId": {
          "anyOf": [
            {
              "$ref": "#/$defs/Identity"
            },
            {
              "type": "null"
            }
          ]
        },
        "displayLabel": {
          "anyOf": [
            {
              "maxLength": 512,
              "minLength": 1,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "paths": {
          "items": {
            "$ref": "#/$defs/ReportPath"
          },
          "maxItems": 1000,
          "minItems": 1,
          "type": "array"
        },
        "fields": {
          "items": {
            "$ref": "#/$defs/ReportField"
          },
          "maxItems": 7,
          "minItems": 7,
          "type": "array"
        }
      },
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "snapshotId",
        "projectId",
        "itemId",
        "itemRevisionId",
        "workId",
        "workRevisionId",
        "membership",
        "duplicateOfItemId",
        "displayLabel",
        "paths",
        "fields"
      ],
      "type": "object"
    },
    "CorpusReportFilter": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "$ref": "#/$defs/ReportFilterKind"
        },
        "membership": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportMembership"
            },
            {
              "type": "null"
            }
          ]
        },
        "sourceKey": {
          "anyOf": [
            {
              "$ref": "#/$defs/SourceKey"
            },
            {
              "type": "null"
            }
          ]
        },
        "leftSourceKey": {
          "anyOf": [
            {
              "$ref": "#/$defs/SourceKey"
            },
            {
              "type": "null"
            }
          ]
        },
        "rightSourceKey": {
          "anyOf": [
            {
              "$ref": "#/$defs/SourceKey"
            },
            {
              "type": "null"
            }
          ]
        },
        "route": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportRoute"
            },
            {
              "type": "null"
            }
          ]
        },
        "leftRoute": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportRoute"
            },
            {
              "type": "null"
            }
          ]
        },
        "rightRoute": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportRoute"
            },
            {
              "type": "null"
            }
          ]
        },
        "dimension": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportDimension"
            },
            {
              "type": "null"
            }
          ]
        },
        "state": {
          "anyOf": [
            {
              "$ref": "#/$defs/ReportState"
            },
            {
              "type": "null"
            }
          ]
        },
        "value": {
          "anyOf": [
            {
              "maxLength": 512,
              "minLength": 1,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "kind",
        "membership",
        "sourceKey",
        "leftSourceKey",
        "rightSourceKey",
        "route",
        "leftRoute",
        "rightRoute",
        "dimension",
        "state",
        "value"
      ],
      "type": "object"
    },
    "ReportFilterKind": {
      "enum": [
        "all",
        "membership",
        "duplicate-linked",
        "unattributed",
        "source",
        "route",
        "source-overlap",
        "route-overlap",
        "coverage"
      ],
      "type": "string"
    },
    "CorpusReportDrillPage": {
      "additionalProperties": false,
      "properties": {
        "schemaVersion": {
          "const": "1.0",
          "type": "string"
        },
        "contractVersion": {
          "const": "1.0.0",
          "type": "string"
        },
        "documentType": {
          "const": "research-observatory-corpus-report-drill-page",
          "type": "string"
        },
        "snapshotId": {
          "$ref": "#/$defs/Identity"
        },
        "projectId": {
          "$ref": "#/$defs/ProjectIdentity"
        },
        "filter": {
          "$ref": "#/$defs/CorpusReportFilter"
        },
        "members": {
          "items": {
            "$ref": "#/$defs/CorpusReportMember"
          },
          "maxItems": 100,
          "type": "array"
        },
        "nextCursor": {
          "anyOf": [
            {
              "maxLength": 512,
              "minLength": 1,
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "total": {
          "$ref": "#/$defs/Count"
        }
      },
      "required": [
        "schemaVersion",
        "contractVersion",
        "documentType",
        "snapshotId",
        "projectId",
        "filter",
        "members",
        "nextCursor",
        "total"
      ],
      "type": "object"
    }
  }
};
type JsonRecord = Record<string, unknown>;
const FORBIDDEN = new Set(["__proto__", "constructor", "prototype"]);
const DIMENSIONS = ["identifier", "year", "venue", "language", "discipline", "oa", "full-text"];
const VALUE_DIMENSIONS = ["year", "venue", "language", "discipline", "oa", "full-text"];
const ROUTES = ["import-member", "connector-record", "citation", "recommendation", "manual"];
const MEMBERSHIPS = ["candidate", "included", "excluded", "withdrawn"];

function record(value: unknown): JsonRecord | null {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) return null;
  const descriptors = Object.getOwnPropertyDescriptors(value);
  if (Object.keys(descriptors).length > 64 || Object.entries(descriptors).some(([key, property]) =>
    FORBIDDEN.has(key) || !("value" in property))) return null;
  return value as JsonRecord;
}

function matches(value: unknown, rawNode: unknown, depth = 0): boolean {
  if (depth > 20) return false;
  const node = record(rawNode);
  const definitions = record(record(SCHEMA)?.$defs);
  if (!node || !definitions) return false;
  if (typeof node.$ref === "string") {
    const name = node.$ref.startsWith("#/$defs/") ? node.$ref.slice(8) : "";
    return name !== "" && matches(value, definitions[name], depth + 1);
  }
  if (Object.hasOwn(node, "const") && value !== node.const) return false;
  if (Array.isArray(node.enum) && !node.enum.includes(value)) return false;
  if (Array.isArray(node.anyOf) && !node.anyOf.some((option) => matches(value, option, depth + 1))) return false;
  if (Array.isArray(node.oneOf) && node.oneOf.filter((option) => matches(value, option, depth + 1)).length !== 1) return false;
  if (node.type === "null") return value === null;
  if (node.type === "string" || typeof node.pattern === "string") {
    if (typeof value !== "string") return false;
    const length = Array.from(value).length;
    if (length > 512) return false;
    if (typeof node.minLength === "number" && length < node.minLength) return false;
    if (typeof node.maxLength === "number" && length > node.maxLength) return false;
    if (typeof node.pattern === "string") {
      const hit = new RegExp(node.pattern, "u").exec(value);
      if (!hit || hit.index !== 0 || hit[0].length !== value.length) return false;
    }
  }
  if (node.type === "integer") {
    if (!Number.isSafeInteger(value)) return false;
    if (typeof node.minimum === "number" && (value as number) < node.minimum) return false;
    if (typeof node.maximum === "number" && (value as number) > node.maximum) return false;
  }
  if (node.type === "boolean" && typeof value !== "boolean") return false;
  if (node.type === "array") {
    if (!Array.isArray(value) || value.length > 20000) return false;
    if (typeof node.minItems === "number" && value.length < node.minItems) return false;
    if (typeof node.maxItems === "number" && value.length > node.maxItems) return false;
    if (!value.every((item) => matches(item, node.items, depth + 1))) return false;
  }
  if (node.type === "object") {
    const item = record(value);
    const properties = record(node.properties);
    if (!item || !properties || !Array.isArray(node.required)) return false;
    const keys = Object.keys(item);
    if (node.additionalProperties === false && keys.some((key) => !Object.hasOwn(properties, key))) return false;
    if (!node.required.every((key) => typeof key === "string" && Object.hasOwn(item, key))) return false;
    if (!keys.every((key) => matches(item[key], properties[key], depth + 1))) return false;
  }
  return true;
}

function orderedUnique(values: unknown): boolean {
  return Array.isArray(values) && values.every((value, index) =>
    typeof value === "string" && (index === 0 || values[index - 1] < value));
}

function codePointCompare(left: string, right: string): number {
  const a = Array.from(left, (letter) => letter.codePointAt(0) ?? 0);
  const b = Array.from(right, (letter) => letter.codePointAt(0) ?? 0);
  for (let index = 0; index < Math.min(a.length, b.length); index += 1) {
    if (a[index] !== b[index]) return Number(a[index]) - Number(b[index]);
  }
  return a.length - b.length;
}

function canonicalUtcMillis(value: unknown): boolean {
  return typeof value === "string" && !value.startsWith("0000")
    && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
}

function rows(value: unknown): JsonRecord[] | null {
  if (!Array.isArray(value)) return null;
  const mapped = value.map(record);
  return mapped.every((item) => item !== null) ? mapped as JsonRecord[] : null;
}

function filterError(value: unknown): string | null {
  const filter = record(value);
  if (!filter) return "corpus-report-filter-invalid";
  const present = new Set(["membership", "sourceKey", "leftSourceKey", "rightSourceKey", "route", "leftRoute", "rightRoute",
    "dimension", "state", "value"].filter((name) => filter[name] !== null));
  const required: Record<string, string[]> = {
    all: [], membership: ["membership"], "duplicate-linked": [], unattributed: [],
    source: ["sourceKey"], route: ["route"],
    "source-overlap": ["leftSourceKey", "rightSourceKey"],
    "route-overlap": ["leftRoute", "rightRoute"], coverage: ["dimension", "state"],
  };
  const names = required[String(filter.kind)];
  if (!names || !names.every((name) => present.has(name))) return "corpus-report-filter-invalid";
  const allowed = new Set(names);
  if (filter.kind === "coverage" && filter.state === "known") allowed.add("value");
  if ([...present].some((name) => !allowed.has(name))) return "corpus-report-filter-invalid";
  if (filter.kind === "source-overlap" && String(filter.leftSourceKey) >= String(filter.rightSourceKey))
    return "corpus-report-filter-invalid";
  if (filter.kind === "route-overlap" && String(filter.leftRoute) >= String(filter.rightRoute))
    return "corpus-report-filter-invalid";
  return null;
}

function memberError(document: JsonRecord): string | null {
  if ([document.itemRevisionId, document.workId].includes(document.itemId)
    || document.duplicateOfItemId === document.itemId) return "corpus-report-member-identity-invalid";
  const paths = rows(document.paths);
  const fields = rows(document.fields);
  if (!paths || !fields || !orderedUnique(paths.map((item) => item.pathId)))
    return "corpus-report-path-order-invalid";
  if (paths.some((item) =>
    (item.route === "import-member" && (typeof item.sourceKey !== "string" || !item.sourceKey.startsWith("import:")))
    || (item.route === "connector-record"
      && (typeof item.sourceKey !== "string" || !item.sourceKey.startsWith("connector:")))))
    return "corpus-report-source-root-invalid";
  for (const path of paths) {
    const retained = path.metadataAssertionStatus === "retained";
    if (retained !== (path.reportInspectStatus === "allowed")
      || retained !== (path.rightsPolicyRevisionId !== null)
      || (!retained && path.rightsExpiresAt !== null)) return "corpus-report-path-rights-invalid";
    if (path.rightsExpiresAt !== null && !canonicalUtcMillis(path.rightsExpiresAt))
      return "corpus-report-path-rights-time-invalid";
  }
  if (fields.map((item) => item.dimension).join("|") !== DIMENSIONS.join("|"))
    return "corpus-report-field-set-invalid";
  for (const field of fields) {
    if (field.state === "known") {
      if (field.value === null || field.witnessRevisionId === null) return "corpus-report-known-witness-required";
      if (["oa", "full-text"].includes(String(field.dimension)) && !["yes", "no"].includes(String(field.value)))
        return "corpus-report-status-value-invalid";
    } else if (field.value !== null) return "corpus-report-missing-value-invalid";
  }
  return null;
}

function snapshotError(document: JsonRecord): string | null {
  if (!canonicalUtcMillis(document.createdAt)) return "corpus-report-time-invalid";
  const memberships = rows(document.membershipCounts);
  const routes = rows(document.routeContributions);
  const coverage = rows(document.coverage);
  const distributions = rows(document.valueDistributions);
  const sources = rows(document.sourceContributions);
  const sourcePairs = rows(document.sourceOverlaps);
  const routePairs = rows(document.routeOverlaps);
  if (!memberships || !routes || !coverage || !distributions || !sources || !sourcePairs || !routePairs)
    return "corpus-report-summary-invalid";
  if (memberships.map((item) => item.membership).join("|") !== MEMBERSHIPS.join("|")
    || routes.map((item) => item.route).join("|") !== ROUTES.join("|")
    || coverage.map((item) => item.dimension).join("|") !== DIMENSIONS.join("|")
    || distributions.map((item) => item.dimension).join("|") !== VALUE_DIMENSIONS.join("|"))
    return "corpus-report-summary-invalid";
  const total = Number(document.memberCount);
  const pathTotal = Number(document.discoveryPathCount);
  const unattributedPaths = Number(document.unattributedDiscoveryPathCount);
  if (memberships.reduce((sum, item) => sum + Number(item.itemCount), 0) !== total
    || Number(document.duplicateLinkedItemCount) > total || Number(document.unattributedItemCount) > total
    || pathTotal < total || unattributedPaths > pathTotal
    || unattributedPaths < Number(document.unattributedItemCount))
    return "corpus-report-member-count-invalid";
  if (coverage.some((item) => ["known", "notReported", "unknown", "unavailable"]
    .reduce((sum, key) => sum + Number(item[key]), 0) !== total)) return "corpus-report-coverage-count-invalid";
  for (const distribution of distributions) {
    const buckets = rows(distribution.buckets);
    const matching = coverage.find((item) => item.dimension === distribution.dimension);
    if (!buckets || !matching || (Number(distribution.otherKnownCount) > 0) !== distribution.truncated
      || new Set(buckets.map((item) => item.value)).size !== buckets.length
      || buckets.some((item) => item.itemCount === 0)
      || buckets.some((item, index) => index > 0
        && (Number(buckets[index - 1]?.itemCount) < Number(item.itemCount)
          || (buckets[index - 1]?.itemCount === item.itemCount
            && codePointCompare(String(buckets[index - 1]?.value), String(item.value)) >= 0)))
      || buckets.reduce((sum, item) => sum + Number(item.itemCount), 0)
      + Number(distribution.otherKnownCount) !== matching.known) return "corpus-report-distribution-invalid";
  }
  const sourceCounts = new Map(sources.map((item) => [String(item.sourceKey), Number(item.itemCount)]));
  const routeCounts = new Map(routes.map((item) => [String(item.route), Number(item.itemCount)]));
  if ([...sourceCounts.values(), ...routeCounts.values()].some((count) => count > total))
    return "corpus-report-contribution-count-invalid";
  if (sources.reduce((sum, item) => sum + Number(item.discoveryPathCount), 0) + unattributedPaths !== pathTotal
    || routes.reduce((sum, item) => sum + Number(item.discoveryPathCount), 0) !== pathTotal
    || [...sources, ...routes].some((item) => Number(item.discoveryPathCount) < Number(item.itemCount)
      || Number(item.discoveryPathCount) > pathTotal))
    return "corpus-report-discovery-path-count-invalid";
  if (!orderedUnique(sources.map((item) => item.sourceKey))
    || sourcePairs.some((item) => String(item.leftSourceKey) >= String(item.rightSourceKey))
    || routePairs.some((item) => String(item.leftRoute) >= String(item.rightRoute)))
    return "corpus-report-overlap-invalid";
  const sourcePairKeys = sourcePairs.map((item) => `${item.leftSourceKey}|${item.rightSourceKey}`);
  const routePairKeys = routePairs.map((item) => `${item.leftRoute}|${item.rightRoute}`);
  if (!orderedUnique(sourcePairKeys) || !orderedUnique(routePairKeys)
    || sourcePairs.some((item) => item.itemCount === 0
      || Number(item.discoveryPathPairCount) < Number(item.itemCount)
      || Number(item.itemCount) > Math.min(
      sourceCounts.get(String(item.leftSourceKey)) ?? 0, sourceCounts.get(String(item.rightSourceKey)) ?? 0))
    || routePairs.some((item) => item.itemCount === 0
      || Number(item.discoveryPathPairCount) < Number(item.itemCount)
      || Number(item.itemCount) > Math.min(
      routeCounts.get(String(item.leftRoute)) ?? 0, routeCounts.get(String(item.rightRoute)) ?? 0)))
    return "corpus-report-overlap-invalid";
  return null;
}

function memberMatchesFilter(member: JsonRecord, rawFilter: unknown): boolean {
  const filter = record(rawFilter);
  const paths = rows(member.paths);
  const fields = rows(member.fields);
  if (!filter || !paths || !fields) return false;
  const sources = new Set<unknown>(paths.map((item) => item.sourceKey).filter((item) => item !== null));
  const routes = new Set<unknown>(paths.map((item) => item.route));
  if (filter.kind === "all") return true;
  if (filter.kind === "membership") return member.membership === filter.membership;
  if (filter.kind === "duplicate-linked") return member.duplicateOfItemId !== null;
  if (filter.kind === "unattributed") return paths.some((item) => item.sourceKey === null);
  if (filter.kind === "source") return sources.has(filter.sourceKey);
  if (filter.kind === "route") return routes.has(filter.route);
  if (filter.kind === "source-overlap") return sources.has(filter.leftSourceKey) && sources.has(filter.rightSourceKey);
  if (filter.kind === "route-overlap") return routes.has(filter.leftRoute) && routes.has(filter.rightRoute);
  const field = fields.find((item) => item.dimension === filter.dimension);
  return field !== undefined && field.state === filter.state
    && (filter.value === null || field.value === filter.value);
}

function pageError(document: JsonRecord): string | null {
  const members = rows(document.members);
  if (!members || filterError(document.filter)) return "corpus-report-page-invalid";
  if (members.some((item) => item.snapshotId !== document.snapshotId || item.projectId !== document.projectId
    || memberError(item) !== null)) return "corpus-report-page-scope-invalid";
  if (!orderedUnique(members.map((item) => item.itemId)) || members.length > Number(document.total))
    return "corpus-report-page-order-invalid";
  if (document.nextCursor !== null && members.length === 0) return "corpus-report-page-cursor-invalid";
  if (members.some((item) => !memberMatchesFilter(item, document.filter)))
    return "corpus-report-page-filter-invalid";
  return null;
}

function semanticError(document: JsonRecord): string | null {
  if (document.documentType === "research-observatory-corpus-report-snapshot") return snapshotError(document);
  if (document.documentType === "research-observatory-corpus-report-member") return memberError(document);
  if (document.documentType === "research-observatory-corpus-report-drill-page") return pageError(document);
  return "corpus-report-document-type-invalid";
}

export function corpusReportContractErrors(value: unknown): ReadonlyArray<string> {
  try {
    if (!matches(value, SCHEMA)) return Object.freeze(["corpus-report-schema-invalid"]);
    const error = semanticError(value as JsonRecord);
    return Object.freeze(error === null ? [] : [error]);
  } catch {
    return Object.freeze(["corpus-report-schema-invalid"]);
  }
}

export function decodeCorpusReportDocument(value: unknown): CorpusReportDocument | null {
  if (corpusReportContractErrors(value).length !== 0) return null;
  try {
    const owned = JSON.parse(JSON.stringify(value)) as CorpusReportDocument;
    if (corpusReportContractErrors(owned).length !== 0) return null;
    const freeze = (item: unknown): void => {
      if (item !== null && typeof item === "object") {
        Object.values(item).forEach(freeze);
        Object.freeze(item);
      }
    };
    freeze(owned);
    return owned;
  } catch {
    return null;
  }
}
